### ISSUE TITLE
macOS/Emacs key bindings for navigating lists

### ISSUE THREAD

**Issue by jackbaty** [silverbulletmd/silverbullet#1006]
On macOS, there are a number of built-in key bindings based on the default Emacs bindings. In particular, CTRL-n and CTRL-p for navigating up and down selection/dropdown lists. I use this everywhere and all the time, but they don’t work in SilverBullet. The arrow keys on my (HHKB) keyboard are inconvenient, so I’d love to use the “normal” bindings.

Is there any way to enable those bindings (CTRL-n / CTRL-p) in SilverBullet for navigating things like the page switcher and command palette?

Thanks.

**Comment by dchobarkar** [comment]
Hi there,

I would like to work on this issue. Could you please assign it to me?

Thank you!
Darshan

**Comment by zefhemel** [comment]
Of course @dchobarkar

**Comment by zefhemel** [comment]
@dchobarkar btw, you will want to look at web/components/filter.tsx around line 140

**Comment by dchobarkar** [comment]
Hi @zefhemel,

I have started working on this issue. I will update you with my progress soon.

Thank you,
Darshan
