### ISSUE TITLE
File tree

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#102]
I've resisted this for a long time, but it may be useful to have a "traditional" file/folder tree on the left-hand side. Fully optional of course. 

It should support folding and collapsing of folders, and highlighting your currently open page. 

This is fully implementable as a plug, and should use the `showPanel("lhs", ...)` API.

**Comment by vassudanagunta** [comment]
This would complicate how page links work. 

Given this Hierarchy:
```
- Project A
  - Principles
  - Parser
  - Renderer
- Project B
  - Principles
  - Schedule
  - Team
- Principles
```

How would *Project A/Parser* link to each of the three *Principles* pages? Perhaps:

- fully qualified path to link to any place in the tree, e.g. `[[/Project B/Principles]]`
- `[[Principles]]` would link to page in same folder only

Alternatively, `[[Principles]]` could resolve to the "nearest" match, e.g. first match in this order: in same folder, first one down the tree (if deep trees are supported), first one up the tree. Fully qualified paths must be used to jump across branches.

Alternatively, you could force page names to remain unique irrespective of path. Folders are merely for organization and do not define a hierarchical page namespace.

**Comment by vassudanagunta** [comment]
Also it would be nice if, continuing my example above, a folder node could have its own content, much like index pages on a website.

**Comment by zefhemel** [comment]
@vassudanagunta this already works perfectly fine now, and you can use folders right now simply by putting slashes in page names (it creates the hierarchy automatically). There's a discussion on how to handle page reference links here: #116 

Right now we always require "full" links, and there's just shortened to the last pieces by live preview. Try it :)

**Comment by zefhemel** [comment]
> Also it would be nice if, continuing my example above, a folder node could have its own content, much like index pages on a website.

And this also works perfectly fine, just create a page named "People" and one named "People/Vas" and this is what you'll get.

Bonus hidden feature, when you're on the "People/Vas" page, go to the Page switcher and hit the spacebar, it will complete the page name to be "People/" so you can easily add another page in that folder.

**Comment by orausch** [comment]
Made a basic plugin for this here: https://github.com/orausch/silverbullet-filetree

**Comment by zefhemel** [comment]
@orausch just tried it out, nice start! I have been looking around for a solid file tree component, one where we could also support things like drag & drop for moving pages etc, did you custom build something here?

**Comment by ffernn-dev** [comment]
+1 on this, I haven't looked at the codebase yet but I might take a crack at it when I have some time.

**Comment by joekrill** [comment]
> I have been looking around for a solid file tree component, one where we could also support things like drag & drop [...]

@zefhemel  I started playing around with this idea myself, but I'm a little stuck: I don't see a way to render a preact component from a plug? `showPanel` just takes some html. I guess you could maybe pass along a JavaScript file as an asset and have that render a component tree? But that adds some further complications (i.e. does this require bundle a second instance of the preact library? or is there a way to use it from the main bundle?; and how do we fetch data for the component?; How do we keep things in sync between the iframe of the plug and the main UI?)

Is there already something in place that allows this? Or would this require some sort of change to the plug API? Or is it just something that isn't supported and isn't planned to be?

(I don't mean to hijack this issue... perhaps this discussion belongs elsewhere?)

**Comment by joekrill** [comment]
I put together a tree view implementation here: https://github.com/joekrill/silverbullet-treeview

It should be production ready. I found an excellent library called [SortableTree](https://marcantondahmen.github.io/sortable-tree/) that does most of the heavy lifting and seems to have everything we're looking for her.

Some notes on the implementation:

**Key bindings:**

In most apps, `Ctrl+b`/`Cmd+b` seems to be the preferred keybinding for toggling some sort of sidebar navigation. That currently toggles bold in the editor, though, so I chose `Ctrl-alt-b`/`Cmd-alt-b` instead here. 

**Drag & Drop:**

This should be relatively simple to implement, but I've held off on this for now. The built-in `index` plug has the functionality needed for this implemented already (via `renamePageCommand` and `renamePrefixCommand`), but it's not really usable for the purpose of this plug at the moment, for a few reasons:

- `renamePageCommand` will only work against the current page. You can send it the new page name, but there's no way to ask it to rename a page other than the current one.
- `renamePrefixCommand` does not have a way to programatically pass in the old and new prefixes. It will always prompt the user for the prefix. It also always prompts for confirmation (which maybe we want? but we may want to bypass this?)

I considered reimplementing (read: copy/pasting) the code into this plug, but it's quite a bit of code and relatively complex - I think it would probably be better to change the existing commands to be able to accept some optional parameters to avoid prompting the user (and to allow renaming a page other than the current page), and use that instead. 

**Theming + Dark Mode:**

I've tried to keep the styles consistent and aligned with the existing look and feel. And I implemented dark mode, too. But that required a lot of copy/pasting of CSS variables from the main repo. 

I think it would be great if we'd consider injecting the existing theme variables, fonts, and `data-theme` value into the iframe of the `Panel` component. That would allow anything using `showPanel` to provide a more consistent experience. Maybe these would be opt-in for callers of `showPanel` as to potentially avoid breaking any existing plugs. I can create an issue and even work on the implementation if there's alignment on that idea.

**Comment by zefhemel** [comment]
Very, very excited about this @joekrill ! Can't wait to test this properly.

**Comment by zefhemel** [comment]
I just added this plug to the website (will update soon) and thereby am going to consider this issue closed!
