### ISSUE TITLE
GET request to /index.json returning HTML for main page

### ISSUE THREAD

**Issue by stevegg** [silverbulletmd/silverbullet#1029]
Hi,

I'm trying to understand how to use the API to programatically fetch all documents within my notes instance.  My notes are running on a local server with the ip: 10.0.1.234 so my request is:

curl --location 'http://10.0.1.234/index.json'

This is returning the first page of my notes instead of the expected JSON.

`<!DOCTYPE html>
<html lang="en" prefix="og: https://ogp.me/ns#">

<head>
	<meta charset="utf-8" />
	<meta name="viewport"
		content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<base href="/" />
	<link rel="apple-touch-icon" href="/.client/logo.png">
	<meta name="theme-color" content="#e1e1e1" media="(prefers-color-scheme: light)">
	<meta name="theme-color" content="#262626" media="(prefers-color-scheme: dark)">

	<title>index</title>
	<meta property="og:image" content="/.client/logo.png">
	<meta property="og:description"
		content=" Steve’s NotesThis is my collection of notes about...well..everything. Todos{{{task select name render [[Library/Core/Query/Page]]}}}HomeWork">`

I'm running Silverbullet 0.9.0 via Deno.

What am I doing wrong here?

I've also tried adding headers for Accept like this:

`curl --location 'http://10.0.1.234/index.json' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'`

Any help would be greatly appreciated.

**Comment by zefhemel** [comment]
Have a look at this: https://silverbullet.md/API

You're missing an x-sync-mode header.

**Comment by stevegg** [comment]
> Have a look at this: https://silverbullet.md/API
> 
> You're missing an x-sync-mode header.

Well I knew it would end up being something simple.  Thought I had read that document a few times but missed that completely.  Thank you!

Steve
