### ISSUE TITLE
diffrent behavior between query of items and tasks

### ISSUE THREAD

**Issue by davidbeijinho** [silverbulletmd/silverbullet#1052]
I`m getting different results for this queries

In task we get sub items and not for items, is this the expected results is there a way in items to also get sub items?

![image](https://github.com/user-attachments/assets/d45894f4-04b6-4983-9c85-b7d8945fb909)

**Comment by davidbeijinho** [comment]
![image](https://github.com/user-attachments/assets/c8c7bcfd-a142-4a7e-993a-d9a4a4890af8)

in this query i would like to get all my books, but if the item is a sub item i cant get it in the query

**Comment by davidbeijinho** [comment]
with #tags it works but then i cant get the attributes

![image](https://github.com/user-attachments/assets/eeb07145-e99c-4bdd-aef8-fc3eb39d9bc2)

**Comment by zefhemel** [comment]
This should now be fixed.
