### ISSUE TITLE
[Request] Unauthenticated ping endpoint

### ISSUE THREAD

**Issue by cterence** [silverbulletmd/silverbullet#1069]
Hi, I'm currently hosting Silverbullet on Kubernetes and enabled authentication.

I found out about the /.ping endpoint : 
https://github.com/silverbulletmd/silverbullet/blob/bddb1b5da9cdb56b058058676d2a53b8ff55a88e/server/http_server.ts#L470 which initially made a good fit for a liveness/readiness probe endpoint.
However, enabling authentication restrict access to this endpoint as well, which is not ideal.

Would it be possible to add a similar endpoint (`/.health`, `/.alive` for example) which would stay unauthenticated in any case ?

**Comment by zefhemel** [comment]
Maybe you can use `/_` for this, e.g. `https://silverbullet.md/_/`. It will return a 404, but that means it works :) And it's unauthenticated.

**Comment by cterence** [comment]
Thanks for the suggestion, by searching this I just learned about [space scripts](https://silverbullet.md/Space%20Script).
I just made myself a simple one from the example:

```space-script
silverbullet.registerEventListener({name: "http:request:/health"}, (event) => {
  return {
    body: "ok"
  };
});
```

Now I have an unauthenticated `/_/health` endpoint that I was able to use for my probes, great stuff!

Closing this issue.
