### ISSUE TITLE
Question how to get the browser icon "Install App" in the url ?!

### ISSUE THREAD

**Issue by Oxyaxion** [silverbulletmd/silverbullet#1077]
Hello,

Testing silverbullet on my home server I run it like this

```/usr/local/bin/deno run -A --unstable-kv https://get.silverbullet.md --user mysuser:1234 /mnt/notes```

Instance is running behind a nginx configured in reverse proxy.

For now there is no https, it's just local testing.

I've noticed that I don't have the icon that opens the application in a dedicated Window. That's anoying cause I have tons of tab on my browser And would like to have the notes on a separate one ...

![html-icon](https://github.com/user-attachments/assets/f9fac89c-0f5c-43ee-a1d0-66fd01edc5b1)

On the other hand if I run the app locally on my laptop with http://127.0.0.1:3000/, I got the icon, even if there is no https connection.

Do I need to configure something to get this icon ?

**Comment by roceb** [comment]
You need HTTPS to be able to install it as a PWA. Surprise that it works
with localhost.

**Comment by zefhemel** [comment]
This is a browser security feature that I have no control over. PWAs are only enabled on localhost or 127.0.0.1 over http, and over any other URL via https.
