### ISSUE TITLE
Plug configuration in SETTINGS are ignored

### ISSUE THREAD

**Issue by tmichela** [silverbulletmd/silverbullet#1078]
I recently installed a fresh silverbullet and noticed that the generate configuration at `SETTINGS` changed from `yaml` to `space-config`.

It appears that settings for plugs (I tried the git and the treeview plugs) are ignored.  
If I change the type of the code block back to `yaml` all work fine again

**Comment by moreirapenna2** [comment]
+1 on this, just started using Silverbullet and a lot of stuff was not working, changing the `SETTINGS` codeblock from `space-config` to `yaml` solved it for me.

**Comment by zefhemel** [comment]
Please list the plugs this applies to. They need to be updated.

**Comment by moreirapenna2** [comment]
> Please list the plugs this applies to. They need to be updated.

For now, i had this with both [AI](https://github.com/justyns/silverbullet-ai) and [TreeView](https://github.com/joekrill/silverbullet-treeview).
I'm not sure if it has to do with any of this, but when i had my settings as `space-config`, i was getting an error on the "indexPage" parameter, saying `indexPage must match format "page-ref"`, and when i changed it to `page-ref` it said `indexPage must be string`, which was solved by changing to YAML.

**Comment by zefhemel** [comment]
@moreirapenna2 that's another issue, the error may not be clear but a page-ref means a string in the form `"[[some page]]"`. So if you put something like `"some page"` there, this is not an accepted value.

**Comment by zefhemel** [comment]
I just noticed the default generated SETTINGS used the wrong format, fixed that too. Releasing 0.9.4 now.
