### ISSUE TITLE
Can't delete pages

### ISSUE THREAD

**Issue by hanzei** [silverbulletmd/silverbullet#108]
Running `Page:delete` does not delete the page, neither on disk nor logically in SB. The file can still be accessed in SB.

This bug happens with both files in sub-directories and one in the root directory of the space.

The only interesting thing in the logs that I could find was that after the page gets "deleted" and a user navigates to it again, there is a timeout:
```
Loading file test.md
[Sandbox log] Meta data test {}
[Sandbox log] Timeout!
[Sandbox log] Meta data test {}
```

**Comment by zefhemel** [comment]
This is strange, are you running multiple instances of silverbullet by any chance? The logs you post are from the browser or server?

Something you can try: run `silverbullet fix <path-to-your-pages>` this will delete your data.db and _plugs folder, then run silverbullet again and see if it works. You'll have to run the Update Plugs command to reload all your plugs (one time).

**Comment by zefhemel** [comment]
Is this still happening since the `fix`?

**Comment by zefhemel** [comment]
Please reopen if it's still an issue
