### ISSUE TITLE
`undefined` document links on query result

### ISSUE THREAD

**Issue by mcanyucel** [silverbulletmd/silverbullet#1083]
I have the following template query to list notes with a specific tag:

```template
{{{csharp select name render [[Library/Core/Query/Page]]}}}
```
The result includes a note with the name `undefined` that points to nowhere:

![Screenshot 2024-09-16 132206](https://github.com/user-attachments/assets/2ce1ce18-e604-4385-859d-dff30c92b0c1)

This happens in some queries and not in all of them; I could not see an obvious pattern as well.

**Comment by zefhemel** [comment]
Do you have anything tagged with csharp that is not a page? An item? A paragraph? Likely you do. You can work around this by using `page where tags = "csharp"` instead.

**Comment by mcanyucel** [comment]
> Do you have anything tagged with csharp that is not a page? An item? A paragraph? Likely you do. And those objects don't have a `name` attribute. You can select only pages by using `page where tags = "csharp"` instead.

Well it looks like you nailed it. I did not know that you can tag paragraphs or items, and I have no idea how that is done, but apparently I have done it. 
Thanks!
