### ISSUE TITLE
Recommend memory-only or sync-only for slow drives

### ISSUE THREAD

**Issue by lutzky** [silverbulletmd/silverbullet#1092]
As discussed [on the forum](https://community.silverbullet.md/t/sync-slow-conflicted-files-showing-up/1020), it appears that a lot of flakiness can arise from servers with non-SSD hard drives using the default sqlite datastore (as it appears to have no caching).

I'm happy to draft a pull request with a better-wordsmithed version of my recommendations below, if it sounds good to you.

# Recommendations

Add a section "workarounds for slow disks", explaining that the default sqlite database is suitable for fast SSD drives, but will struggle with frequent access on slower, magnetic drives. Instead, the user can use either sync-only mode (linking to that section) or the memory database.

https://github.com/silverbulletmd/silverbullet/blob/4bc6ed719cda8cc61461d79092850d149ccc147d/website/Install/Configuration.md?plain=1#L73-L77

The above section can be changed to indicate that the in-memory database is useful for testing or for machines with slow disks, pointing at the new aforementioned "workarounds for slow disks" section. Add an explicit caveat that this will use more RAM and that, upon restart, users will be logged out if `SB_AUTH` is in use.

**Comment by zefhemel** [comment]
An alternative solution is to store the database elsewhere, even in a local temporary folder that is on faster storage. You can do this by setting the `SB_KV_DB` environment variable, e.g. `SB_KV_DB=/tmp/silverbullet.md`

**Comment by lutzky** [comment]
Yes, that is also a good recommendation. Would you like me to draft a PR?

**Comment by zefhemel** [comment]
I already wrote something up, see the linked commit. Open to improvements though.
