### ISSUE TITLE
ä-Umlaut shown as ‘

### ISSUE THREAD

**Issue by khooler** [silverbulletmd/silverbullet#111]
If you type the umlaut ä on a german keyboard it is shown as ‘ in the editor. All other umlaut (ö,ß,ü) are correct

**Comment by zefhemel** [comment]
Strange bug, but I think I fixed it, could you verify?

**Comment by j6b72** [comment]
The bug seems fixed on my side, I can insert "ä" again without any issues. Thank you!

**Comment by khooler** [comment]
Yes. Can confirm, it is working now. Thank you!
