### ISSUE TITLE
"silverbullet clean" command to remove directive results materialized in pages

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#114]
Right now, whenever you use a #query or #use or any other directive, it materializes its results and saves the current state to disk. For local use this is probably ok. The question is if you want this when you e.g. commit your stuff to git as well, or you would want to commit "clean" files without the materialized stuff.

For this we could introduce a `silverbullet clean` command that goes through all your pages, wipes out anything between `<!-- #directive -->` and `<!-- /directive -->` and saves it. You could then use this a pre-commit hook.

First discussed here: https://github.com/mattermost/mattermost-test-management/pull/4#issuecomment-1308964892 cc @m1lt0n 

We may also want to introduce an opposite command (not sure what it should be called, maybe `render`) which populates all directives in a batch mode, without having to "visit" each of the pages to have the directives be rendered.

**Comment by hanzei** [comment]
2/5 that I actually like the current behaviour as the default one because it allows reading the committed files with the directive content in, e.g. GitHub.

**Comment by zefhemel** [comment]
Definitely this would be optional. A big reason to "materialize" the queries to disk is to reduce lock in. You can view these files with any tool, even github, and get 100% of the content. This is as opposed to Obsidian where a lot of plug-in functionality depends on having Obsidian + specific plugins installed, like Dataview.
