### ISSUE TITLE
Support for Parameterized Buttons in Template Queries to Trigger Actions based on the Row

### ISSUE THREAD

**Issue by simone-viozzi** [silverbulletmd/silverbullet#1140]
Hi, my use case is:

Currently, SilverBullet does not have a robust attachment management system ( see #72 ).

To address this, I created a space script that allows querying for orphaned attachments:

```space-script
silverbullet.registerFunction({ name: "getOrphanAttachments" }, async () => {
  // List of folders to exclude
  const excludeFolders = ["_plugs", "silverbullet_utils"];

  // Get all attachments in the space, filtering out excluded folders
  const allAttachments = await space.listAttachments();
  const filteredAttachments = allAttachments.filter(attachment => {
    return !excludeFolders.some(folder => attachment.name.startsWith(`${folder}/`));
  });

  // Get all links in notes pointing to files
  const allLinks = await datastore.query({ type: "link" });

  // Filter links to include only those with the "link" tag and a non-empty `toFile`
  const linkedFiles = allLinks
    .filter(entry => entry.value.tag === "link" && entry.value.toFile && entry.value.toFile.trim() !== "")
    .map(entry => entry.value.toFile);

  // Find attachments that are not present in links
  const orphanAttachments = filteredAttachments.filter(attachment => {
    return !linkedFiles.includes(attachment.name);
  });

  return orphanAttachments;
});
```

Now I would like to create a query from this list where each row of the query has a delete button.

Something like:

```template
{{#each getOrphanAttachments()}}
- [[{{ref}}]] - [Delete](deleteFile "{{name}}")
{{/each}}
```

or

```template
{{#each getOrphanAttachments()}}
- [[{{ref}}]] - {[deleteFile "{{name}}"]}
{{/each}}
```

something like this:

![image](https://github.com/user-attachments/assets/cede0d72-943a-4498-9d06-2a154e389630)

### Request:

What type of space script do I need to implement so that clicking the button/link would trigger the `space.deleteAttachment(fileName)` syscall?

### Side Issue:

When clicking on the link of the file reference in a query result, I get an error: `Page name cannot end with a file extension`. However, when the result of the query is embedded, clicking the file reference opens the file in a new tab, as expected.

Thank you

**Comment by simone-viozzi** [comment]
```space-script
silverbullet.registerCommand({ name: "Delete It" }, async (name) => {
  if (name) {
    try {
      // Add ./ in front of the name
      name = `./${name}`;
      
      // Delete the file
      await syscall("space.deleteFile", name);
      await syscall("editor.flashNotification", `File Name ${name} Deleted!`);
      await syscall("codeWidget.refreshAll");
    
    } catch (error) {
      await syscall("editor.flashNotification", `An error occurred: ${error.message}`);
    }
  } else {
    await syscall("editor.flashNotification", "No file name provided!");
  }
});
```

````
```template
{{#each getOrphanAttachments()}}
- [[{{ref}}]] - {[Delete It]("{{ref}}")}
{{/each}}
```
````

Done it!!


this will render like:

![image](https://github.com/user-attachments/assets/f05461a2-2eec-44f2-a096-8e11a0b3c72e)

if you add a ! in the query (like `![[{{ref}}]]`) it will also render each attachment, so you can see them right away.

Thank you @wunter8!

**Comment by crosbyh** [comment]
I am trying to set this up and for some reason the template returns "Error: space.listAttachments is not a function"

Has anyone encountered this?

**Comment by crosbyh** [comment]
> I am trying to set this up and for some reason the template returns "Error: space.listAttachments is not a function"
> 
> Has anyone encountered this?

Figured it out, seems that call was renamed to space.listDocuments(). Changing the one instance in the space-script above makes it work again!
