### ISSUE TITLE
Naked URL links shouldn't include final period/full-stop

### ISSUE THREAD

**Issue by lutzky** [silverbulletmd/silverbullet#1160]
Input:

    I like https://silverbullet.md/SilverBullet. It's great.

Desired output - period outside link

    I like <a href="I like https://silverbullet.md/SilverBullet">https://silverbullet.md/SilverBullet</a>. It's great.

Actual output - period inside link.

    I like <a href="https://silverbullet.md/SilverBullet.">https://silverbullet.md/SilverBullet.</a> It's great.

This occurs both in the live editor and in markdown preview. Notably, that's a [broken link](https://silverbullet.md/SilverBullet.).

Github gets this right:

> I like https://silverbullet.md/SilverBullet. It's great.

So does https://markdownlivepreview.com/ and https://dillinger.io/. SilverBullet actually gets this right for commas, but not for periods.

**Comment by lutzky** [comment]
Issue is likely here:

https://github.com/silverbulletmd/silverbullet/blob/51fc5952bcc4e36533fc7f5523bd09e043f3ffc6/common/markdown_parser/parser.ts#L576-L585

**Comment by lutzky** [comment]
Workaround: Use the proper commonmark style, `<https://silverbullet.md/SilverBullet>.` does the right think (in github too. Notably, commonmark specifies that "truly naked" URLs (without `<>`) [don't count as links](https://spec.commonmark.org/0.31.2/#autolinks).

**Comment by stapelberg** [comment]
> SilverBullet actually gets this right for commas

No, I don’t think it does, actually: URLs are cut off at comma or semicolon characters, for example the following URL does not work in SilverBullet:

https://cs.opensource.google/go/go/+/master:src/archive/zip/reader.go;l=25;drc=9cfe3a86d34f7f4a401dae9a22389b12f7e8bb2e

Renders as:

<img width="808" alt="Screenshot 2024-11-20 at 23 20 55" src="https://github.com/user-attachments/assets/ce602790-73da-46c6-9d6d-49512771b0fe">

There might of course be more trigger characters I have not yet encountered in my usage :) We should probably locate the relevant RFC.

One heuristic I thought about is for SilverBullet to recognize period/comma **followed by whitespace** as not part of the URL. Though of course that breaks URLs which require a trailing comma. I am not sure how common these are, but the safest solution of course is to not use any heuristic and require users to be explicit when the behavior isn’t what they expect.

**Comment by lutzky** [comment]
(Yo @stapelberg! Fancy meeting you on a bugreport)

You're right, the same issue occurs for commas (e.g. http://example.com/?p=1,2 will end at 1 instead of 2)

This is probably why commonmark mandates <URLs>, and heuristics don't need to be perfect; for example <https://example.com/b=),> is a perfectly cromulent URL, but it seems quite sane to me parse that as https://example.com/b=), and call it a day.

However, I think there's an argument to be made for matching other (non-commonmark) markdown engines' behavior here - it breaks user expectations (specifically period after trivial URL), and doesn't reward sites that try to make "markdown-compatible" URLs (I can't immediately think of an example with a comma, but you did provide one with a semicolon).

**Comment by stapelberg** [comment]
(Hey! 👋)

 OK. I sent PR #1162 to scratch my own itch. Feel free to send a separate one for commonmark unification (IIUC) :)

**Comment by lutzky** [comment]
> @stapelberg @zefhemel For [RFC3987](https://datatracker.ietf.org/doc/html/rfc3987) [this JS regex](https://regex101.com/library/vF2bZ4) looks good to me. I also think it should be used within `<` and `>` too (works out of the box). It matches even IPv6 and UTF-8 etc. addresses correctly (try e.g., `https://[ffff::]:12345/My%20♥%20is%20Linux/`). 👍

Unfortunately this *does* seem to include a full-stop:

![image](https://github.com/user-attachments/assets/a6e8875f-6b79-4641-8a8a-14d6581fc950)

**Comment by p-weston** [comment]
Would something like this work? It should include any of ```.,:;)``` as part of the URL unless they are at the end (followed by whitespace or end of a line):
```^https?:\/\/[-a-zA-Z0-9@:%._\+~#=]{1,256}(([-a-zA-Z0-9(@:%_\+~#?&=\/]|(?:[.,:;)](?!(\s|$))))*)```

(standard "I trust regexes about as much as I can pronounce them" disclaimer applies...)

**Comment by lutzky** [comment]
Nearly! I've added some unit tests here: https://regex101.com/r/T90clU/1 (please select "Function->Unit Tests" on the left, I can't seem to link directly to that)

**Comment by lutzky** [comment]
Domain names ending in a dot don't work naked in other markdown implementations, and <http://domainwithdot.com.> should do the right thing in that case.

**Comment by lutzky** [comment]
@mjf  Sure, but that's a separate bug to this one IMO. Let's keep this one focused on "if autolinkifyNakedLinks is enabled, then autolinkify without the final period".
