### ISSUE TITLE
Hide (long) URLs/live preview

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#118]
When using long links, eg `[link](https://hdjdjdid.did.com/whatever)` this takes a lot of screen space and is a bit ugly. It may be possible to hide or shorten (with ellipsis) the URL when not editing it (when the cursor is outside). 

Obsidian does something like this, but for all markup (live preview) and I'm not a huge fan of the resulting jumping around of text that happens when you move your cursor through a document. 

Opinions welcome.

**Comment by bbroeksema** [comment]
Is this kind of a one-off Or are there any other elements that could lead to a similar sort of argumentation? E.g. lists do not fit into this for me, as I can't be bothered seeing dashes or some fancy bullet. The issue I have with a link is really the screen estate they take, which makes an exception plausible for me.

The usage SB is advocating is working in the editing mode non-stop,.  This is fine, as long as that doesn't result in screen estate being taken away necessarily. And finally, given the design, this could be in a plug, right? I.e. enabling it would in that case be optional.

**Comment by zefhemel** [comment]
There's an implementation we can reuse here: https://codeberg.org/retronav/ixora/src/branch/main/src/plugins

**Comment by Willyfrog** [comment]
From a product perspective: are we ok to have the text jump whenever the caret is in the link?

Also, if we are going to use an ellipsis, let's make sure that we at least have the host section showing.

**Comment by zefhemel** [comment]
This is happening, and will go way beyond links most likely.

**Comment by zefhemel** [comment]
Live preview is now in `default`.
