### ISSUE TITLE
Beware! Data Breach on Silverbullet ⚠️⚠️⚠️

### ISSUE THREAD

**Issue by MohitDeshwal** [silverbulletmd/silverbullet#1193]
Found this today on my Google dark web results: 
![CleanShot X 2024-12-25 09 03 01](https://github.com/user-attachments/assets/514add19-72e3-46fa-9666-b2a85e128c96)

I think it's time to use a proper auth proxy.

**Comment by zefhemel** [comment]
Different SilverBullet
