### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#123]
Diagramming langdurig that can easily be embedded in triple backticks. GitHub supports this for instance. In SB this could have live preview. 

https://mermaid-js.github.io/mermaid/#/

**Comment by zephraph** [comment]
Should this be core? Seems like it could just be another plug.

**Comment by zefhemel** [comment]
Right now you do not have direct access to the DOM (except in iframes) from plugs. Hence this would need to be implemented in core for now.

**Comment by zephraph** [comment]
Hmmm... I think you'd likely want to define it in a code fence and display it inline inside an iframe. Probably would want syscall support for that pattern.

**Comment by zefhemel** [comment]
I'm starting to think that too. Would have to investigate if that's viable from a performance perspective.

**Comment by zefhemel** [comment]
Boom: https://github.com/silverbulletmd/silverbullet-mermaid
