### ISSUE TITLE
Installation on windows failed

### ISSUE THREAD

**Issue by fairplay** [silverbulletmd/silverbullet#128]
After `deno` is installed in windows in powershell and working I can't install silverbullet

```
> deno install -f --name silverbullet -A --unstable https://get.silverbullet.md
error: The module's source code could not be parsed: Expected ';', '}' or <eof> at https://get.silverbullet.md/:1:11
```

**Comment by fairplay** [comment]
The same problem is in WSL, but I successfully set up silverbullet on Ubuntu several hours earlier. M.b. temporary problem with the host?

**Comment by zefhemel** [comment]
I'm such an amateur, I broke get.silverbullet.md. Should be fixed now, can you check?

**Comment by fairplay** [comment]
The problem is the same, seems like three comment lines in the head
```
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually
```
breaks the installation.

**Comment by fairplay** [comment]
Disregard last message, it's just the cache. Everything seems fine, thanks!
