### ISSUE TITLE
Outlining commands

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#13]
Currently when you hit `Tab` inside of a bullet list item, it will indent it, `Shift-Tab` will outdent it. This is standard CodeMirror Markdown functionality. It would be cool to also add “move item down” and “move item up” commands, e.g. bound to `Alt-Up` and `Alt-Down`. This should move entire sub-trees with it.

Example of “move item down”:

```
* This is item 1 (CURSOR HERE)
    * This is a sub-item
* This is item 2
```

Turns into:

```
* This is item 2
* This is item 1 (CURSOR HERE)
    * This is a sub-item
```

As “better versions” of Tab, `Alt-right` and `Alt-down` could do indent and outdent with subtrees as well.

When used inside numbered lists, items should be renumbered as items are moved around.

**Comment by adamshand** [comment]
Another common keyboard shortcut that I use all the time is shift-enter to insert a line break within the current bullet.
