### ISSUE TITLE
Does not run on raspberry 

### ISSUE THREAD

**Issue by ulrischa** [silverbulletmd/silverbullet#136]
Because deno dies not run on raspberry pi silverbullet does not run too. Would like to use it on a raspberry pi. 
Please give another Option to install

**Comment by zephraph** [comment]
I think your best shot is following along with this issue. https://github.com/denoland/deno/issues/2295. It sounds like you probably _could_ self compile deno and then run sb, but your milage may vary. This isn't an installation issue. You'd have to rewrite the tool to not depend on deno.

**Comment by ulrischa** [comment]
For me a show Stopper for raspberry.

**Comment by zefhemel** [comment]
If you run a 64 bit OS on a recent RPI this should work: https://github.com/LukeChannings/deno-arm64/releases

**Comment by zefhemel** [comment]
Let me put this on my roadmap list. I have some Pis lying around, would be nice to use them for SB. Maybe I can provide an arm 64 docker image too.

**Comment by zefhemel** [comment]
Maybe we can easily switch to this base image to get support for both intel and arm: https://hub.docker.com/r/lukechannings/deno

A shame it's based on Ubuntu.

**Comment by ulrischa** [comment]
Oh cool. Could you tell me more Details if it works?

**Comment by zefhemel** [comment]
Ok, so this works flawlessly once you setup Deno. Instructions:

Tested on Ubuntu server 64-bit on a Pi, but should work the same for any 64 (!! 32-bit won't work) Linux distribution on a RPI:

```shell
$ apt install unzip
$ cd ~
$ wget https://github.com/LukeChannings/deno-arm64/releases/download/v1.29.1/deno-linux-arm64.zip
$ mkdir -p ~/.deno/bin
$ cd ~/.deno/bin
$ unzip ~/deno-linux-arm64.zip
```

Add `~/.deno/bin` to PATH, e.g. in `~/.bashrc` add:

```
export PATH=$PATH:~/.deno/bin
```

Then to verify:

```shell
$ source ~/.bashrc
$ deno -V
```

Then, just follow standard SB install instructions:

```shell
$ deno install -f --name silverbullet -A --unstable https://get.silverbullet.md
$ mkdir ~/Notes
$ silverbullet ~/Notes --hostname 0.0.0.0
```
And access it on `http://ip-of-pi:3000`

**Comment by zefhemel** [comment]
Properly documented here: https://silverbullet.md/Raspberry_Pi_Installation

**Comment by ulrischa** [comment]
Thank you for that christmas present :)
I will try ot out next days

**Comment by sweisgerber** [comment]
Added PR to fix this issue in https://github.com/silverbulletmd/silverbullet/pull/400
