### ISSUE TITLE
Support for rendering LaTeX

### ISSUE THREAD

**Issue by AlexMV12** [silverbulletmd/silverbullet#137]
Hello,

First of all, congratulation on this project. It is extremely clean, fast, and without useless stuff.
While the panorama of knowledge management applications is crowded, I think that your solution can be perfect for a lot of users.

I'd like to suggest a feature (similar to the one present in Obsidian and in many other similar apps) to support the rendering of LaTeX text - usually put inside `$$`, like: `$$ \frac{42}{e^{1-x}} $$`.

I am not an expert in the JS development field, but I think that this solution may be implemented using [MathJax](https://github.com/mathjax/MathJax) - maybe as a plugin.

I'll leave it here as a suggestion, thanks again!

**Comment by yorrd** [comment]
also leaving [katex](https://github.com/KaTeX/KaTeX) here as a fast alternative to mathjax

**Comment by zefhemel** [comment]
Here you go: https://github.com/silverbulletmd/silverbullet-katex
