### ISSUE TITLE
Attachments not loading when using --password

### ISSUE THREAD

**Issue by brtwrst** [silverbulletmd/silverbullet#139]
* When I run silverbullet with `--password`, attachments (tested with images) don't load any more.
* The Chrome Devtools/Network show that when the picture is requested - a 401 Unauthorized is returned (only for the /fs/<name>.png request).
* Uploading a Picture via drag and drop or pasting **works fine** even with `--password` set
* When I remove `--password` everything works fine again, adding it breaks it again.

I run silverbullet in Docker with the following Dockerfile
```Dockerfile
FROM denoland/deno:alpine

RUN apk add tini
RUN deno install -f --name silverbullet -A --unstable https://get.silverbullet.md

RUN mkdir /space
WORKDIR /space

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "-g", "--"]
CMD ["silverbullet", "/space"]
```
* I have tried it with the above Dockerfile with deno:alpine and deno:latest as a base image
* I have tried it with the Dockerfile and docker compose from the repo (which seems to be an older version or something) and the same thing happened there - in addition to the whole "live edit" thing not working any more
* I have tried it through a nginx reverse proxy and by directly connecting to the port 3000 of the machine. Same thing happened there.

* Browser is Brave Version 1.46.133 Chromium: 108.0.5359.71
* Host: Ubuntu 22.04 - Docker 20.10.21

**Comment by zefhemel** [comment]
Fixed by switching to basic auth (use the `--user` flag now). If this doesn't fix it for you (works for me) please reopen.

**Comment by brtwrst** [comment]
Password authentication works.
Looking forward to some more "permanent" way to log in so I don#t have to reauthenticate every so often.

Concerning the attachments I am seeing a different kind of (weird) behaviour now.
I have pulled the latest changes a few minutes ago.
1. When I go to any page, I can not see any pictures/attachments at first.
![image](https://user-images.githubusercontent.com/6873862/205688990-36255d7e-3940-4c4e-bd38-d04ab997d28d.png)

2. I have to find one of the invisible pictures and put the cursor on the line to make the text visible
![image](https://user-images.githubusercontent.com/6873862/205689060-027e4127-0135-46f5-9748-5eb8cc452284.png)

3. If I just move the cursor away nothing will change but if I change/update anything about the link -> all pictures in the document will appear.
![image](https://user-images.githubusercontent.com/6873862/205689538-1af90485-b180-41d3-ab22-bf9763bb4bd7.png)

As soon as I press F5 or otherwise reload the page - all pictures are invisible again

This happens with `--user` and without so it seems to be unrelated to that.
From the Devtools I can see that the pictures are not even downloaded until step 3 described above is executed

**Comment by zefhemel** [comment]
I've seen this too, it's not just for attachment. It may be a codemirror bug... could you report this as a separate issue?
