### ISSUE TITLE
More helper functions for Handlebar

### ISSUE THREAD

**Issue by ankitrgadiya** [silverbulletmd/silverbullet#141]
The query directive, along with Rendering templates is very powerful as it is. But, I think it would be even more useful if more helper functions are present in the Handlebar.

* [ ] Equality Comparision 
      I want to add some Text based on the status of the Page. But Handlebar seems to not have 
      equality operators.
      `[[#if status == "Complete"]][[/if]]`
* [ ] Date Formatting.
      Currently, if I add the Date field to the Front-matter, it gets converted into a Timestamp. This is returned when quering. But, I'd like to have pretty dates like "17th August, 2022". SQLite exposes `strftime()` but the modifiers there are quiet limited.

**Comment by zefhemel** [comment]
If anybody wants to look at implementing this, this is where the current helpers are defined: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/directive/util.ts

**Comment by zefhemel** [comment]
No longer relevant since template engine switch
