### ISSUE TITLE
Inline Directive

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet#145]
As a user, I would like to prevent the directive from generating line breaks so that I can use them as inline-logic. For example, I would like to do

![image](https://user-images.githubusercontent.com/1191486/205496624-4a44796e-b4d4-4d1b-97b9-1481471cdeae.png)

but with current behavior that expression breaks up into 

![image](https://user-images.githubusercontent.com/1191486/205496643-65813f58-258c-497f-9704-c2197dbc7eb3.png)

upon re-evaluating.

**Comment by zefhemel** [comment]
This is one option, but my struggle is that this notation is just very long as it is.

I’m considering adding a shorter notation for inline use, something along the lines of `$[helloworld.getDailyNote()](WHATEVER THIS EVALS TO)`, which would live preview to just `WHATEVER THIS EVALS TO.` Thoughts?

**Comment by yorrd** [comment]
Understood. In the Obisidan world, many plugin autors allow code snippets between backticks to be parsed and evaluted. For example
```
`2+4=?`
```
is evaluated by the mathpad plugin in Obsidian to be rendered as latex. 

Also, there is the `![[...]]` syntax for embedding (similar to `/include`). 

---

Your proposed syntax seems interesting. I like how it keeps the prompt but also puts the result in the markdown. Obsidian "good practice" is to render virtually, which I don't agree with. I like the proposal.

**Comment by zefhemel** [comment]
Relevant discussion topic: https://github.com/silverbulletmd/silverbullet/discussions/183#discussioncomment-4370524
