### ISSUE TITLE
Add vim support

### ISSUE THREAD

**Issue by ryanwwest** [silverbulletmd/silverbullet#149]
I'd love to use this tool being self-hosted and WYSIWYG and like Obsidian, but it doesn't yet have vim keybinding support. I see that it uses Codemirror, and I believe Obsidian supports its vim keybindings through a Codemirror repo and they don't maintain it directly (there is a large discussion here that I haven't looked at much: https://forum.obsidian.md/t/vim-support-for-the-new-editor-codemirror-6-neovim-libvim-or-something-else/21803/31).

I'd love it if Silverbullet could take advantage of an existing vim keybindings repo like this to support vim (and hopefully .vimrc files, too) in the editor. I know that Obsidian doesn't keep vim in its own plugin because it is too integrated with the core editor - not sure if a Plug would work for this or not either.

**Comment by zefhemel** [comment]
Yeah, it looks like there’s this plugin for CM6, which should work and will likely not be that hard to integrate: https://github.com/replit/codemirror-vim 

This will not possible to integrate using a plug, but we can consider merging into SB proper. Even though I’m a recovering vim user myself, I’ll likely not be using it. Therefore I’m happy to take it as a contribution, but will need support to keep maintaining it down the line. Would you be up for that?

**Comment by zefhemel** [comment]
Hadn't planned to work on this but found a few minutes and it seemed easy. Seems to work quite alright so far, PR here: #197 will merge it later

**Comment by zefhemel** [comment]
Ok merged.

You can enable it by setting `vimMode: true` in your `SETTINGS` page and reloading the page. Likely there will be issues, please create new issues for them.

**Comment by jamesob** [comment]
Wow, thanks @zefhemel! I'll give this a shot today.

**Comment by zefhemel** [comment]
Update: vim mode is now toggled per client via the `Editor: Toggle Vim Mode` command (not using `SETTINGS` anymore).

**Comment by jamesob** [comment]
This works great! Thanks.
