### ISSUE TITLE
Update docker to Deno setup

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#150]
Currently still using the old npx deployment.

**Comment by brtwrst** [comment]
I have 2 working versions based on the old one
A few things to note:
* the deno user has different IDs in the alpine and default (debian) image of deno (users might have to change the permissions of their /space folder)
* The folder /deno-dir/deps is not writable for the deno user in either images and has to be chown'd or the root user has to be used.
* I like to add [tini](https://github.com/krallin/tini) to containers so that shutting them down does not take several seconds

Dockerfile.debian
```Dockerfile
FROM denoland/deno:debian

RUN apt-get update; apt-get install tini
RUN deno install -f --name silverbullet -A --unstable https://get.silverbullet.md

RUN mkdir /space
WORKDIR /space
RUN chown deno:deno /space

# /deno-dir/deps needs write permissions for deno user or sb will not run
RUN chown deno:deno /deno-dir/deps

# deno user id is 1993 in debian image
USER deno

EXPOSE 3000

ENTRYPOINT ["/usr/bin/tini", "-g", "--"]
CMD ["silverbullet", "/space"]
```

Dockerfile.alpine
```Dockerfile
FROM denoland/deno:alpine

RUN apk add tini
RUN deno install -f --name silverbullet -A --unstable https://get.silverbullet.md

RUN mkdir /space
WORKDIR /space
RUN chown deno:deno /space

# /deno-dir/deps needs write permissions for deno user or sb will not run
RUN chown deno:deno /deno-dir/deps

# deno user id is 1000 in alpine image
USER deno

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "-g", "--"]
CMD ["silverbullet", "/space"]
```

**Comment by MaverickDe** [comment]
Hi, Can I get assigned to this issue?

**Comment by MaverickDe** [comment]
Please can you explain in depth what is to be achieved in this issue

**Comment by zefhemel** [comment]
What we would like to have (from my perspective) is an updated `Dockerfile` (likely based on recent Deno-based, minimal) image, downloads the most recent version of SB into the image, allows volume mounting of the space folder into the image, and runs SB on boot. 

I think @brtwrst 's second solution (Alpine) is what I was expecting.

**Comment by brtwrst** [comment]
Yes the second one does that and it's the one I'm using currently. Also has the upside of keeping the user ID the same compared to the previous (non deno based) image. 
If the docker-compose.yml gets updated with `restart: unless-stopped` or `restart: always` then "auto boot" would also be covered.

**Comment by BaptisteBdn** [comment]
@brtwrst the Alpine Dockerfile looks great. Quick question, how do you handle upgrading Silverbullet ? We could exec a command inside the docker container to run `silverbullet upgrade` and restart SB but that may not be the best practice for a docker container.

**Comment by brtwrst** [comment]
`docker-compose build --no-cache` in the folder where the `docker-compose.yml` file is located

**Comment by brtwrst** [comment]
that said, I have no idea what the `deno install -f --name silverbullet -A --unstable https://get.silverbullet.md` does and if it is the best solution to installing it or if pulling the source from github and working with that is more efficient.
Is the `https://get.silverbullet.md` kept up to date with the github repo automatically?
This will download 16MB from wherever this is hosted **per image build**. Is that going to be a problem?

A case could be made for setting up a CI/CD pipeline / github actions that builds the image and uploads it on dockerhub.
As far as I know you can do that for free if you're an open source project.

Things to ponder about....

**Comment by zefhemel** [comment]
Right now the bundle coming from get.silverbullet.md is updated on every commit to the main branch.

**Comment by zefhemel** [comment]
First step is to get the Dockerfile in. Could somebody create a PR for this? After that I'll look into creating a GitHub action that builds a docker container and pushes it.

**Comment by BaptisteBdn** [comment]
I can submit a PR for the Dockerfile.
If get.silverbullet.md gets updated at every commit we could have the Dockerfile use that, like @brtwrst used in his example.
The Github action should then occur after the get.silverbullet.md gets updated.

Or we can redo the build with deno inside the Dockerfile to replace the install from `https://get.silverbullet.md`, if so could you point out how this build is being done ?

**Comment by zefhemel** [comment]
Right, the problem is that there is a separate Netlify build step (though a webhook) that builds the website and updates get.silverbullet.md and I'm not sure how to let a GitHub action wait for that. Alternative is indeed to run the "deno task bundle" as part of the docker build... maybe I just have to take this and noodle with it for a bit. Will look tomorrow hopefully.

**Comment by zefhemel** [comment]
Feel free to create a PR for the Docker file as is, btw, I can adapt to work with CI later.

**Comment by BaptisteBdn** [comment]
I have been working with deno to understand a bit more how it is working.
I think the following Dockerfile should be enough and it should be easy to include it in CI.

```
FROM denoland/deno:alpine

# build silverbullet using deno in /app
COPY . /app 
WORKDIR /app
RUN deno task build
RUN deno task install

RUN mkdir /storage
WORKDIR /storage
RUN chown deno:deno /storage

# /deno-dir/deps needs write permissions for deno user or sb will not run
RUN chown deno:deno /deno-dir/deps

# deno user id is 1000 in alpine image
USER deno

EXPOSE 3000

CMD ["silverbullet", "/storage"]
```

I have removed tini because it is enabled by default in newer version of docker.
I will submit a PR when I have a bit more time.

**Comment by zefhemel** [comment]
Ok thanks all for your input, I think I'll need to take it and push over the finish line, because I also need to do the integration with CI in the end. I'll create this a PR for your review later.

**Comment by zefhemel** [comment]
Here's the PR. Please have a look, there's no CI part yet (will do that later). But the docker image is already pushed.

https://github.com/silverbulletmd/silverbullet/pull/174
