### ISSUE TITLE
Suggest already linked but not yet created files

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet#154]
As a user, sometimes I make links that I forget or choose not to fill immediately. When I come back to that topic later on, I'd like to be reminded that I already have a link with a similar name. This can be achieved by suggesting not-yet-existing but already linked files in the switcher dialog, together with already existing files.

**Comment by zefhemel** [comment]
Yep, and I'm pretty sure we will already have indexed all those non-existing pages: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/core/page.ts#L26

So it's a matter of adding these to the page completion results in a good way: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/core/page.ts#L217

**Comment by genotrance** [comment]
This is a crucial feature - I'm moving from LogSeq and all those links that got auto-suggested don't anymore with SB. I'm having to fill in dummy info to workaround this but that doesn't scale for the several hundred I have.

**Comment by zefhemel** [comment]
Yes, I've started working on this. I'll look at ways to add non-existing, but linked pages to both the page picker and page auto complete.
