### ISSUE TITLE
Public Read Only Mode Suggestion 

### ISSUE THREAD

**Issue by lazarskik** [silverbulletmd/silverbullet#161]
Hello,

Just installed SB yesterday and am very impressed with the speed and simplicity of this software. I'm a big proponent of the portability of markdown. There's one thing that I think would make this a great solution for anyone trying to host this on the Public Internet. That's the ability to restrict others from making edits. This is similar to the way that the main https://silverbullet.md works. Any changes made to the page are not permanent. 

I see there's an option in the command menu to toggle "Editor: Toggle Read Only Mode" but anyone can turn that on and off.
Can we make a setting that enables Public Read Only mode? It would make sense to integrate it with some sort of authentication.

Thank you.

**Comment by zefhemel** [comment]
Discussion on how to “hack” this: https://discord.com/channels/1028543811191836782/1081646254993461379

**Comment by qaqland** [comment]
🤯 Users without discord cannot access

> Discussion on how to “hack” this: https://discord.com/channels/1028543811191836782/1081646254993461379

**Comment by tarpdalton** [comment]
> 🤯 Users without discord cannot access
> 
> > Discussion on how to “hack” this: https://discord.com/channels/1028543811191836782/1081646254993461379

discord invite link: https://discord.gg/EvXbFucTxn

**Comment by zefhemel** [comment]
I may add this as a feature of https://github.com/silverbulletmd/silverbullet-pub so in addition to publish some or all pages as markdown and clean HTML, I may also add an option to just wrap the SB UI around it as well.
