### ISSUE TITLE
Relative date support

### ISSUE THREAD

**Issue by handcraftedbits** [silverbulletmd/silverbullet#162]
Looking at the query grammar, it seems there's no way to specify relative dates, is that correct?  That prevents useful queries like "all incomplete tasks due by next week" or similar.  I was thinking about tackling this, but unsure of what a good syntax would be.  I was thinking that dates could be specified via a `date` prefix, e.g., `date:YYYY-MM-DD` for an absolute date or `date:today`, `date:tomorrow`, `date:+30day`, `date:-2week` for relative dates.  Does that seem reasonable?

Also, I noticed that the query grammar only supports logical `and`, no nesting, etc.  Is that something on the roadmap?  If not, I can try to take a stab at that.

**Comment by zefhemel** [comment]
See https://github.com/silverbulletmd/silverbullet/discussions/147

**Comment by zefhemel** [comment]
All this can now be implemented with space script https://silverbullet.md/Space%20Script
