### ISSUE TITLE
Add a strikethrough shortcut

### ISSUE THREAD

**Issue by milk9111** [silverbulletmd/silverbullet#180]
Strikethrough already works if you wrap the text in tildes, but would be nice to have a shortcut to do this like you can with **bold** and _italics_.

**Comment by zefhemel** [comment]
Super easy to do, what should the shortcut be?

**Comment by zefhemel** [comment]
Like this: https://github.com/silverbulletmd/silverbullet/blob/850077bad0619d5d321bbcd4ca7589e1d51c5a22/plugs/core/core.plug.yaml#L295
