### ISSUE TITLE
Release tags as Github releases + properly tagged docker images

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#198]
Right now we're in streaming release mode, every merge to `main` results in a new release, both to `get.silverbullet.md` and the `zefhemel/silverbullet:latest` docker image. Likely this will have to change.

When tagging a release:
* We can release the bundled `silverbullet.js` as a proper github release (this is 100% self contained and can be run locally)
* We can push a docker image with a proper version number

**Comment by sweisgerber** [comment]
Hi there,

there are surely dozens of work-flows out there, one of the better known is `git-flow`.
- https://jeffkreeftmeijer.com/git-flow/, which has been put into a nice git plugin:
- https://github.com/nvie/gitflow, that get's explained in a blog-post:
- https://nvie.com/posts/a-successful-git-branching-model/

That would surely help with doing proper releases and their tagging, IMHO.

The main aspect is, that one does only work on branches, which will get merged to `develop`.

Every release is then created by merging & tagging `develop->main` through release-branches.
One does never push to main or develop, only to branches (perhaps you push to develop as well if you are the only dev, although it's not allowed when applying yhe work-flow strict).
This leads not only to `main` being always ready to run, but to `develop` as well.
When using the linked git plugin the git-flow is pretty easy.

O.c. there are plenty of alternatives like [github-flow](https://githubflow.github.io/) and [more](https://www.jetbrains.com/help/space/space-git-flow.html).

**Comment by sweisgerber** [comment]
Anyway, what I actually wanted to post :D :

I'm currently working on github action workflow that uses tags as proper release numbers.
It also adds these new features
- uses buildx to build arm64 & amd64 (#136)
- pushes builds to dockerhub & the github container registry as well.
- tags with `latest`, `nightly` & `releases`

https://github.com/sweisgerber/silverbullet/pull/1

If you want, I can redirect the PR to your repository as well while I test the semantics on my fork.
Final tests have to get done by you anyway, as it needs tags and you have to configure github container registry (ghcr) access.
