### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Pinjasaur** [silverbulletmd/silverbullet#2]
A dark theme would be a great addition to the default (light) theme. Many ways to support it ([my go-to resource](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)) but in general use the `prefers-color-scheme` set at the OS/browser level or do more custom persistence via `localStorage`, cookies, or maybe the SQLite store.

**Comment by zefhemel** [comment]
Thanks for this. Definitely, this is something I’d want to have as well. For pragmatic reasons (it’s tricky enough getting a reasonably styled CSS done, let alone maintaining two) I haven’t gotten to it yet. The question is if this shouldn’t go together with a general theming system. I know this is a thing people would want: to simply theme every bit of this, which of course is perfectly possible. [CodeMirror has built-in theming support](https://codemirror.net/examples/styling/) which I’m not very much leveraging right now, but that’s something to evaluate here too.

**Comment by Pinjasaur** [comment]
Yeah, that's an interesting point: maybe SB could load a custom local stylesheet if it exists locally? e.g. `./silverbullet.css` or similar. IMHO maintaining themes becomes complicated, but maybe that's a non-issue if you're leveraging what CodeMirror has builtin.

**Comment by Pinjasaur** [comment]
Played around with SB locally and tweaked some styling against a `prefers-color-scheme: dark` `@media` query. Very much a WIP but shows the potential. I did this on my personal blog somewhat recently: https://github.com/Pinjasaur/blot-theme-jot/pull/7

### Screenshots

Before: 

![image](https://user-images.githubusercontent.com/6335792/184437690-c39a3d0d-0d34-4c7d-bbd4-548a3ac9d207.png)

![image](https://user-images.githubusercontent.com/6335792/184438552-e9e7e23d-6439-4c19-9fee-0d7ee4058a23.png)

After:

![image](https://user-images.githubusercontent.com/6335792/184437873-9aa1c5ea-1d74-40a1-97bd-fa6f5c547526.png)

![image](https://user-images.githubusercontent.com/6335792/184438459-0e83f509-dce7-40ac-8e56-68ffa82d585b.png)

### Patch

```patch
diff --git a/packages/web/styles/theme.css b/packages/web/styles/theme.css
index 972dd12..d8dd487 100644
--- a/packages/web/styles/theme.css
+++ b/packages/web/styles/theme.css
@@ -270,3 +270,30 @@
   font-size: 75%;
   line-height: 75%;
 }
+
+@media (prefers-color-scheme: dark) {
+  #sb-root {
+    background-color: #555;
+    color: rgb(200, 200, 200);
+  }
+
+  #sb-top {
+    background-color: rgb(38, 38, 38);
+    border-bottom: rgb(62, 62, 62) 1px solid;
+    color: rgb(200, 200, 200);
+  }
+
+  .sb-saved {
+    color: rgb(225, 225, 225);
+  }
+
+  .sb-filter-box {
+    color: #ccc;
+    background-color: rgb(38, 38, 38);
+  }
+
+  .sb-code,
+  .sb-line-fenced-code {
+    background-color: #333;
+  }
+}
```

**Comment by zefhemel** [comment]
I like this a lot. I'm thinking how to best incorporate this. Perhaps make it part of the existing theme.css, but only enabled with a .dark class on the root element or something?

**Comment by Pinjasaur** [comment]
IMHO I don't see any major issues leaving it behind the `prefers-color-scheme: dark` since that's changeable at the OS & browser level. If you wanted more of a "feature flag" then a .e.g `.dark` class or `data-theme` attribute on the root element could work—I'm just not sure offhand how that sort of value would be toggled on/off.

**Comment by zefhemel** [comment]
Ah sorry, didn't see that. Yeah that works.
