### ISSUE TITLE
Vim mode stuck in INSERT mode

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#200]
Happened to me many times, not sure what triggered it yet. All of a sudden vim mode seems stuck in INSERT mode (Esc key does nothing).

**Comment by zefhemel** [comment]
To debug this, likely we'll have to add some debugging statements for various vim events (documented here: https://codemirror.net/5/doc/manual.html#vimapi how to hook into them https://github.com/replit/codemirror-vim)

**Comment by zefhemel** [comment]
Ok, this seems to happen when I have Grammarly enabled (Chrome plugin) only. Please reopen if somebody finds this breaking in other scenarios.

**Comment by Kevinizevbigie** [comment]
Also happens when Vimium (Chrome vim plugin) is active on the silverbullet instance
