### ISSUE TITLE
Suggestion: Move page title inside CodeMirror editor

### ISSUE THREAD

**Issue by tomusher** [silverbulletmd/silverbullet#205]
As it is right now, the title of a page is edited in a separate input. This means

- the emoji picker doesn't work
- slash commands (if there were any that were useful in a title) don't work
- long titles don't wrap
- new editor features like vim bindings can't be used in the title
- you can't navigate 'naturally' to the title using arrow keys

If the title was 'inside' the CodeMirror editor as a special fixed element, all those problems would go away.
Appreciate there's likely to be issues with trying to add directives or 'dynamic' features to titles, so I imagine this isn't that straightforward.

Loving Silverbullet, great work!

**Comment by zefhemel** [comment]
Not sure if moving it inside is the right approach, but we can definitely consider turning the page title into a "mini codemirror" editor, which would have the same effect.

While at it, the same should be done for the page switcher input as well as the command palette input.
