### ISSUE TITLE
"Refactoring: Extract to Page" command

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#210]
Would cut the current selection (or if nothing is selected the current section based on header?), ask for a page name, replace it with a page reference and move the content to the new page.

**Comment by yorrd** [comment]
also interesting, "merge with page"

**Comment by zefhemel** [comment]
Yes, that makes sense. You could also decide to not merge it into core, but create a separate plug repo: https://github.com/silverbulletmd/silverbullet-plug-template

But honestly, I think this will be useful enough to have in core, so yes — I'd put this functionality in `plugs/core/refactor.ts` or similar.
