### ISSUE TITLE
navigation controls for mobile PWA

### ISSUE THREAD

**Issue by strcrzy** [silverbulletmd/silverbullet#214]
When using silverbullet as a Mobile PWA on iOS, users lose Safari navigation controls.

I believe the mobile PWA could benefit from back and forward buttons in the nav bar.
I have attached a crude design proposal (my suggestions in red).

![mobilepwa](https://user-images.githubusercontent.com/119740/208312070-7fde79f4-4086-42f6-8e95-d6ca0194e9e7.jpeg)

**Comment by zefhemel** [comment]
Yep, we can do this. I should mention that the usual swipe from left or right border from the screen gestures to go backwards and forward work fine. That's what I use myself.

**Comment by v411e** [comment]
It looks like on Android there is no such a swipe gesture.

**Comment by Maarrk** [comment]
What if we make it possible to display `actionButtons` from SETTINGS conditionally based on mobile and/or PWA display?

Would also be helpful for adding files, or I'd hide my template picker on mobile.

Probably more feasible now, with Expression language

**Comment by zefhemel** [comment]
Implemented by @Maarrk via custom action buttons.
