### ISSUE TITLE
feature request: publish

### ISSUE THREAD

**Issue by strcrzy** [silverbulletmd/silverbullet#216]
one thing i would really love to be able to do one day that i think is pretty close to possible with what you have already built is to take a silverbullet directory tree (or a page in that tree), and render its pages as html into a static site. 

we can almost do this today with existing tools, but they wouldn't support `[[` links among other things. it might be a while, but i just wanted to request this in case it wasn't on your radar yet.

something like 

`silverbullet --generate-html --include-images`
or `silverbullet --generate-html --generate-index --start-page=journal --follow-linked-pages --max-depth=4 `

by no means comprehensive, just spitballing

**Comment by zefhemel** [comment]
I already built a basic version of this: https://github.com/silverbulletmd/silverbullet-publish

However it's broken right now since various major refactorings. I'll put it on my backlog to fix so you can play with it.

**Comment by zefhemel** [comment]
What you could do now is have a look at the README on how it works and create issues in that project with ideas in how to improve it (if it were to operate as described).

**Comment by strcrzy** [comment]
thanks so much! will definitely take a look :)

**Comment by zefhemel** [comment]
Work on this is in progress: https://pub.silverbullet.md
