### ISSUE TITLE
PWA not available with docker installation

### ISSUE THREAD

**Issue by BaptisteBdn** [silverbulletmd/silverbullet#217]
I am not able to install a progressive web app, I think it might have something to do with the docker installation.
Tested with chrome browser as well as Firefox android. It is working just fine with https://silverbullet.md.
I am using Traefik as the reverse proxy as well as Authelia for authentication, but I tested without and the problem is still there.
Maybe a config file is missing in the Dockerfile ?

**Comment by zefhemel** [comment]
You have to make it available via HTTPS. That's a PWA requirement.

**Comment by BaptisteBdn** [comment]
Silverbullet is available via HTTPS through Traefik, is PWA enabled during the github action build ?

**Comment by BaptisteBdn** [comment]
My bad, this was a CORS issues that was caused by using Authelia for authentication. It was not able to fetch the manifest.json file.

**Comment by zefhemel** [comment]
Alright 👍🏻
