### ISSUE TITLE
Tabbing or clicking away from a new page title does not persist the title

### ISSUE THREAD

**Issue by mkraft** [silverbulletmd/silverbullet#222]
# tabs repro
1. create a new page with the chord option+shift+n
2. click into the title
3. type a new title (ex my new page)
4. press tab

# click repro
1-3. same as above
4. click into the body of the document

# expectation vs reality (same for click and tab)
expected: page title is saved
actual: page title reverts to the default (ex Untitled, in English)

**Comment by zefhemel** [comment]
Yeah this is by design. Right now you have to press enter to apply the change. Do you think it should always save? I guess that can also make sense.

**Comment by zefhemel** [comment]
I suppose this originates from the time that it was still a bit scary to rename a page, but I think once I fix #221 this should be fine.

**Comment by mkraft** [comment]
Seems UX-consistent to auto-save titles if the document body is being auto-saved.

**Comment by zefhemel** [comment]
Agreed, I'll change this.
