### ISSUE TITLE
Trouble building locally

### ISSUE THREAD

**Issue by jamesob** [silverbulletmd/silverbullet#224]
I'm trying to modify the Dockerfile so that I can build a local copy of silverbullet without having to install deno on my host; so far the change is pretty simple:
```diff
diff --git a/Dockerfile b/Dockerfile
index f9d6c28..57f6f48 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,8 +7,8 @@ FROM denoland/deno:alpine-1.28.3
 #   docker run -v myspace:/space -it zefhemel/silverbullet
 VOLUME /space

-# Copy the bundled version of silverbullet into the container
-ADD ./dist/silverbullet.js /silverbullet.js
+ADD . ./
+RUN deno task build bundle && cp ./dist/silverbullet.js /silverbullet.js
```

Oddly, when I run `deno task bundle` in the container as above, the `dist/` folder doesn't contain `silverbullet.js`. This is odd because the `./script/build_docker.sh` script seems to assert that this would be the case.

**Comment by zefhemel** [comment]
Right. `deno task` doesn't allow you to specify multiple tasks in one go, you have to run them separately. This should work:

```
RUN deno task build && deno task bundle && cp ./dist/silverbullet.js /silverbullet.js
```

Is installing Deno on your host system really problematic enough to jump through all these hoops and accept the significant waiting for every docker build cycle?

**Comment by jamesob** [comment]
> Is installing Deno on your host system really problematic enough to jump through all these hoops and accept the significant waiting for every docker build cycle?

I'm a little paranoid and prefer to keep my host as free of dependencies as possible, especially when it comes to the javascript ecosystem. :)

**Comment by jamesob** [comment]
Your suggestion worked, thanks!
