### ISSUE TITLE
404 for Silver%20Bullet.md

### ISSUE THREAD

**Issue by kjk** [silverbulletmd/silverbullet#231]
Currently on https://silverbullet.md/ you can see in the console the following error:

```
util.ts:5 Error: File not found
    at J1.getFileMeta (http_space_primitives.ts:117:13)
    at async z1.getPageMeta (space.ts:95:7)
    at async space.ts:76:11
(anonymous) @ util.ts:5
Promise.catch (async)
qi @ util.ts:4
(anonymous) @ space.ts:64
http_space_primitives.ts:23          
OPTIONS https://silverbullet.md/fs/Silver%20Bullet.md 404
```

I'm guessing it's supposed to check for`Silver_Bullet.md` ?

**Comment by zefhemel** [comment]
This is specific to the silverbullet.md deployment. It's running on Netlify without a proper SB backend in place. SB doesn't know any of this and is making regular `OPTIONS` calls that somehow Netlify doesn't seem to support and give 404s for. Hence the errors. It doesn't affect functionality, so I haven't looked at a solution yet.
