### ISSUE TITLE
Add support for syntax highlighting in code blocks

### ISSUE THREAD

**Issue by mkraft** [silverbulletmd/silverbullet#234]
This may be a duplicate, I searched the issues and homepage and didn't see it.

**Comment by zefhemel** [comment]
It's there for JavaScript, typescript and YAML, using the

    ```javascript
    
    ```

Syntax. See the demo of this also on silverbullet.md. 

Every language will add to the bundle size, but any language you're missing specifically?

**Comment by mkraft** [comment]
Personally I'd rather have syntax support for the languages I use than a smaller bundle. 

When I wrote this ticket I was missing it for sql. 

I wonder if optional language support could be an option if size is deemed to be a blocker?

**Comment by zefhemel** [comment]
It may not be too big. And there need to be lezer/codemirror parsers for it. I can check if one exists for SQL.

**Comment by zefhemel** [comment]
We’re in luck: https://github.com/codemirror/lang-sql This can likely be plugged in easily here: https://github.com/silverbulletmd/silverbullet/blob/main/web/editor.tsx#L498

**Comment by mkraft** [comment]
Opened https://github.com/silverbulletmd/silverbullet/pull/292 for review.
