### ISSUE TITLE
data loss from weird but valid markdown

### ISSUE THREAD

**Issue by strcrzy** [silverbulletmd/silverbullet#236]
Hi, I was editing a document and wound up putting it in a situation where it started like this:

```

#

# `all wisdom comes from memory` 

```

my intention was to add a nice header to center myself, but I kind of messed it up and wound up with an empty header line above the actual header line. before i could fix this, the rendering glitched to a blank note and I saw a stacktrace in my browser that looked like this:

```
RangeError: Invalid range for replacement decoration
    at oc.range (view.js:2:20727)
    at enter (hide_mark.ts:97:31)
    at We.iterate (common.js:2:3357)
    at hide_mark.ts:82:23
    at create (util.ts:69:14)
    at pt.create (state.js:5:16713)
    at Object.create (state.js:5:16788)
    at tt.computeSlot (state.js:5:27243)
    at Gu (state.js:5:19623)
    at new tt (state.js:5:24632)
```

The part where it gets weird though, is if I edit the blank note, a new note will overwrite the previous one with the new edits (starting from a blank, which doesn't bode well for the previous note!)

I back up all my notes of course, and this seems like a weird corner case, but this might lead to a bad situation for those who run into it and don't recognize what is happening and might accidentally overwrite their note while trying to figure it out.

Thanks again for silverbullet. 🙏

**Comment by zefhemel** [comment]
Yeah, this doesn't look good. I'll look into it.

**Comment by zefhemel** [comment]
Found the issue, fixed. Thanks for reporting!
