### ISSUE TITLE
Attachment link with an empty name doesn't work

### ISSUE THREAD

**Issue by ekaragodin** [silverbulletmd/silverbullet#240]
Links like `[](attachment/path)` and `![](attachment/path)` lead to the broken url `/fs/)` after a click. Embedded preview for `![](attachment/path)` works fine. Also, link `[](attachment/path)` is hidden when it is out of focus.

**Comment by zefhemel** [comment]
Thanks! Fixed now. Not live previewing empty link texts (seemed the best solution), and also fixed clicking on a empty anchor text that's not live previewed.
