### ISSUE TITLE
uploads with spaces in saved filenames breaks link formatting

### ISSUE THREAD

**Issue by strcrzy** [silverbulletmd/silverbullet#243]
if i drag "curious george.jpg" into SB and save it as such, the file is uploaded correctly, but the link refuses to format properly.
i believe this is because of the spaces in the filename, because if i rename the file and update the link, the image renders / link works.

I see a stacktrace that looks like this pop up when I try to click on a link to a filename with a space in it:

```
util.ts:5 Error: Cannot read properties of undefined (reading 'children')
Stack trace: TypeError: Cannot read properties of undefined (reading 'children')
    at te (eval at <anonymous> (worker.js:1:1313), <anonymous>:3:3593)
    at g (eval at <anonymous> (worker.js:1:1313), <anonymous>:3:3913)
    at async worker.js:1:1620
    at Z0.onMessage (sandbox.ts:121:15)
    at webworker_sandbox.ts:17:20
    at $l (util.ts:2:3)
    at Worker.<anonymous> (webworker_sandbox.ts:16:7)
```

**Comment by zefhemel** [comment]
Right, the SB (rather: Code Mirror) markdown parser doesn't allow spaces in the path name. Fixed to URI Encode the path for the inserted `![](...)` or `[](...)` links when uploading a new attachment.
