### ISSUE TITLE
Add ability to pass arguments to command links

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#244]
The `{[notation]}` in addition to supporting an alias, should also support passing arguments somehow. Open to ideas on syntax.

**Comment by jwalzer** [comment]
As I have a vision for a concrete usecase, and was about to open a new issue, I'm happy I found this.
I'd like to build a site-index, where I can quickly glance over pages and possibly delete them.
Therefore I would build an query und use a template that includes the `Page: Delete` command, but delegate that to the page from the query.

My suggestion was to go for: `{[CMD]:[ARGS]}` ... which would then be `{[Page: Delete]:[{{name}}]}`

**Comment by 20after4** [comment]
Rather than inventing new syntax, why not lean on javascript syntax?

The native template literal syntax is perfect, IMO.

```${cmd(arg1, arg2)}```


Maybe this is only intuitive to a javascript programmer but I think this is cleaner than having a bunch of nested square and curly braces.

So `${page.delete(name)}`

**Comment by zefhemel** [comment]
@20after4 currently the syntax for creating a command link is `{[Name of the command]}` or when aliased: `{[Name of the command|my alias}]` how would you suggest these look with a JS-style syntax? Command names are not JS identifiers right now (they're the same names you see in the command palette).

**Comment by zefhemel** [comment]
Implemented
