### ISSUE TITLE
Support URL-based link to jump to an anchor

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#248]
### Discussed in https://github.com/silverbulletmd/silverbullet/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **pgr0ss** December 27, 2022</sup>
It would be great to be able to link to a specific section in a page (e.g. sections defined by headers like `##`), not just the top of the page. For example, linking to a section of https://silverbullet.md/%F0%9F%94%8C_Core/Templates within silverbullet, or even being able to send someone a link with the section in the URL. Thanks!</div>

**Comment by montarion** [comment]
this one isn't on the roadmap, and the link to the discussion is dead. I also don't see anyting in https://silverbullet.md/Markdown/Basics. Do you happen to have any updates?

**Comment by montarion** [comment]
This seems to be an old one, I think this can be closed? [[note#header-name]] gets you to the right place.

**Comment by zefhemel** [comment]
Yep!
