### ISSUE TITLE
Backticks not hidden when leaving a fenced code block which is indented

### ISSUE THREAD

**Issue by rjgibson** [silverbulletmd/silverbullet#249]
The three backticks aren't hidden when the cursor is moved out of a fenced code block which is indented:

This works as expected:

```
code block
```

whereas the backticks aren't hidden in the following case:

- List item

    ```
     indented code block
    ```

despite the fact that the code block is properly rendered in preview mode.

**Comment by zefhemel** [comment]
Nice find, should be fixed now.
