### ISSUE TITLE
Pre-render HTML for content pages on SilverBullet.md

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#251]
I doubt search engines index anything on SilverBullet.md right now. It may be nice to pretender or render on the fly using edge functions on Netlify.

**Comment by yorrd** [comment]
![image](https://user-images.githubusercontent.com/1191486/210132546-5746c4c0-bf2a-4d5f-aa86-db028c799bdd.png)

seems to me like it's at least partially indexed. I'm guessing the links are not crawled for some reason. You could check that using the [google search console](www.google.com/webmasters/). Happy to assist via PM to get that up and running. Shouldn't need additional infrastructure even though that would be a cool feature. We run several sites without prerendering that are indexed just fine.

**Comment by yorrd** [comment]
there seems to be an issue when clicking on the Google link though because it will route to `https://silverbullet.md/%F0%9F%94%8C_mattermost/` instead of `https://silverbullet.md/%F0%9F%94%8C_Mattermost`

**Comment by yorrd** [comment]
there seems to be an issue when clicking on the Google link though because it will route to `https://silverbullet.md/%F0%9F%94%8C_mattermost/` instead of `https://silverbullet.md/%F0%9F%94%8C_Mattermost`

**Comment by zefhemel** [comment]
Implemented
