### ISSUE TITLE
iframe embedding of external contents

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet#258]
Obsidian uses a Syntax like `![[link]]` to embed local notes without materializing them into the note. Maybe we could do something like `![...](link)` to iframe the link into the current note? This seems useful to me in terms of integrating a flow chart or miro board or something that has been created externally and needs to be consumed together with one's own notes on the topic (meeting notes).

**Comment by zefhemel** [comment]
Interesting. That seems useful and fairly easy to do. Need a different syntax though, the one you're proposing is used for inlining images. Also, need a way to determine the desired width and height for the iframe.

**Comment by yorrd** [comment]
Obsidian only offers writing iframes as html. 

Adressing your points: Let's just make it a directive, `/embed`?

```
<!-- #embed https://link.example width = "400px" height = "300px"  -->

<!-- /embed -->
```

default being some height and 100% width?

Considering styling: I think the current content width is too small, could we make iframe sections full width?

**Comment by zefhemel** [comment]
Generally directives would have the content they render inline, but that’s not what we’d want in this case right? The general expectation is that something dynamic happens with their content upon update. The syntax would allow for adding attributes like width and height, that’s true.

**Comment by yorrd** [comment]
yeah you're right. It's somewhat misleading. On the other hand, one could even allow 

```
<!-- #embed https://link.example width = "400px" height = "300px"  -->
<custom> html code </custom>
<!-- /embed -->
```
and `/iframe` just being a shorthand for 
```
<!-- #embed https://link.example width = "400px" height = "300px"  -->
<iframe src=... style="..."> </iframe>
<!-- /embed -->
```
wdyt?

**Comment by zefhemel** [comment]
For the general case (not inlining your own pages) what about:

    ```html 
    <iframe ...>
    ```

Which live previews to rendering the actual HTML? Trivially doable with current plug extension points. Perhaps this shouldn't be `html` but `html-embed` or something for those who just want to show HTML snippets not render them.

**Comment by pm64** [comment]
I like the embed syntax. Perhaps the inner portion should be expressed in JSON, to allow the possibility of additional parameters.

```
    ```embed
    {
        "url": "https://silverbullet.md/"
    }
    ```
```

**Comment by zefhemel** [comment]
I like the idea of using something structured for the body here, but I'd vote for YAML. Because we use that everywhere already (and we can get free syntax highlighting for it). Let me give this a should, should be easy to add and solves my need of wanting to embed the SB roadmap on the SB website.

**Comment by zefhemel** [comment]
Ok, first implementation done! Docs: https://silverbullet.md/Markdown/Code_Widgets (embed section)
