### ISSUE TITLE
missing command in dockerhub instructions

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#259]
Hi! Love the project's concept and grateful for your efforts. 

I was running into some unexpected crashed so I decided to run with docker compose. Following the instructions  at https://hub.docker.com/r/zefhemel/silverbullet

<img width="805" alt="image" src="https://user-images.githubusercontent.com/867661/210152956-e0b609be-f88a-4afd-bc47-26fea8992641.png">

running the first line errored: 
``` 
$ deno task bundle
Task bundle deno bundle silverbullet.ts dist/silverbullet.js
error: Module not found "file:///home/tristan/silverbullet/dist/asset_bundle.json".
    at file:///home/tristan/silverbullet/cmd/invokeFunction.ts:3:25
```
so I tried the build command (thinking it should populate some of the `/dist` folder and running `deno task build` seemed to allow me to progress. 

I'm not sure if the build command should be added, but it seems like something should be changed on those instructions. I'm on a raspi/ubuntu

**Comment by zefhemel** [comment]
Thanks, the correct instructions are in the README, but I hadn’t updated the copy on docker hub yet. Should be correct now. Let me know if it’s not!
