### ISSUE TITLE
Soulver-like calculation support

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#26]
This one's a bit out there and I'm not 100% how this should work, but I really like the free form way you can write calculations in [Soulver](https://soulver.app/) and I wonder if we can accomplish something similar in SB. 

Open ideas on even how this could work purely from the UX perspective, implementation can come later.

**Comment by zefhemel** [comment]
If you look at the Soulver UI, it used a panel to the right to show calculation results. This is doable in SB but it will be tricky to align it with the text.

Alternatively, perhaps calculation results can be inlined in the page text similar to how this works with queries. We'd have to figure out a clean way to put in those results and make them update on the fly(ish).

**Comment by zefhemel** [comment]
Can be based on this: https://github.com/5anthosh/fcal

**Comment by zefhemel** [comment]
And this https://github.com/gtg922r/obsidian-numerals

**Comment by jamesob** [comment]
Along these lines too is something I'm interested: ipython integration. I think conceptually they are both pretty similar; you have cells which are acted upon by some external process (whether that's a calculator or a python interpreter), and results are presented (and potentially cached). You'd also potentially have dependencies across cells for recomputation.
