### ISSUE TITLE
Plug idea: Table of Contents

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet#263]
Syntax could be 

```
<!-- #toc  -->

<!-- /toc -->
```

resulting in

```
<!-- #toc  -->
- h1 text
  - h2 text
  - h2 text
    - h3 text
- h1 text
- ...
<!-- /toc -->
```

Wdyt?

**Comment by yorrd** [comment]
Actually, just tried that. I'm naturally getting

```
<!-- #eval helloworld.toc() -->
**ERROR:** Unregistered syscall editor.getCurrentPage
Stack trace: Error: Unregistered syscall editor.getCurrentPage
    at blob:null/c53ce345-b18c-4464-a505-fe21cbdc2316:1:1962
    at c (blob:null/c53ce345-b18c-4464-a505-fe21cbdc2316:1:38)
    at blob:null/c53ce345-b18c-4464-a505-fe21cbdc2316:1:1272
    at innerInvokeEventListeners (deno:ext/web/02_event.js:775:9)
    at invokeEventListeners (deno:ext/web/02_event.js:815:7)
    at dispatch (deno:ext/web/02_event.js:684:11)
    at dispatchEvent (deno:ext/web/02_event.js:1063:14)
    at pollForMessages (deno:runtime/js/99_main.js:159:9)
<!-- /eval -->

```

Is there any way to get the current page on the server side? Should I rather register a custom directive? What's the way to go here?

**Comment by zefhemel** [comment]
Sorry, completely missed this one before. No, there’s no way to get the current page on the server side, because the server doesn’t know the state of all (possibly multiple) clients.

As a feature, I think a #toc directive seems cool. The way I’d build it is it is add integrate it into the existing directive plug, code lives here: https://github.com/silverbulletmd/silverbullet/tree/main/plugs/directive

Since this is triggered from the client, the name of the current page being processed is passed to the server, so it should be available. If you need more specific pointers on how to approach this, let me know, happy to help!

**Comment by skyrunner15** [comment]
Any word on this feature? It would be super handy for longer notes!

**Comment by zefhemel** [comment]
I think the way we'd want to build this feature is that it doesn't just show an outline, but also makes those items clickable right? Something slightly tricky here may be that this would require some sort of way to navigate to specific headers in the page. At first I was thinking of using positions (# of characters from start of document), but those shift as part of even updating the TOC. So maybe we'd need some sort of syntax that allow pointing to headers based on some auto-generated slug, e.g.

```
## My header
```

You could point to via:

```
[[My header@#my-header]]
```

Just thinking out loud at this point

**Comment by zefhemel** [comment]
Since we no have Live Queries and Live Templates, I think this may also be implemented in a similar fashion, like a "Live TOC". Since pushing this up my priority list a bit :)

**Comment by zefhemel** [comment]
What do you think about the alternative implementation of not including this in the page itself, but just as a UI element at the top of the page, similar to how we have Linked References right now at the bottom of a page?

**Comment by skyrunner15** [comment]
Sounds like a good idea since it should be interactive and bring the user to a specific point in longer notes.
