### ISSUE TITLE
Daily Note Templates not working

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#265]
Hi again! 

I'm looking to use a custom template for daily notes. From the docs, and my light reading of the code it seems like creating a file `templates/page/Daily Note` should be sufficient for this, however I have such a file and new daily notes are not being created from the template. 

The template (`templates/page/Daily Note`) is never available in my page search (which I assume is a hard coded exclusion) but I do have log entries like 
```
Saving file templates/page/Daily Note.md
[Sandbox log] Reindexing templates/page/Daily Note
```

Manually setting the `dailyNoteTemplate` to the default `templates/page/Daily Note` in SETTINGS seems to have no effect. 

Below is the template I'm trying to use, in case there is some kind of runtime or parsing exception that is preventing it's use.
```md
---
$name: "📅 "
---
Gratitude:
Weight:

[[{{tomorrow}}]]
[[{{yesterday}}]]
```

**Comment by tristansokol** [comment]
Looking at the code again I thought there was possibly an issue with the markdown parsing preventing the use of the template, but after manually reindexing, I now see the template in my search.

**Comment by zefhemel** [comment]
Ok, so the bug is in the documentation, it's not `templates/page/Daily Note` it's `template/page/Daily Note`. And the `$name` front matter doesn't do anything, it always uses the thing you specify as a `dailyNotePrefix` in `SETTINGS` as a prefix. Let me update the docs.

**Comment by tristansokol** [comment]
awesome thanks! I just came to same typo conclusion.
