### ISSUE TITLE
Can't seem to be able to paste in GIFs

### ISSUE THREAD

**Issue by shootie22** [silverbulletmd/silverbullet#267]
I can't seem to be able to paste GIFs into a silverbullet page. I can paste images just fine, but GIFs don't show up.

Screenshot:
![image](https://user-images.githubusercontent.com/39218788/210276693-41bb1e79-04e3-46cf-aa31-54d04053eddc.png)

I'm not sure if I'm missing something or if I'm doing something wrong. Either way, awesome project!

**Comment by zefhemel** [comment]
OH NO, GOTTA HAVE WORKING GIFS!!!11

I'll look into what's going on here 🙂

**Comment by zefhemel** [comment]
I changed a bit how inline images work now, and when I drag in an animated gif it seems to work fine. Could you try again?

**Comment by zefhemel** [comment]
Please reopen if this is not fixed.
