### ISSUE TITLE
Double scroll bars on Windows/Linux

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#270]
I noticed that in certain window sizes, the basic desktop app (and apparently PWA) shows two scrollbars on the right, that’s not good.

**Comment by yorrd** [comment]
not limited to windows, I got it on the PWA too (arch linux)

**Comment by zefhemel** [comment]
Ah, good to know! Yeah, this is what you get when you use Mac (which hardly ever renders scrollbars)
