### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#274]
Hi, 

Trying to get my development environment setup to debug #265. After installing Deno with homebrew, then running the suggested commands (deno task build, install, watch-web, watch-server) `watch-server` fails with 83 similar errors: 
```
TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
          </div>
          ~~~~~~
    at file:///silverbullet/web/editor.tsx:1046:11

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
          <div className="sb-bhs">
          ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///silverbullet/web/editor.tsx:1049:11

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
          </div>
          ~~~~~~
    at file:///Development/silverbullet/web/editor.tsx:1051:11
```

Based on (random googling)[https://stackoverflow.com/questions/37674017/how-to-solve-jsx-element-implicitly-has-type-any-error] it seems like maybe I'm missing some kind of react type dependency, but I'm not sure exactly how to get it with Deno ( I tried a `npm i -g @types/react` but it didn't seem to help.

**Comment by zefhemel** [comment]
This is very strange. Using npm won't do anything, we don't use it. What version of Deno are you using? `deno --version`?

**Comment by tristansokol** [comment]
> Using npm won't do anything, we don't use it.
makes sense! 

```
deno --version
deno 1.23.3 (release, x86_64-apple-darwin)
v8 10.4.132.8
typescript 4.7.4
```

**Comment by zefhemel** [comment]
Ok, that's pretty old, you got that from homebrew? I think we need 1.26 at least, could you try installing the "official" way? https://deno.land/manual@v1.29.1/getting_started/installation

**Comment by tristansokol** [comment]
huh, seems like I had a stuck dependency that was pinning me to an older version, fixing that and reinstalling from homebrew gave me a 1.29 version. 

That seems to do it! `deno task watch-server` seems to work now. Thanks for your help!

**Comment by zefhemel** [comment]
👍🏻
