### ISSUE TITLE
support multiple hostnames

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#278]
Hi! 

I'd like to access from my local network, as well as my public ip/VPN. Would it be possible to support multiple hostnames? Or is a reverse proxy the only option?

**Comment by zefhemel** [comment]
Wouldn't listening on `0.0.0.0` achieve that? I just checked, and Deno doesn't support specifying multiple hostnames. It would be possible to instantiate servers for each hostname I suppose, but you really gotta want it ;)

**Comment by tristansokol** [comment]
ahh, 0.0.0.0 works for what I wanted. Thanks!
