### ISSUE TITLE
PWA offline data persistance / offline access

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#289]
Ok, the one thing that keeps me from switching 100% is that if my server is down, I can't access my notes to bring my server back up.  Could we change some of the pwa settings to keep a cache? likely start with a read-only copy so you don't have to worry as much about update collisions, but if you already have collaborative editing maybe that would be trivial. 

Generally I have seen this implanted in apps by adding in a middle layer to data reading and keeping a cache in localstorage for a worker or the like.

**Comment by zefhemel** [comment]
Have a look at #296 and add your thoughts. I'm currently leaning towards offering "native" mobile apps that do full on sync. For this I'll have to build a sync engine #261 anyway. If there's a big demand for a fully offline capable PWA #59 this could also be built. It wouldn't be rocket science, just yet another permutation of all subsystems that need to be built, maintained and checked.

**Comment by tristansokol** [comment]
Thanks! I'll reply in that thread. I don't suspect PWAs will be as demanded with full mobile support.

**Comment by zefhemel** [comment]
Agreed, I think this will be a bit niche, but if PWAs ever become a big thing — we’re in a good place to actually implement this.

**Comment by zefhemel** [comment]
This is now implemented, closing 😄
