### ISSUE TITLE
Command palette search breaks with Show Logs on

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#291]
Something seems to be off about the async updates for searching commands and pages. The inital typing seems to be a fast list reduction but eventually new results will load in, which don't seem to be using the input. 
![Jan-05-2023 20-08-18](https://user-images.githubusercontent.com/867661/210909203-4e08e0cd-d4d1-4af6-bbf5-9cd906af2c22.gif)

**Comment by zefhemel** [comment]
This is really strange, and I cannot replicate this myself. After typing "update" here you only wait, you're not pressing any additional keys?

**Comment by tristansokol** [comment]
Correct, But I just realized it is only an issue when the `Debug: Show Logs` is active. I'm guessing there is a timed task that updates the log windows and somehow loses the typed in state of the input

**Comment by zefhemel** [comment]
Ah yes indeed, I've noticed that too in the past. It's specific to the reload behavior of show logs indeed.

**Comment by zefhemel** [comment]
Fixed this for now by making refresh a manual operation, not a great solution but it works.
