### ISSUE TITLE
Snippets do not work on Windows

### ISSUE THREAD

**Issue by cgudrian** [silverbulletmd/silverbullet#297]
Despite having multiple pages in the "snippet" folder
![image](https://user-images.githubusercontent.com/204897/211314940-996d3ff5-3798-43ed-a151-f85faff8e4fd.png)
none of them can be inserted as a snippet:
![image](https://user-images.githubusercontent.com/204897/211315069-e31c992a-54a3-4926-ae83-7e8e7ec81de6.png)

Setting `snippetPrefix` to `snippet\` in the *SETTINGS* page makes the *Snippets* command work correctly. That however, brakes snippets on non-Windows systems, as settings are shared.

**Comment by zefhemel** [comment]
Hmm. You shouldn't use backslashes in page names just slashes even on windows, can you try creating a page named like "snippet/my snippet" and see if that works?

**Comment by cgudrian** [comment]
Creating a page named "snippet/my snippet" yields a page titled "snippet/my snippet". In the "Open" dialog it shows up as "snippet\my snippet":
![image](https://user-images.githubusercontent.com/204897/211386928-49681037-c972-40ff-bd50-54e25f2766fb.png)

Running _Silver Bullet_ from WSL on the same data folder works as expected.

**Comment by zefhemel** [comment]
Understood, this is related to this one #235 
Have to look into it

**Comment by cgudrian** [comment]
Seems right. I'll close this issue then. Thanks for your work!

**Comment by cgudrian** [comment]
Duplicate of #235.

**Comment by zefhemel** [comment]
I'll leave this open, because this instance of it is actually more urgent than the one I linked earlier.

**Comment by cgudrian** [comment]
Thanks for the quick fix!
