### ISSUE TITLE
Query Pages in Directory 

### ISSUE THREAD

**Issue by andersmmg** [silverbulletmd/silverbullet#299]
I want to have some pages inside directories, which works great though there's not a way I can see to get a list of subpages for one. How could I do this? Or is there another recommend way to do nesting?

**Comment by zefhemel** [comment]
There's no specific support for nesting, but you can match names with a regular expression. For instance, to find all pages in the "People" folder, you can write:

```
<!-- #query page where name =~ /^People\// -->

<!-- /query -->
```

Hope that helps!
