### ISSUE TITLE
link unfurling not working?

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#300]
I just tried to do some link unfurling as describe here https://silverbullet.md/%F0%9F%94%8C_Core/Link_Unfurl

It looks like the code was merged in 5 months ago, but I'm not seeing the command to unfurl in either my instance or the public site. It looks like there might be some kind of requirement for the command to be an option? If so how do you trigger it? https://github.com/silverbulletmd/silverbullet/blame/dc7de9d8f963f121045cbdd34aeb5a1b482bb5ae/plugs/core/core.plug.yaml#L396

**Comment by zefhemel** [comment]
It's a context sensitive command that is only available (via the shortcut or command palette) when your cursor is positioned in a "naked URL" on a page, e.g. https://silverbullet.md
