### ISSUE TITLE
Plug idea: dead links

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#302]
Frequently I'll be writing and add in something as a link before there is a page for it. It might be nice to be able to see a page of all the dead links so you can go back and make pages for them. Or associate them to pages you have created, but have slightly different names

Seems like it would be similar to full text search plugin, but just searching for ilnks. Or maybe you could list all links and use something like levenshtein to find ones that are similar to the dead links.

**Comment by zefhemel** [comment]
I like the idea!

**Comment by tristansokol** [comment]
What is the best way to get all of the space's content?

**Comment by zefhemel** [comment]
There's no really efficient way. You'll just have to space.listPages() and then do a space.readPage() for each. Potentially this can be parallelized.

**Comment by zefhemel** [comment]
There is a `Broken Links: Show` command now
