### ISSUE TITLE
Wiki links with aliases don't work in tables

### ISSUE THREAD

**Issue by strout** [silverbulletmd/silverbullet#304]
Links with the `[[page|alias]]` syntax don't work how I would expect inside tables.

For instance:

```md
| header                        |
|-------------------------------|
| [[wiki link without alias]]   |
| [[page|wiki link with alias]] |
```

![image](https://user-images.githubusercontent.com/110026/211890683-bac1db82-530e-4f23-821f-248c42bcf677.png)

As a workaround, a backslash before the link's pipe works, as shown below, but that has a couple problems:
* I encountered this in a `#query task` table and I don't know if I can escape it within the query. 
* clicking the link while editing it navigates to `page/` instead of `page`.

workaround:
```md
| header                        |
|-------------------------------|
| [[wiki link without alias]]   |
| [[page\|wiki link with alias]] |
```
![image](https://user-images.githubusercontent.com/110026/211891164-c4292aee-de38-48d8-8a23-9a81b0bc0289.png)

I don't know how parsing is implemented but perhaps the precedence of these two pieces of syntax could be reversed.

**Comment by zefhemel** [comment]
Got it, will look into it.

**Comment by zefhemel** [comment]
Should be fixed now.
