### ISSUE TITLE
[Desktop] Add icons for Linux desktop

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#308]
Works for Mac and Windows, somehow not yet on Linux.

**Comment by sahensley** [comment]
I was able to get the icon to work in a Desktop file, but I don't know how much help that will be for the bundled release.

## Create the icon file
Create a resized copy of logo.png to 48x48 and install it to ~/.local/share/icons/hicolor/48x48/apps/silverbullet.png.  

I used GraphicsMagick, just drop the `gm` portion to get the ImageMagick command.
`gm convert logo.png -resize 48x48 ~/.local/share/icons/hicolor/48x48/apps/silverbullet.png`

## Create the desktop file

The desktop file was installed to ~/.local/share/applications/silverbullet.desktop

```text
[Desktop Entry]
Name=SilverBullet
Icon=silverbullet
StartupWMClass=silverbullet
Comment=SilverBullet personal knowledge platform
Exec="/var/home/MYUSER/apps/silverbullet/silverbullet" %f
Version=1.0
Type=Application
Categories=Office;
Terminal=false
StartupNotify=true
```
## Update the desktop database

Validate the desktop file: `desktop-file-validate ~/.local/share/applications/silverbullet.desktop`

It seems like the desktop database is automatically updated on Fedora Silverblue but I still run the manual update just to be sure: `update-desktop-database ~/.local/share/applications/`

Run SilverBullet via a menu/runner/whatever and enjoy the pretty icon :smiley:

**Comment by zefhemel** [comment]
Closing since the desktop app is now legacy
