### ISSUE TITLE
Plug installation and management broken on fresh Docker install

### ISSUE THREAD

**Issue by AlexMV12** [silverbulletmd/silverbullet#309]
I had problems with plug-in installation on my installation, so, I tried with a fresh installation using Docker and it happens to be broken even there.

## Steps to reproduce
1. Clone the repo: `git clone https://github.com/silverbulletmd/silverbullet.git`
2. Modify `.env` to put the port 3000
3. run `docker-compose pull`
4. run `docker-compose up -d`
5. go to `localhost:3000`

The installation works, but if you try to run `Plug: Add` and use a plugin, nothing happens --- and the PLUGS page is not created.
This is confirmed by running `Plug:Update`: 

```
Error updating plugs: Error processing PLUGS: Could not read file PLUGS.md Stack trace: Error: Error processing PLUGS: Could not read file PLUGS.md at M (eval at <anonymous> (blob:null/698a7019-2284-4877-88b8-296f52ee4dd6:1:1706), <anonymous>:3:3326) at async blob:null/698a7019-2284-4877-88b8-296f52ee4dd6:1:2013
```

However, even if I create the PLUGS page and put in the same content of `https://silverbullet.md/PLUGS`:
![immagine](https://user-images.githubusercontent.com/36054651/212484337-9ce23f4f-0626-4812-ae2a-8157de6e32ec.png)

and run `Plug:Update`, a new error occurs:

```
Error updating plugs: Error processing PLUGS: r.filter is not a function Stack trace: Error: Error processing PLUGS: r.filter is not a function at M (eval at <anonymous> (blob:null/698a7019-2284-4877-88b8-296f52ee4dd6:1:1706), <anonymous>:3:3326) at async blob:null/698a7019-2284-4877-88b8-296f52ee4dd6:1:2013
```

Any idea? I am on docker image `9a342d6d216c`.

**Comment by zefhemel** [comment]
This should now be fixed. One important thing about this particular plug (the Git one): it relies on the host's install and configuration of Git. The SB docker image does not come with git included at this moment, so it won't work. If there's interest in it, I can likely just add git to the docker image, however still the configuration of the repo, putting in of the proper SSH keys etc. would still be somehow be managed, not sure what's the right way to do that. If you're interested in this, please create a separate issue for it.

**Comment by AlexMV12** [comment]
Thank you very much, I can confirm that now plugins work as intended.
I have no particular interest in the `git` plugin, so if anyone else is interested to it they can open a separate issue as you suggested.
