### ISSUE TITLE
Android mobile application

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#310]
The iOS app is more or less functional (and going live soon). Next: Android!

**Comment by tionis** [comment]
Would this work like a totally normal desktop silverbullet instance and use the shared internal storage?

**Comment by zefhemel** [comment]
In a sense yes, it would keep stuff locally. See: https://silverbullet.md/Mobile

**Comment by tionis** [comment]
Ah yes, thanks for the link!

**Comment by zefhemel** [comment]
Current status: working in an emulator, just have to figure out how to do the whole signing and deployment part and waiting for a physical Android testing device to makes sure this ACTUALLY works.

**Comment by tionis** [comment]
How can I build the current version myself? Would love to alpha test it!

**Comment by zefhemel** [comment]
You need to have Android Studio installed as well as node.js and npm. Then:

```
deno task mobile:deps
deno task mobile:clean-build
```

If this all succeeds, there should be an Android project under `mobile/android` that you can open in Android Studio and run from there (on an emulator or actual device).

**Comment by tionis** [comment]
All right, thanks!

**Comment by tionis** [comment]
After the latest commit, many of the previous errors seems to have disappeared. Android Studio can't compile it though due to version conflict, but that could be misconfiguration in my dev environment.
Part of the error message in question:
```
Dependency 'androidx.room:room-runtime:2.5.0' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.

      :app is currently compiled against android-32.
```

**Comment by joemccall86** [comment]
@tionis This worked for me: https://github.com/silverbulletmd/silverbullet/pull/382

It probably needs to be updated regularly. Maybe this is something dependabot could help out with?

**Comment by zefhemel** [comment]
Just meged @joemccall86 's PR. Sorry for the delay.
