### ISSUE TITLE
Automate syncing

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#315]
Right now it needs to be triggered manually which is annoying.

Ideas on when sync should happen:

* With a debounce after changing a page locally
* Every minute

Obviously, this should be smart about Internet connectivity.

**Comment by pm64** [comment]
Not saying SB should do it this way -- but for context, Obsidian's syncs appear to happen on each local update. And the local update seems to basically use the "debounce after changing a page locally" strategy.
