### ISSUE TITLE
Saving the state of Vim mode settings

### ISSUE THREAD

**Issue by sahensley** [silverbulletmd/silverbullet#319]
Can SilverBullet please save the state of Vim mode settings, similar to how the Vim Mode Toggle is saved?  

I currently run `:imap jj <Esc>` every time I launch SilverBullet, but it would be great if the mapping could be either be saved or have them defined in a YAML block (like a partial vimrc file) as discussed in related issue #193 .

As a short term work-around, could I use a directive and a template to run something like the following code from the codemirror-vim repo which [uses a checkbox to change a Vim mode mapping](https://github.com/replit/codemirror-vim/blob/66891bcbdc6c958fa37bc9cef57bcec248bc4d29/dev/index.ts#L46)?

Thanks for all of the work you've put in developing SilverBullet, it is a wonderful piece of software.

**Comment by zefhemel** [comment]
Oh wow, I didn't even realize remapping works at all 😆 

I think it will be tricky to do the thing, you linked to, but it will likely not be hard to e.g. check if there's a `VIMRC` page (for instance) indeed with a fenced code block with one of those vim command per line that would be executed on load?

If that seems like the right way to go I'll add that to the roadmap.

**Comment by sahensley** [comment]
> .. check if there's a `VIMRC` page (for instance) indeed with a fenced code block with one of those vim command per line that would be executed on load?

I agree, I think that is the cleanest way to go about it. Plus it solves some of the key mapping requests for Vim mode 😀

**Comment by zefhemel** [comment]
Done: https://silverbullet.md/Vim
