### ISSUE TITLE
Task plug: support due times

### ISSUE THREAD

**Issue by pm64** [silverbulletmd/silverbullet#327]
It should be possible for a task's due moment to include a time.

- [ ] take out the trash 🔁 every Sunday 📅 2021-05-02 3:00pm
- [ ] take out the trash 🔁 every Sunday 📅 2021-04-25 ✅ 2021-04-24 10:30am

I'm not sure if the above syntax is optimal, let's discuss!

**Comment by zefhemel** [comment]
Agree, also related to #323 syntax-wise this looks reasonable to me, although the am/pm vs 24 clock debate is always a fun one to have.

**Comment by zefhemel** [comment]
Different solution: https://community.silverbullet.md/t/migrating-from-obsidian-tasks/292
