### ISSUE TITLE
Create plug template

### ISSUE THREAD

**Issue by Willyfrog** [silverbulletmd/silverbullet#33]
To ease development start, there can be a plug-example repo with the bare minimum to clone as a base for the example.

[How to make a repo a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

**Comment by Willyfrog** [comment]
https://github.com/Willyfrog/silverbullet-plug-template

I've invited you to collaborate on it, as I'm not sure how to transfer ownership to the org (already tried and I couldn't create public repos on it)

**Comment by zefhemel** [comment]
I also didn’t see the option to transfer, so I [forked it](https://github.com/silverbulletmd/silverbullet-plug-template) and added you as an admin to the forked repo. Further discussions on the template itself we can have in https://github.com/silverbulletmd/silverbullet-plug-template
