### ISSUE TITLE
Should template placeholders work in $name field?

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#343]
### Discussed in https://github.com/silverbulletmd/silverbullet/discussions/241

<div type='discussions-op-text'>

<sup>Originally posted by **pgr0ss** December 27, 2022</sup>
I have a button to instantiate a new page:

```
{[Template: Instantiate Page]}
```

And I have a template for those new pages, but I noticed that the template placeholders like `{{tomorrow}}` don't seem to work in the `$name` field. For example, I have this template:

```
---
  $name: "Meeting notes/{{today}} "
---

Today is {{today}}

```

And it tries to create a new page named `Meeting notes/{{today}}`, but once created, the placeholder in the body works:

```
Today is 2022-12-27
```
</div>

**Comment by jhjaggars** [comment]
FWIW, I would like to use a feature like this for recurring meeting notes (one on ones).
