### ISSUE TITLE
Feature request: Copy button for code snippets

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#345]
I think it would be handy to have copy buttons for code snippets. Example:

![image](https://user-images.githubusercontent.com/34944988/214948763-144c3e03-789d-404e-af5c-7bf408176a7b.png)

**Comment by devopsicle** [comment]
May seem ridiculous but this is a deal-breaker for me.  However, I think this is an awesome project and has unbelievable potential.  Will definitely be checking back as it matures.

**Comment by joekrill** [comment]
Hey @zefhemel - I have [a working implementation of this](https://github.com/silverbulletmd/silverbullet/compare/main...joekrill:silverbullet:code-copy-button?expand=1) that I can put a PR up for if you're interested in it. I wasn't sure if there needed to be some discussion around the implementation details, though. In particular:

- I implemented this as a CodeMirror plugin. CodeMirror is relatively new to me. Is that the best approach? Did I over-complicate this? Would this be better handled in the editor plug (or a completely different plug)? (is it even possible to implement in a plug?)
- What's the ideal UI/UX? Screenshots below show my current implementation. Do we want to show a button next to or below the language? Should it only show on hover? Should it match the way buttons are shown in template blocks (the refresh/edit buttons)? Or should we try to do something like Obsidian does: the language text (`sb-code-info` text) is what you click on to copy the code (that doesn't seem very intuitive, though). 
- Do we want to limit which languages we show this for? For example, we probably don't want to show a button on `template`, `query`, and `embed` blocks, I wouldn't think? Are there other cases we shouldn't show it? 
- Conversely, are there other block types we'd want to show the button? For example `BlockQuote` or `FrontMatter` blocks?

Screenshots:

<img width="779" alt="Screenshot 2024-02-21 at 2 37 05 PM" src="https://github.com/silverbulletmd/silverbullet/assets/393220/63991aa3-0e3a-4a5e-975d-e1daa62a7933">
<img width="779" alt="Screenshot 2024-02-21 at 2 37 25 PM" src="https://github.com/silverbulletmd/silverbullet/assets/393220/45de4b1b-162f-4694-bab8-b3fee2e844ba">

**Comment by zefhemel** [comment]
A PR would be great! The UI looks good to me, in terms of where it should appear: any fenced code block that doesn't define special behavior I'd say (live queries, templates etc.) and doing this in the CM extension part sounds like the right place. Let's discuss further in the PR once you have it.

**Comment by zefhemel** [comment]
This has since been implemented
