### ISSUE TITLE
Rename folder and update references

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#346]
I think it's currently not possible to rename a folder. You can rename it on disk but this will void all references.

### Example

`[[Books/Harry Potter and the Philosopher's Stone]]`
`[[Books/Harry Potter and the Chamber of Secrets]]`
...
...

Renaming the `Books` page (if one exists) would just rename the corresponding .md file.
Renaming the `Books` folder to `Book` on disk would rename the hierarchy successfully but references won't get updated.

**Comment by henrikx** [comment]
Did you try command "Page: Batch Rename Prefix"?

**Comment by zefhemel** [comment]
As referenced, this is already possible
