### ISSUE TITLE
media up- and download behavior

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#354]
I don't know how files are served internally, but it seems that the downloads are delivered as a base64 encoded blob instead of the raw URL. 

The way I'd love to see downloads happen is how it's already implemented somehow: Like this: https://silverbullet.md/fs/CHANGELOG.md

## some more things I noticed regarding up- und downloads

In my testing every file gets offered as download and doesn't open in a new tab which would be convenient for some file types like PDFs. Sometimes it downloaded the same file twice. For example if I upload a pdf and then download it via Chrome/Edge on Windows this happens:

### 1
![image](https://user-images.githubusercontent.com/34944988/215342151-bb6c7d0f-737d-4a60-934c-51ba25ba77a2.png)

### 2 
![image](https://user-images.githubusercontent.com/34944988/215342143-1358958d-9e38-4e20-9ad5-9a843c499a46.png)

### 3
![image](https://user-images.githubusercontent.com/34944988/215342163-62812864-5434-4220-9c1f-fee13899ed78.png)

Uploading files like `.txt` or `.md` pastes the text of the file in the document.

## Example

![image](https://user-images.githubusercontent.com/34944988/215342981-1d07c754-2a72-46b4-aa11-6af20ca62723.png)

**Comment by zefhemel** [comment]
This should now be better, data URLs are no longer used.
