### ISSUE TITLE
Modifieable line width

### ISSUE THREAD

**Issue by dvbvr** [silverbulletmd/silverbullet#356]
Hi,
Thanks for creating silverbulletmd! I love it! :)

I think it would be even greater, if we could choose the **line width** on our own.
I am not familiar with TS, so I am not sure where the line width should be stored, but here come my suggestions:
*  maybe in SETTINGS?
* Or maybe each page could have it's own SETTINGS space (this would allow us to modify each page on it's own, not sure if one needs it, but it could give each page a unique character).

Not sure if I found the right place but for people with TS skills this might be a good starting point:
![image](https://user-images.githubusercontent.com/23474416/215571961-15513731-3752-41cf-8d2a-a831662433ae.png)

**Comment by jwalzer** [comment]
I would even suggest to allow placing custom CSS into some kind of SETTINGS File, which would allow to apply theming ans customization

**Comment by zefhemel** [comment]
Yep. Working on this now. Will likely be a STYLES page with a fenced CSS block.

**Comment by zefhemel** [comment]
Implemented as part of https://github.com/silverbulletmd/silverbullet/commit/288e67e380f956cb84a40c9146b6a4cc1cd31689

See https://silverbullet.md/STYLES for documentation
