### ISSUE TITLE
Click event for a page in a folder triggers as if it wasn't shortened

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#357]
if there is no text right next to it

https://user-images.githubusercontent.com/34944988/215572921-5f06f636-ab22-41a9-a7f2-82875a4b534c.mp4

**Comment by zefhemel** [comment]
I don't know, but I cannot see this video (tried different browsers and nothing). Could you upload it a different way or describe the problem?

**Comment by itsamemarkus** [comment]
Oh, okay, that's weird. I have to figure out a video format that is more compatible. :D Thanks.

if you click here

![image](https://user-images.githubusercontent.com/34944988/219671195-f6623850-8e47-4a3d-81cf-4dc39b2b4138.png)

it will follow the link as if it wasn't shortened

![image](https://user-images.githubusercontent.com/34944988/219671484-597607ee-6894-47de-a87a-2d616dcdb9ee.png)

which means when I have a line like this

`You should check out [[Software/SilverBullet]]`

and you click here to continue writing that line

![image](https://user-images.githubusercontent.com/34944988/219672298-432fab95-7a55-4fa4-bd0d-49058d65f89f.png)

it will follow the link instead of putting the cursor after the link.

This doesn't happen when there is text after the link

**Comment by zefhemel** [comment]
This was fixed some time ago, but apparently I didn't close the issue.
