### ISSUE TITLE
Feature request: Warning for existing pages when instantiating new ones

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#359]
When using

`{[Template: Instantiate Page]}`

![image](https://user-images.githubusercontent.com/34944988/215765771-f8489279-ba96-43ae-b5ab-5a481fd94304.png)

page gets overwritten with no warning if it already exists.

**Comment by zefhemel** [comment]
Good point, should add a check for this.

**Comment by zefhemel** [comment]
Errr. Ok let me look into that

**Comment by zefhemel** [comment]
My bad, fixed now properly.
