### ISSUE TITLE
Images are not displayed in a table

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#360]
Images break when they're in a table. They then try to load via http://host:port/file.png 

https://user-images.githubusercontent.com/34944988/215868632-ff846f0f-1921-413d-9f3c-ae633623de16.mp4

**Comment by itsamemarkus** [comment]
Hi, I'm not sure where to add this. Images in the table  go beyond the set page width / size is not modified

![image](https://user-images.githubusercontent.com/34944988/221404726-8a3b3f40-8fee-4276-8617-1c6774fb9351.png)

Syntax used for this example

```markdown
| Header A | Header B |
|----------|----------|
| ![](2023-02-26_10-16-25.png) | ![](2023-02-26_10-16-25.png) |
```

**Comment by zefhemel** [comment]
That’s a different issue, could you create a new issue for it?
