### ISSUE TITLE
Feature Request: relative path for images

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#363]
Currently links to images have this syntax

`![](image.png)`

This makes it so that links aren't rendered if you preview  your silverbullet library in GitHub or in a code editor like Visual Studio Code.

imo it would be good to always have the relative path

`![](/image.png)`

---
Bonus feature request 😄 :

Maybe it's worth considering having an images or assets folder instead of storing everything in root. I'm not using silverbullet for that long and the root directory will be full pretty fast

![image](https://user-images.githubusercontent.com/34944988/216762914-782fd9d6-e48d-4778-98d6-bfcaafda11c3.png)

**Comment by zefhemel** [comment]
This makes sense to tweak. Note that SB technically doesn't have a real concept of folders, although anything with a `/` will make the translation to folders behind the scenes. As a result, you can already upload you attachments to a folder simply by giving them a name like `attachments/image.png` for instance, but I agree that having a setting to do this by default may be helpful.

**Comment by zefhemel** [comment]
By the way your suggested syntax for relative paths (starting with `/`) is what I would actually expect for _absolute_ paths, wouldn't you agree?

**Comment by itsamemarkus** [comment]
> Note that SB technically doesn't have a real concept of folders, although anything with a `/` will make the translation to folders behind the scenes.

🤯



> By the way your suggested syntax for relative paths (starting with `/`) is what I would actually expect for _absolute_ paths, wouldn't you agree?

Yes, right. My mistake.

Relative path would maybe open a whole new jar of problems, when renaming pages they'd most likely also need to change.

---

When I think more about it: It might already be a good way to to store images in the root folder to have a good compatibility to other tools one might want to utilize and where the tool expect images to be in the root folder. 

Maybe the solution would then just be the *absolute* path for image reference so that you can preview images in Visual Studio Code Markdown preview and on Github.

**Comment by jwalzer** [comment]
I would rather oppose to storing everything in the root directory. My hope would rather be to make SB a bit more aware of "this hierarchy thing". Understanding `/` as a hierarchy delimiter and by surprise this hierarchy is also reflected in the storage backend as paths ;)

This would actually open the path for keeping different stuff contained in single directories, when indeed relative paths are respected and treated as such. Storing an article and images in the same subdirectory makes IMHO much more sense, and linking from the article to the image simply without the absolut path is intuitive.

There was a idea of "mounting" other instances/spaces into a directory of SB -- this would also be easier if simply a hierarchy would be recognized and relative links work like in the filesystem.

**Comment by julianfoad** [comment]
I see the issue like this: SB is not the master of my files, it is a tool that I point at some of my files. It needs to play nicely with how other tools interpret my files. The "SB space root" is not special to anything else outside SB. I have many existing markdown files in subfolders. Only some of my files were created through SB. The rest of them were created by other tools that know nothing about SB, and don't expect their contained links to refer to SB's space root. They expect their relative paths to be relative to their own location in the filesystem.

Specifically I'm sometimes opening my files in Markor or QOwnNotes, and there's one subfolder that I pass to Eleventy to publish on my web site. None of these know or respect SB's space root.

It seems to me that other tools generally interpret a relative path in a markdown file as relative to the folder in which the markdown file is found. That is also the most intuitive interpretation. Adopting that convention will avoid problems in switching between different tools on the same files, syncing or deploying the files to another place, such as using them as input to a static site generator, for example.

As for Wiki-style links, on the other hand, I suppose being relative to "the wiki root" is the more established practice. However, it's cumbersome repeating the `Sub/Folder/` prefix when working on a bunch of related files in a sub-folder, so I'm looking for a shortcut for that case too. I propose allowing `./` as a shortcut meaning "here", for this case.

## Proposal

1. when SB is interpreting a Markdown link or HTML link found in a file:

* a relative path (doesn't begin with '/' or scheme) is relative to the folder containing the file.
* a path beginning with '/' is relative to the SB space root.

2. when SB is interpreting a Wiki-style reference found in a file:

* an explicit './' relative path (begins with './') is relative to the folder containing the file.
* any other other Wiki-style path is relative to the SB space root.

## Examples

In the file `SPACE/Sub/Folder/file1.md`:

* `![](foo.png)` refers to `SPACE/Sub/Folder/foo.png`
* `[there](../bar/foo)` refers to `SPACE/Sub/bar/foo.png`
* `<a href="baz"> refers to `SPACE/Sub/Folder/baz`
* `<a href="./baz"> refers to `SPACE/Sub/Folder/baz`
* `<a href="/baz"> refers to `SPACE/baz`

and

* `[[Foo]]` refers to `SPACE/Foo.md`
* `[[./Foo]]` refers to `SPACE/Sub/Folder/Foo.md`

For backward compatibility we need an option to maintain the old behaviour. I propose this should be a per-space setting and be set to "new behaviour" (by default, unless user opts out) when initialising any new SB space, and default to "old behaviour" when encountering any existing SB space.

How much sense does this all make to you all?

**Comment by zefhemel** [comment]
It makes sense and seems to be right way to do it. My only concern is that we need "modes" for backwards compatibility...

**Comment by ryanwwest** [comment]
Has anyone requested the Obisidian-wikilink style of embedding images?

The main example of this is `![[Engelbart.jpg|100]]`, where the `|100` scales the width to 100 pixels maintaining aspect ratio. It's also path agnostic, just like Markdown files, so if `Engelbart.jpg` is in `media/` it still renders. This would be very nice as I'm using Silverbullet as a web solution for my Obsidian vault and no images being rendered is the biggest problem.

https://help.obsidian.md/Linking+notes+and+files/Embedding+files#Embed+an+image+in+a+note

**Comment by zefhemel** [comment]
Image URLs are now relative to the page's folder, unless their URL starts with a `/` then they're relative to the space root.

**Comment by julianfoad** [comment]
Awesome! Thanks!
