### ISSUE TITLE
Docs: Beginner friendly tutorial for building Plugs

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#367]
*We wrote about this topic on the Mattermost instance before.*

It would be good to have a beginner friendly tutorial for building Plugs. There is the [silverbullet-plug-template](https://github.com/silverbulletmd/silverbullet-plug-template) already. From my perspective this could be enriched with some simple examples on how to access and manipulate content in Silverbullet.

Maybe also as a video tutorial.

**Comment by zefhemel** [comment]
Done here: https://community.silverbullet.md/t/plug-development-for-beginners/49
