### ISSUE TITLE
Feature Request: Table of Contents

### ISSUE THREAD

**Issue by jwalzer** [silverbulletmd/silverbullet#375]
### description

I would like a plug that allows me to create a Table of Contents in my page. A special Tag `<!-- TOC --> .... <!-- EndToc -->` could be used to embed the current hierarchy. Of course a nice addon would be if a quick-command `/toc` would exist.

The ToC should be created from the headlines of the paragraph of the document. The titles should be a link to the headline it was generated from.

**Comment by zefhemel** [comment]
Duplicate of #263 could you add your suggestions there?
