### ISSUE TITLE
Search doesn't show exact matches on top and suggests creating existing pages (fuzzy finding algorithm)

### ISSUE THREAD

**Issue by itsamemarkus** [silverbulletmd/silverbullet#381]
I noticed two things regarding search (ctrl + k) 

## exact matches often don't show up at the top + not matching entries

![image](https://user-images.githubusercontent.com/34944988/226175663-4e5834f2-f5a6-4dc2-9b51-360c49215847.png)

My nested folders here are pretty messy, but some of the entries make no sense, because they don't contain "VLAN" in the title.

And I think the exact page "VLAN" in any folder should be near the top. Maybe if you type a string that is more than 3-4 characters long that matches a page exactly the entry is on top.

## Create page suggestion for existing pages

In this example the page `Software` exists but there is a suggestion to create a new one.

![image](https://user-images.githubusercontent.com/34944988/226175718-60555245-9eee-475b-8ecd-912836de6cdc.png)

(when you select the create page entry, it will just open the existing one)

**Comment by zefhemel** [comment]
I rewrote the logic for this, could you see if it's better now? For sure the issue of suggesting to create an existing page should be fixed.

**Comment by zefhemel** [comment]
Please reopen as desired
