### ISSUE TITLE
OR operator in query

### ISSUE THREAD

**Issue by siddhant3s** [silverbulletmd/silverbullet#384]
We have `AND` in SB's query language. However there is no `OR`.  Sometimes you want to write OR queries such as follow:
```
<!-- #query task where deadline <= '{{today}}' OR tags=["p0", "p1"] where done=false render [[template/task]] -->
```
This lists tasks which needs urgent attention: with high priority or with today's deadline.
The closest thing to OR we have right now is overloaded equality check when rhs is a list (as in the example above). The semantics of `tags=["p0", "p1"]` that it's equivalent to `tags="p0" OR tags="p1"`

Note that multiple `where` clauses are allowed, but they still `AND the results`

**Comment by zefhemel** [comment]
This is now implemented
