### ISSUE TITLE
optimize excessive markdown parsing

### ISSUE THREAD

**Issue by kjk** [silverbulletmd/silverbullet#395]
Multiple places do the sequence:
* `s = editor.getText()`
*  `tree = markdown.parseMarkdown(s)`

This happens e.g. every time you click inside editor. The text is re-parsed as markdown even if it didn't change.

This could be optimized by adding `editor.getParsedMarkdown()` that uses a cached tree.

The tree is invalidated when the text changes.

Places that could use this: `unfurlCommand()`, `parsePageCommand()`, `linkNavigate()`, `clickNavigate()`, `updateDirectivesOnPageCommand()`, `taskToggleAtPos()`, `taskToggleCommand()`, `postponeCommand()`.

**Comment by zefhemel** [comment]
Yep, this would be nice. So far my attitude has been "if it's not noticable, we'er still ok" but for sure this is not optimal as is.

**Comment by kjk** [comment]
For reference, this is how I implemented such improvement in my app: https://github.com/kjk/noted/commit/ca23c59c0c0ef93e5819a4c5519486b48e705b48

This can be easily adapted to SB but my code diverged enough that it would require a few minutes of adaptation.

**Comment by firasdib** [comment]
Perhaps an easy fix would be to just use a memoize library with cache size of 1? Given the same text is used as input, the cached result is returned, which will be invalidated as soon as the input to the function changes.
