### ISSUE TITLE
Docker images runs as different user suddenly (ID 1993)

### ISSUE THREAD

**Issue by sweisgerber** [silverbulletmd/silverbullet#402]
Based on the bugreport at: https://github.com/silverbulletmd/silverbullet/pull/400#issuecomment-1542226265

> Is it possible that switching the base image for deno also caused the user id to change?
> Because my instance started crashing on startup since the update from yesterday with
> 
> `Permission denied (os error 13): open '/space/data.db'`
> The files in my silverbullet volume all have the permissions 1000:1000.
> However, executing id inside the container now returns
> 
> `uid=1993(deno) gid=1993(deno) groups=1993(deno)`
> 
> So its uid 1993 now, not 1000 [as in the old base image](https://github.com/silverbulletmd/silverbullet/blob/c8d0b2df146742d7e07d04f6eb8e647ad939c301/Dockerfile#L33).
> 
> Backing up all files and destroying the volume fixes it, because the re-created volume automatically gets the new uid 1993.

**Comment by sweisgerber** [comment]
So, here's a fix:  https://github.com/silverbulletmd/silverbullet/pull/401
I'll test it a littlw more tomorrow, before handing it in.

**Comment by zefhemel** [comment]
Great, let me know when it's ready

**Comment by zefhemel** [comment]
Thanks for the quick fix! I'll close this then.
