### ISSUE TITLE
FR: About/Help/Version Info

### ISSUE THREAD

**Issue by ryanwwest** [silverbulletmd/silverbullet#408]
It would be nice to have a way to quickly determine the version number of a running instance of SilverBullet from the client side as well as at least get a link to getting started documentation or help, if not having that embedded directly in the app. I could see several variations of supporting this:
- a icon by the others that shows a list of options to reach settings/help/about/version info etc (maybe the easiest for less techy users, but more buttons is less minimalist)
- commands to display each of these

**Comment by zefhemel** [comment]
Absolutely, and easy to implement as well.

**Comment by ryanwwest** [comment]
Thanks!
