### ISSUE TITLE
Ability to exclude file/folder patterns from a space

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#409]
So that these files/folders will not appear in file listings, and will not be synced to the client.

Likely this can just be a `spaceIgnore` setting in `SETTINGS` supporting various patterns, similar to `.gitignore`.

Open question: should these files still be accessible via readFile()? Reason to support this would be to exclude large folders with lots of data and avoid syncing these everywhere, but still being able to link to them.

**Comment by ryanwwest** [comment]
Thanks for making this!

I don't know the specifics of readFile(), but I do think this could be a first step towards being able to access (and load) files from the remote server without preloading them / syncing them. As we discussed on Discord #general, while I haven't tested low-power devices yet with the new 0.3.1 sync-first model, I feel like it's somewhat likely that some of those could struggle so it might be nice to have an option where they can still access files you choose not to sync here (and potentially no files synced locally until you try to access the directly via click or loaded embed) and still work.

Even if we don't get there, you could imagine someone using this to just spaceIgnore the entire vault so we'd have to handle that behavior somehow in the meantime.

**Comment by zefhemel** [comment]
In 0.3.0 attachment links, e.g. `[my PDF](my-pdf.pdf)`) work by simply rewriting the link URL to have the `/.fs/` prefix, so e.g. `/.fs/my-pdf.pdf`. The service worker intercepts this URL pattern, and serves it locally, and if it doesn't find it gives you a 404. A simple tweak to make here would be to simply pass on the request to the server in case it doesn't find it locally, and if it finds the file there, it just serves it.

The result of this would be that you can link to files that match your `spaceIgnore` pattern, but they'd just always be served from the server and never cached locally. This seems a reasonable way of having the best of both worlds: the ability to exclude large files from sync but still be able to link to them.
