### ISSUE TITLE
Internal page link autocomplete doesn't place cursor after closing double brackets 

### ISSUE THREAD

**Issue by JordanPaoletti** [silverbulletmd/silverbullet#415]
Currently, when using autocomplete to fill in a page name (e.g. [[test page]]) the cursor is place before that ]] rather than after.
In short, using the snippets cursor placement syntax:
current behavior: [[test page|^|]]
desired behavior: [[test page]]|^|

**Comment by zefhemel** [comment]
While I’m not against changing this (would have to check how), but I would like to point out that if you’re using the syntax for wiki links with an alias: `[[other page|my alias]]` that is: if you intend to add a pipe and then an alias, you’d probably be confused with the proposed cursor behavior.

**Comment by JordanPaoletti** [comment]
I wasn't aware of the wikilink alias syntax, that's a very fair point.

I did look into what it would take to do this and the limitations/sandbox the workers have seems to make such a change non-trivial. Specifically, the inability the pass a function to the `apply` of `Completion` makes moving the cursor and other aspects rather difficult. Seems like it would require a fragile/hacky solution or a decent size expansion on the plugin autocomplete functionalities.

Given your point about the aliasing syntax and the non-trivial change required, I think it makes sense to close this issue as 'wont do'.
