### ISSUE TITLE
Adjust allowed character for tags

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#427]
I like using dashes for my tags, but they seem to terminate the tag in SilverBullet. You are also not able to use anything but a-z in tags, which can be a bit limiting.

I propose one of the following two regexes to create a good standard for tags:

```javascript
const asciiRegex = /#[a-z](?:[_-]?\w)+/gi;
const unicodeRegex = /#\p{Letter}(?:[_-]?[\p{Letter}\p{Number}])+/gu;
```

Fiddle here: https://regex101.com/r/ZfHg2s/1

**Comment by zefhemel** [comment]
What makes you believe you cannot use anything but a-z in tags? Here are some valid tags that seem to parse fine:

#hel-lo

#myt-ag/he-llo

What you cannot do is end your hash tag on a non-word (\w matching) character

The regex is here: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/core/core.plug.yaml#L8

**Comment by firasdib** [comment]
Ah, I see. My initial problem was, in that case, due to not ending the tag with a word character (`[a-zA-Z0-9_]`). If you're happy with how the regex is working, then feel free to close this.
