### ISSUE TITLE
Website overflows on smaller screens

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#429]
The website overflows beyond the max width of the screen in small screen scenarios (such as phones) due to no `width` being defined for the containing element.

Since `body` and `#sb-root` already have the correct `width: 100%;` set, you should just need to set the same rule on `#sb-editor` and `.cm-content` to propagate that change down.

Adding the following css rule resolves the issue for me:

```css
#sb-editor,
.cm-content {
  width: 100%;
} 
```

**Comment by zefhemel** [comment]
Yep, seems to work 👎
