### ISSUE TITLE
Documentation: data objects

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#43]
Fully undocumented, but implemented exist:

    ```data
    name: John
    age: 50
    ---
    name: Jane
    age: 53
    ```

Indexed and queryable across the entire space, e.g.:

```
<!-- #query data where age > 50 -->

<!-- /query -->
```

**Comment by sinansonmez** [comment]
General question about issues with documentation label: Where these documentation info should be placed? Under [website/feature](https://github.com/silverbulletmd/silverbullet/blob/main/website/🤯%20Features.md) ?

**Comment by zefhemel** [comment]
Good question. I didn't think this through fully yet. In case of functionality coming from plugs (like documented here), I think it would be best to add it to "plug docs" like I started one for query here: https://github.com/silverbulletmd/silverbullet/blob/main/website/%F0%9F%94%8C%20Query.md For others it may indeed be something under a page under `website` indeed, could be `feature` we can always move it later.

**Comment by davidbeijinho** [comment]
Hey just to add that I think data object can be very powerfull if we could have multiple in one page and "attached" to a node so we could have 2 paragraphs , in one page each representing a book, and add the values like we do in front matter

**Comment by lylebrown** [comment]
@davidbeijinho I actually just learned something that will work for my use case, and might help you out too -

when you add `data` to a page, it saves the page the data was placed on as a column. So the following query will filter out `data` to just what's on the current page:
`<!-- #query data where page = "{{page}}" -->`

I'm also considering adding a "type" property to all of my data, so I can have multiple types of data (with different columns/properties), and filter by that type.

**Comment by davidbeijinho** [comment]
I was trying to create an example page called books

---

Chamber of Secrets
```data
type: book
year: 1998
```

Philosopher's Stones
```data
type: book
year: 1997
```

  

|type|year|page |pos|
|----|----|-----|-|
|book|1997|Books|0|



But the query does not return the expected results, maybe because the data objects are not to be used like this @zefhemel

**Comment by zefhemel** [comment]
I'm fully open to changing data objects in whatever seems most useful. It's a feature I thought could be useful, without having a clear use case in mind (and in fact I'm not using it myself at the moment).

That said, this is how it works now:

* There is one global "data" source (`#query data`)
* You (should) be able to have as many `data` code blocks in a page as you like, each one becomes its own entry in the data "table"
* You can have multiple entries in a single data code block by separating them with `---`
* There are no ids for these, so you can only filter based on attributes
* There is a "magic" `page` attribute added to each data object that references the pages the data item was defined on

**Comment by zefhemel** [comment]
The entire implementation of this feature lives here: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/directive/data.ts

As usual the truth is in the source code

**Comment by zefhemel** [comment]
> I was trying to create an example page called books
> 
> Chamber of Secrets
> 
> ```
> type: book
> year: 1998
> ```
> 
> Philosopher's Stones
> 
> ```
> type: book
> year: 1997
> ```
> 
> type	year	page	pos
> book	1997	Books	0
> But the query does not return the expected results, maybe because the data objects are not to be used like this @zefhemel

Hmm, that seems odd. I'd expect there to be two data objects in this case. Not linked to the headline above it (data blocks don't have a sense of context) but at least I'd expect two entries, let me check.

**Comment by zefhemel** [comment]
Ok, I just fixed the issue of only supporting a single data block in a page. Multiple ones now longer override.
