### ISSUE TITLE
PWA has no icon

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#430]
Saved the app to my iPhone, where it has no icon. Perhaps it’s missing from the manifest file?

**Comment by zefhemel** [comment]
When you say "saved to my iPhone" what do you mean? I use it via the "Add to homescreen" option and get this on my Home Screen: 

![image](https://github.com/silverbulletmd/silverbullet/assets/59073/61415efa-214b-4d60-91ee-cd567380cd90)

**Comment by firasdib** [comment]
Yeah, that’s what I meant. 

Mine looks like this: 
![image](https://github.com/silverbulletmd/silverbullet/assets/1335165/39ed8e94-ebca-47ae-b87c-425f6dcc0e81)

**Comment by zefhemel** [comment]
Ok, that's odd. What is the URL you're adding here? Is it a `http` link by any chance instead of `https`? Because PWA manifests, service workers (and therefore fully offline capability) is only supported over https.

**Comment by firasdib** [comment]
It's a https site. I added it through the Chrome browser on iOS, not Safari if that matters.

**Comment by v411e** [comment]
I once had the same problem, because I had my keycloak configured as forward-auth proxy in place.  Solution was to create a bypass route without authentication for the manifest and some other endpoints. However I deactivated keycloak authentication completely for sb and now use only the integrated SB login screen which works perfectly fine.

**Comment by firasdib** [comment]
Ah, I have placed SB behind Authelia, so that could indeed be it. I will investigate!

**Comment by zefhemel** [comment]
Right. I think the manifest.json and icon assets cannot be behind authentication for this to work.

**Comment by firasdib** [comment]
Yes! I added a bypass rule for authelia for the png images and manifest file which resolved the issue. Thank you!Vänliga hälsningar / Best regards,Firas DibOn 26 Jun 2023, at 20:42, Zef Hemel ***@***.***> wrote:﻿
Right. I think the manifest.json and icon assets cannot be behind authentication for this to work.

**Comment by zefhemel** [comment]
I'll close this since it's not really an SB bug. If somebody wants to document their Authelia setup that'd be great though (which could document this aspect too).
