### ISSUE TITLE
"Open Page" (CTRL+K) fuzzy search unreliable

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#434]
I have a few documents where the title is a date, `2021-02-01`. I insert `2021` in the search field, but the top results are not relevant, I get `2022-02-10` and similar instead.

Bonus point: it would be nice if when you're at the top of the list, arrow up wraps down and vice versa.

**Comment by zefhemel** [comment]
I just switched over to fuse.js for fuzzy search, can you see if this is better now for you?

**Comment by firasdib** [comment]
Yes! LGTM!
