### ISSUE TITLE
Keyboard shortcut conflict: search and toggle fold (Ctrl-Shift-f)

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet#439]
The keyboard shortcut for #51 is the same as for the global search.

https://github.com/silverbulletmd/silverbullet/blob/629d25e0e33d47e043c725857879daa7adbac23e/plugs/core/core.plug.yaml#L390

https://github.com/silverbulletmd/silverbullet/blob/629d25e0e33d47e043c725857879daa7adbac23e/plugs/search/search.plug.yaml#L23

**Comment by zefhemel** [comment]
Yeah that's silly of me. Will correct.
