### ISSUE TITLE
Documentation: page links + positions

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#44]
Page links people probably know about, but there's also the `@Pos` notation for linking to specific positions inside of the page.

**Comment by tristansokol** [comment]
I was originally thinking https://silverbullet.md/%F0%9F%94%8C_Markdown might be a good spot, but it seems ilke that is possibly a misnamed plugin (and is instead focusing on publishing?) Perhaps a new page that might hold all documentation of what is possible is needed: https://www.markdownguide.org/basic-syntax/

**Comment by zefhemel** [comment]
This may be the best place for now: https://github.com/silverbulletmd/silverbullet/blob/main/website/Markdown.md
