### ISSUE TITLE
Failed to deploy to "Deno Deploy" due to missing module "hocuspocus/server@2.1.0"

### ISSUE THREAD

**Issue by kshehadeh** [silverbulletmd/silverbullet#440]
Trying to deploy using deno.com and deployments fail with: 
```Error The deployment failed: Module not found "npm:@hocuspocus/server@2.1.0".```

![image](https://github.com/silverbulletmd/silverbullet/assets/107061/1b569cfb-964d-42c4-8bb3-c623bff1ff2d)

Just wondering if anyone else has tried running silverbullet on deno deploy and if they had any issues.

**Comment by zefhemel** [comment]
This may be unblocked again soon with #449

**Comment by zefhemel** [comment]
This should now be unblocked. Haven't tested, but these instructions should work again: https://silverbullet.md/Install/Deno%20Deploy
