### ISSUE TITLE
Investigate if the service worker could be redone with WorkBox

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#443]
https://developer.chrome.com/docs/workbox/

**Comment by zefhemel** [comment]
https://github.com/googlecodelabs/workbox-indexeddb

**Comment by firasdib** [comment]
`generateSW` is the simplest way to get started: https://developer.chrome.com/docs/workbox/reference/workbox-build/#method-generateSW

You can define how runtime caching should work in that config, and what files to pre-cache. If the purpose of the SW is to serve things offline, then that should get you quite far.

**Comment by zefhemel** [comment]
We've seen no more issues with the service worker. Little reason to invest in this now.
