### ISSUE TITLE
Collab mode reloads page

### ISSUE THREAD

**Issue by firasdib** [silverbulletmd/silverbullet#447]
Collab mode reloads the page, which sometimes happens in the middle of an edit. This is a bit confusing, but beyond that, the entire page can be removed with ctrl+z which is a bit scary.

**Comment by zefhemel** [comment]
Related #449

**Comment by zefhemel** [comment]
Fixed as per https://github.com/silverbulletmd/silverbullet/commit/fb75ea1a65a1821aa4c7e5e656dd248e550e1bb6

Will be next release
