### ISSUE TITLE
Remove real-time collab altogether

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#449]
Real-time collab is a cool demo and a good feature to have for usage of a single SB instance with a team. However, it also results in a lot of complexity in the code and a lot of bugs and edge cases. Therefore I'm proposing to completely remove real-time collab from SB for now (of course it will still live on a branch). We can bring it back later when it becomes more of a need.

**Comment by ishehadeh** [comment]
I like the feature but it adds *a lot* of complexity to the core server.

I'm just on a single user setup, though, so my opinion isn't that important. The main benefit I've gotten out of it is when it showed me that I had 2 sessions open (phone and laptop, 2 tabs, etc.). Which was nice, but that could be achieved with a much simpler presence ping.

**Comment by zefhemel** [comment]
Since this also drops the reliance on using websockets, this means SB could be deployed on Deno Deploy again: https://silverbullet.md/Install/Deno%20Deploy
