### ISSUE TITLE
Use reserved domain for the example URL on page "Live Preview"

### ISSUE THREAD

**Issue by rybak** [silverbulletmd/silverbullet#459]
Even though `.url` isn't a top-level domain yet, it can be potentially dangerous to have a random URL as an example that isn't [reserved for examples](https://en.wikipedia.org/wiki/example.org).

I recommend replacing `[this is a link](https://to.some.url)` with `[this is a link](https://example.org)` on the page [Live Preview](https://silverbullet.md/Live%20Preview).

**Comment by zefhemel** [comment]
Yep, thanks, fixed!
