### ISSUE TITLE
Tasks Plug

### ISSUE THREAD

**Issue by itsallyours** [silverbulletmd/silverbullet#464]
In https://silverbullet.md/%F0%9F%94%8C%20Tasks, it mentions the ability to postpone tasks.  I do not see that command.  Nor do I see the ability to add due dates, etc.

Do I need to manually add the Tasks plug?  If so, what is the url for the plug?

**Comment by ishehadeh** [comment]
Some commands are only available in certain contexts (i.e. parts of the document).
For postpone, your cursor must be over the task due date:

```markdown
- [ ] do the dishes 📅 2023-07-12
             cursor goes here ^
```

I don't *think* there's a command to add a due date. Due dates are just the calendar emoji followed by a YYYY-MM-DD date. The `/today` and `/tomorrow` slash commands will insert dates in the correct format.

**Comment by itsallyours** [comment]
thank for the explanation.
