### ISSUE TITLE
mount.plug.json ignored

### ISSUE THREAD

**Issue by Melkor333** [silverbulletmd/silverbullet#476]
Heya

I tried to install [silverbullet-mount](https://github.com/silverbulletmd/silverbullet-mount) but it just does nothing. I assume it has to do with the ending being `.json`, not `.js`. Using the following in `PLUGS` does just nothing
```yml
- github:silverbulletmd/silverbullet-mount/mount.plug.json
- https://raw.githubusercontent.com/silverbulletmd/silverbullet-mount/main/mount.plug.json
```
When I change it to the following, I (obviously) get `Error updating plugs: Could not fetch plug code from https://raw.githubusercontent.com/silverbulletmd/silverbullet-mount/main/mount.plug.js`

```yml
- github:silverbulletmd/silverbullet-mount/mount.plug.js
```

Even when I add another plug I can see that it tries to load the second PLUG (but still ignores the mount plug):

```yaml
- https://raw.githubusercontent.com/silverbulletmd/silverbullet-mount/main/mount.plug.json
- github:silverbulletmd/silverbullet-github/github.plug.js
```

```
Saving file PLUGS.md
Proxying fetch request to https://raw.githubusercontent.com/silverbulletmd/silverbullet-github/main/github.plug.js
```

Do I something wrong or is this actually a bug?

**Comment by zefhemel** [comment]
Yeah that's a legacy repo and I should remove it. I'm still playing with different ways of achieving something similar.

**Comment by zefhemel** [comment]
Btw, to really answer your question: until a few versions back all plugs had a `.json` extension. That has changed as of 0.3.0 (from the top of my head), they’re now bundled as single `.js` bundles. In principle all you needed to do is recompile the plug to produce a `.js` version. However in the case of silverbullet-mount there were other changes that would break it. I’ll mark the repo as archived.

Out of interest, what was your use case for it? So I can use it for future development.

**Comment by Melkor333** [comment]
Oh ok, thanks for your quick response! My reason:
Apart from my serverinstance I want to use it locally. My company has a big Nextcloud share with a lot of customerdata. For certain customers we store meeting minutes, etc. in Markdown files. I'd like to be able to "import" such a customer folder to access these files (while silverbullet hopefully ignores all other non ".md" files). That would allow me to use silverbullet as my main markdown editor which would be hella fancy!! :)

Btw. here are some more things I noticed. If you want I can create separate Issues:

I just lost a file content when I wanted to rename it. I first accidentally changed it to `'filename` and immediately changed it to `filename` afterwards, maybe some concurrency problem there. I can try to reproduce it if you like.

On mobile it seems to register touches on "buttondown". That makes it quite hard to edit a link without visiting it. Only a bit too close to a link and it is opened. Maybe introducing a small timeout or doubletap (and e.g. long tap to select) for mobile might make sense.

The docker container "forces" UID 1000 because of some deno stuff happening on startup. would be nice if that wasn't required (and I could run it with user `www-data`). Maybe something for when there is a single binary? :)
You need more publicity :p

Anyway, lot's of critics but the tool is sooooo nice!!! I actually searched for about two hours to find it again now that I can use it. I saw a reddit post long ago and had to dig it up. :D Almost settled with [feather](https://feather.wiki/) because I started to believe I hallucinated about that live update markdownwiki thing! :)
