### ISSUE TITLE
Romanian character not registering

### ISSUE THREAD

**Issue by clmbmb** [silverbulletmd/silverbullet#478]
Running Silverbullet 0.3.5 in docker.

Writing Romanian character â doesn't work at all and only in Silverbullet. I tried it in Firefox, Microsoft Edge and Safari - I'm runnig on macOS Ventura 13.4.1.

The keyboard layout is Romanian Programmers (https://github.com/calini/romanian-programmers-macos) and here's the output from the KeyCodes app:

```
Start typing…

Modifier Change
	Keys:		⌥
	Modifiers:	524608 / 0x80140 ⓘ

Key Down
	Characters:	â
	Unicode:		226 / 0xe2
	Keys:		⌥Q
	Key Code:	12 / 0xc
	Modifiers:	524608 / 0x80140 ⓘ

Key Up
	Characters:	â
	Unicode:		226 / 0xe2
	Keys:		⌥Q
	Key Code:	12 / 0xc
	Modifiers:	524608 / 0x80140 ⓘ

Modifier Change
	Modifiers:	256 / 0x100 ⓘ
```

This was working before (at least one week ago), but I'm not sure about Silverbullet's version I was running, as I have an automated upgrade setup for docker.

**Comment by zefhemel** [comment]
So if I’m reading this correctly, you’re effectively typing Option-q on your keyboard? That would indeed conflict with `Directives: Update` but it’s been like that for over a year, so I’m confused why this would become a problem now…

**Comment by clmbmb** [comment]
> So if I’m reading this correctly, you’re effectively typing Option-q on your keyboard? That would indeed conflict with `Directives: Update` but it’s been like that for over a year, so I’m confused why this would become a problem now…

Hmmm. Yes, that's the case. And it's possible I mistook my usage of Silverbullet on my personal laptop running Linux.

So în this case is there a way to change the shortcut for `Directives: Update`?

**Comment by zefhemel** [comment]
Not yet, but I just bumped the priority of #193

**Comment by clmbmb** [comment]
This is great. Thanks for looking into it.
