### ISSUE TITLE
Backlinks could include a snippet of context

### ISSUE THREAD

**Issue by johnlunney** [silverbulletmd/silverbullet#484]
In Obsidian and especially Logseq, backlinks (both linked and unlinked mentions) are surfaced with a snippet of text around the link point.
This helps you bring together ideas in context, and eventually pull the text in to where you're writing.

I guess this would need an entry in the data-structure in [page_links.ts](https://github.com/silverbulletmd/silverbullet/blob/main/plugs/core/page_links.ts) which could then be used by the Backlinks plug.

**Comment by zefhemel** [comment]
Yep sounds useful!

**Comment by v411e** [comment]
This might be related to #457

**Comment by johnlunney** [comment]
> This might be related to #457

Could be a similar API call...
Although I imagine the backlink wants the snippet around the link or word, where your #457 wants some sort of summary, like the first paragraph does for Wikipedia.

**Comment by zefhemel** [comment]
As of 0.5.0 this has been implemented
