### ISSUE TITLE
Refresh current page note

### ISSUE THREAD

**Issue by uGeek** [silverbulletmd/silverbullet#489]
I am using a remote cloud set up with rclone as storage for the notes. The service works perfectly. But when I edit a note with another application either from the terminal or remotely, silverbullet does not update the note showing the version of its first scan. This is a problem because if I don't notice, if I modify the note with silverbullet, as it is not updated in silverbullet, I lose the information that was modified in another application.

Is there a possibility that when I am previewing a note with silverbullet, I can run a command to refresh that note and show the remote editor version?

Add a command to update or refresh the current note or that every time you enter a note, silverbullet updates the note you open. Synchronising all notes at startup causes this problem of not refreshing already synchronised notes.

With other services or applications this does not happen, because it does not do a full synchronisation via PWA.

It is also possible to disable the synchronisation of all notes and load the note when it is opened. This would avoid these problems.

**Comment by zefhemel** [comment]
This shouldn't be the case. It's already happening that if you switch to a page, it immediately syncs that page, after that it's only every 20s or so. Could you try the following:

1. Open your browser's developer JavaScript console
2. Make a change on the server side to a page
3. Switch to that page in the client -> this should pull the new version within a second (if not, please send a screenshot of your JS console outpout)

You can already explicitly trigger a full sync cycle with the `Sync: Now` command which should always work.

**Comment by uGeek** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/27757712/43276816-ef5d-4da5-ab39-d100c874305b)

It seems to be due to the fact that I don't have the https web service open.


**When I click on sync now, in the console it does indicate that it is synchronising, but it does not refresh the page.**

Anyway, I just opened the service with caddy and https certificates, I don't get that error message anymore, but it doesn't refresh either.

I have set up the service on a Raspberry with ARM64 and I have used Firefox and Brave, in both cases the same thing happens. It also happens to me on my mobile


it seems that the mistake is here. This is what the docker logs show

![image](https://github.com/silverbulletmd/silverbullet/assets/27757712/9562ad2c-7e6b-484b-bd71-531253c30cfd)

**Comment by uGeek** [comment]
the `Sync: Now` command, synchronises the current note or synchronises all notes.

**Comment by zefhemel** [comment]
All

**Comment by uGeek** [comment]
I have already solved it. It's not a SilverBullet problem. Silverbullet works great.

From what I have analysed, it is very important for silverbullet to analyse the creation and edit date of the files. When mounting a folder with rclone with the notes from a server, there is an option I had disabled "--no-modtime" and this causes SilverBullet not to refresh the pages.

This does not happen with other applications and note services that I have used in parallel to SilverBullet, but for SilverBullet it is important.

Now it refreshes instantly and resynchronises the cloud in a very fast way.

Anyway.... When it resyncs, does it only sync the edited note or all notes?

I say this because of the data consumption on mobile devices.

Thank you very much for replying and sorry for taking so much time. I attach the data of the assembly of the notes in a cloud and mounted with rclone that work perfect, as if they were in local:


```
      - "mount"
      - "webdav:"
      - "/data"
      - "--allow-non-empty"
      - "--allow-other"
      - "--vfs-cache-mode"
      - "full"
      - "--vfs-read-ahead"
      - "16M"
      - "--vfs-fast-fingerprint"
      - "--transfers"
      - "16"
      - "--no-checksum"
      - "--buffer-size"
      - "64M"
      - "--ignore-existing"
      - "--dir-cache-time"
      - "60"
```

**Comment by zefhemel** [comment]
Ok great to hear! The "Sync: Now" command (which runs every 20s or so automatically by the way) syncs all files, but only those with a modified time stamp (as you just discovered) which should usually be very few.
