### ISSUE TITLE
Renaming page command deletes page if default prompt input is not changed

### ISSUE THREAD

**Issue by m1lt0n** [silverbulletmd/silverbullet#49]
While trying to rename a page, if the user hits "OK" in the prompt and submits the same value (since the prompt has as its default the current page name), the page is deleted.

Suggested change: check for old vs new value and make the rename a no-op in case they are equal (same behavior as when newName is falsy).

I've prepared a small PR for this https://github.com/silverbulletmd/silverbullet/pull/50

**Comment by zefhemel** [comment]
Closing after merging #50
