### ISSUE TITLE
Import file using alternative method

### ISSUE THREAD

**Issue by esodigoyo** [silverbulletmd/silverbullet#492]
Files are imported through drag and drop.
On mobile android this is not possible.
Using a command to import would be very convenient.

**Comment by gharden91** [comment]
Second adding this feature. A slash or palatte command to invoke the insert model would be quite useful.

**Comment by zefhemel** [comment]
Note to
self: https://web.dev/media-capturing-images/

**Comment by zefhemel** [comment]
This is currently in progress here: https://github.com/silverbulletmd/silverbullet/pull/571

**Comment by zefhemel** [comment]
Implemented as a `File: Upload` command since [ae9c8dc](https://github.com/silverbulletmd/silverbullet/commit/ae9c8dcb4cf53ea0966615e4942322f323ffb3b2)
