### ISSUE TITLE
Add "resize (scale) image" eg. ![](image.jpg | 100x100)

### ISSUE THREAD

**Issue by ArgiSanchez** [silverbulletmd/silverbullet#493]
Add de posibility to scale images in front-end

**Comment by hugojosefson** [comment]
Related comment regarding scaling: https://github.com/silverbulletmd/silverbullet/issues/363#issuecomment-1556419638

**Comment by smcnabb1** [comment]
+1
I have seen other markdown implementations use ![alt text | resolution](filename.png)

**Comment by fflorent** [comment]
I wish to take this one. I am about to implement this markdown extension, if that's OK:
```md
![ALT_TEXT](IMAGE_SRC =WIDTHxHEIGHT)
```
