### ISSUE TITLE
query page, path missing

### ISSUE THREAD

**Issue by conrad82** [silverbulletmd/silverbullet#494]
When I  query page with template `* [[{{name}}]]` the path is not shown as expected, however using template `[[{{name}}|{{name}}]]` works. Is this intended behavior?

![image](https://github.com/silverbulletmd/silverbullet/assets/17353007/1254a2a7-8670-44d5-ae33-dddcf18722be)

**Comment by zefhemel** [comment]
Yes, this is expected behavior and it's not specific to templates. Any page link only shows the last bit of the path in live preview (this is to avoid overly long link names). The way around it is indeed using the alias syntax as you show.
