### ISSUE TITLE
Multi-session support

### ISSUE THREAD

**Issue by uGeek** [silverbulletmd/silverbullet#497]
I have set up 2 SilverBullet sessions for two users on my Raspberry Pi. I have logged in with the same browser from my local network, for example service 1 by IP= 192.168.1.1.100:100 and service 2 on 192.168.1.1.100:101.  I imagine that with the PWA as all the notes are downloaded in the browser with the name of SilverBullet and from the same IP, when you enter service 1, you enter without problems, but if you put the address of service 2, it makes you leave service 1 to log in service 2, but it does not allow to keep in the same browser the two services open simultaneously.

If that were the case, perhaps customizing the name of the service for each user would solve the problem. 

I wanted to take this opportunity to congratulate you for SilverBullet.md, it is the best application - note service I have ever used, using it makes you feel productive.

thank you very much

**Comment by zefhemel** [comment]
Strange, I thought this worked. Maybe I have to change how the cookies are set...

**Comment by zefhemel** [comment]
Ok this is happening because cookies are per domain and that ignores the port: https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific

Thinking of a good solution for this...

**Comment by zefhemel** [comment]
Ok fixed this by putting the hostname + port in the cookie name. Will be part of the next release (0.3.11) or you can get it now from the `zefhemel/silverbullet:edge` docker image.

**Comment by uGeek** [comment]
Good idea to use the port in the cookie. Thank you so much
