### ISSUE TITLE
Markdown relative paths not compatible with other MD programs

### ISSUE THREAD

**Issue by conrad82** [silverbulletmd/silverbullet#498]
If i put a note with an image in the root folder of silverbullet, a markdown program can correctly show images. However, in subfolders it is not compatible with other markdown programs. I used MarkText in the below screenshots

Silverbullet should respect relative paths when adding and showing images.
I noticed this discrepancy when I imported my recipes (in .md), and the images did not show as expected.

Picture and .md placed in root folder:
![image](https://github.com/silverbulletmd/silverbullet/assets/17353007/b890406b-e31f-4fc8-a9ea-ea580a60b996)

Picture and .md placed in subfolder: (edit: Picture _should have_ been placed in subfolder, but silverbullet placed it in root)
![image](https://github.com/silverbulletmd/silverbullet/assets/17353007/59576924-cd63-4f68-b52a-3486170bbcc9)

**Comment by zefhemel** [comment]
Agreed. I'll change this.

**Comment by CyberPenguin** [comment]
Would love to see this! Its the last thing stopping me moving from Logseq for my use case.

**Comment by hugojosefson** [comment]
Duplicate, or related: #363

**Comment by hugojosefson** [comment]
Fixed, thanks to https://github.com/silverbulletmd/silverbullet/issues/363#issuecomment-1863079286 ?

**Comment by zefhemel** [comment]
Yep! :)
