### ISSUE TITLE
Handlebar JS don't work on evaluating if expressions

### ISSUE THREAD

**Issue by siddhant3s** [silverbulletmd/silverbullet#501]
If we are on a `template/task`, we can't do:
```
{{#if @index == 0}} First Task {{/if}}
```
GIves the following parse error:
```
Error running command: Parse error on line 2: ...}}{{#unless @index == 1}}{{/unless}}* [ ----------------------^ Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS'
```

Similarly if try to use any condition on if data, we get the same error:
```
{{#if deadline==@today}}URGENT{{/if}}
```
```
Error running command: Parse error on line 2: .../if}}{{#if deadline==@today}}URGENT{{/if -----------------------^ Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS'
```

**Comment by zefhemel** [comment]
I just checked the Handlebars docs, and it seems that `@index == 0` is not a valid Handebars expression. It looks like we may have to define some built-in helpers to do things like equality checks: https://stackoverflow.com/questions/34252817/handlebarsjs-check-if-a-string-is-equal-to-a-value

I can do that though, not hard.

**Comment by zefhemel** [comment]
Maybe even using this: https://github.com/helpers/handlebars-helpers#eq
