### ISSUE TITLE
`silverbullet upgrade` stuck

### ISSUE THREAD

**Issue by darcien** [silverbulletmd/silverbullet#505]
## Issue

Tried upgrading as usual, it didn't work today.
CLI stuck doing nothing:
```
❯ silverbullet upgrade          
Now going to attempt an upgrade...
So, that's done. Now let's see if this actually did anything...
^C
```

I checked what the upgrade command is doing after logging that line, saw this code:
https://github.com/silverbulletmd/silverbullet/blob/136682ebd3c133ca01c4f26dd9291b8cde31d492/cmd/upgrade.ts#L17-L20

So I tried running it manually and got the same issue, stuck doing nothing:
```
❯ deno run -A --unstable https://get.silverbullet.md/ version
0.3.10
^C
```

Running the `version` command directly does terminate, not stuck:
```
❯ silverbullet version
0.3.10
```

I tried digging deeper into this, but couldn't pinpoint the cause.
From attaching debugger to `version` command, after logging the version
and `execute()` from `cliffy` completed, debugger just loops around executing `eventLoopTick`
in `deno_core`

src: https://github.com/denoland/deno_core/blob/93f62f0fa2b58d781c3bd80a5abb2d94de26233b/core/01_core.js#L169

<details><summary>Debugger config</summary>

Used these debugger config:
`.vscode/launch.json`
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "run version",
      "type": "node",
      "program": "${workspaceFolder}/silverbullet.ts",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "/Users/darcien/.deno/bin/deno",
      "runtimeArgs": [
        "run",
        "--unstable",
        "--allow-all",
        "--inspect-wait"
      ],
      "args": [
        "version"
      ],
      "attachSimplePort": 9229
    }
  ]
}

```

</details>

## Versions

```
❯ silverbullet version
0.3.10
```

```
❯ deno --version
deno 1.36.0 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.12
typescript 5.1.6
```

Also tried on different machine, same issue:
```
❯ deno --version
deno 1.34.3 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

**Comment by zefhemel** [comment]
Could you try running:

```
deno run -A --unstable --reload https://get.silverbullet.md/ version
```

This should perform the upgrade as well (note the `--reload` flag)

**Comment by darcien** [comment]
> Could you try running:
> 
> ```
> deno run -A --unstable --reload https://get.silverbullet.md/ version
> ```
> 
> This should perform the upgrade as well (note the `--reload` flag)

I tried running with `--reload`, no effect.

```
❯ deno run -A --unstable --reload https://get.silverbullet.md/ version
0.3.10
^C
```

Do you suspect this is network/cache related?

**Comment by zefhemel** [comment]
Err isn't the "problem" that 0.3.10 is the latest release and you have it already? 😛

**Comment by darcien** [comment]
> Err isn't the "problem" that 0.3.10 is the latest release and you have it already? 😛
> 
> Edit: oh wait it gets stuck, that is weird.

It should still exit the process after logging no update detected right?

Do you also get stuck when running version or it's just my setup?
```
deno run -A --unstable --reload https://get.silverbullet.md/ version
```

**Comment by zefhemel** [comment]
Ok, I found and fixed the issue. Will be fixed in the new version (it won't hang). When you run `silverbullet upgrade` the upgrade does actually happen, it just doesn't exit, so you can just Ctr-c for now. Thanks for reporting!

**Comment by darcien** [comment]
Wow, thanks @zefhemel, you're awesome!
