### ISSUE TITLE
Shell Syscall Sandboxing

### ISSUE THREAD

**Issue by orausch** [silverbulletmd/silverbullet#506]
Is the [shell syscall ](https://github.com/silverbulletmd/silverbullet/blob/main/plugos/syscalls/shell.deno.ts) sandboxed in any way?

It doesn't look like it to me, which makes me a bit nervous. If not, it seems like any user could just execute arbitrary code on the server?

**Comment by zefhemel** [comment]
It is indeed not sandboxed any way (except for however you sandbox SB on the server itself, such as a docker container). If you don't run SB in a docker container this is potentially dangerous. One quick win here would be to disable shell calls by default and enable it only when explicitly enabled with a flag. Thoughts?

**Comment by orausch** [comment]
Disabing sounds good. Something more advanced could involve storing a list of approved commands somewhere (where approving some requires some sort of server-side input)
