### ISSUE TITLE
Text folding of the section under heading

### ISSUE THREAD

**Issue by radosny** [silverbulletmd/silverbullet#51]
I've noticed that there is missing one feature that I got used to while I was using different notes taking apps, which is text folding of a paragraph under the heading group.

It could be useful while you are presenting something and you don't want to share details of all the topics and keep the audience focused on the expanded part.

For example:
- after folding it
<img width="402" alt="image" src="https://user-images.githubusercontent.com/3193744/181108957-5efc7f07-3a35-4478-874a-95bfb26c9e44.png">

- before folding the paragraph under the heading
<img width="363" alt="image" src="https://user-images.githubusercontent.com/3193744/181109066-e3cc06b5-4d49-4986-860f-1863a0b54ac4.png">

It could also support nesting ➰ 😸

**Comment by zefhemel** [comment]
Yeah, this is something that would be nice to have. Codemirror has support for this, we just have to figure out how to configure it. It’s documented here: https://codemirror.net/docs/ref/ (the `codeFolding` and `foldGutter` extension). Not sure if this will automagically will work with its markdown mode. Will require some research.

**Comment by zefhemel** [comment]
Implemented with https://github.com/silverbulletmd/silverbullet/commit/1b922791f35563b57c776f0a463208395acff7e2

Not much UI for it yet, but folding works

**Comment by ryanwwest** [comment]
This is super nice! Could there be any consideration for a 'toggle' type fold/unfold command as well, since it seems each command can only be run once and then the opposite command has to undo it?

**Comment by zefhemel** [comment]
@ryanwwest just added it: https://github.com/silverbulletmd/silverbullet/commit/eefd8a5245da674ffcf35ce63b3ec3f7dbb55a9e

**Comment by ryanwwest** [comment]
So fast, thank you
