### ISSUE TITLE
[Potential Bug?] Test failed during AUR package installation

### ISSUE THREAD

**Issue by showgood163** [silverbulletmd/silverbullet#514]
Hi there!

I'm using arch linux (both amd64 and arm64) and installing silverbullet using this [aur](https://aur.archlinux.org/packages/silverbullet) (EDIT: the package is based on tag v0.3.11).
The problem is that, for both platforms, after the package is built, the log shows that 1 of 37 tests failed.

More relevant info:
All packages are up to date.
On amd64 I'm using [deno 1.36.4-1](https://archlinux.org/packages/extra/x86_64/deno/).
On arm64 I'm using [deno-arm64 1.36.3](https://github.com/LukeChannings/deno-arm64/releases).
(EDIT: My amd64 VM has 1GB ram, in which about 600MB is avaliable for package installation (deno task build/bundle/test).)

The error log on amd64 platform is as follows.

```
 ERRORS

Run a plugos endpoint server => ./plugos/hooks/endpoint.test.ts:10:6
error: TypeError: error sending request for url (http://localhost:3123/_/test/?name=Pete): error trying to connect: tcp connect error: Connection refused (os error 111)
  const res = await fetch(`http://localhost:${port}/_/test/?name=Pete`);
              ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:501:7)
    at async file:///tmp/makepkg/silverbullet/src/silverbullet-0.3.11/plugos/hooks/endpoint.test.ts:32:15

 FAILURES

Run a plugos endpoint server => ./plugos/hooks/endpoint.test.ts:10:6

FAILED | 36 passed | 1 failed (16s)
```

The error log on arm64 platform is as follows.

```
 ERRORS

Test FS operations => ./plugos/syscalls/fs.deno.test.ts:8:6
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://deno.land/std@0.165.0/testing/asserts.ts:139:11)
    at file:///home/asteria/.cache/pikaur/build/silverbullet/src/silverbullet-0.3.11/plugos/syscalls/fs.deno.test.ts:18:3

 FAILURES

Test FS operations => ./plugos/syscalls/fs.deno.test.ts:8:6

FAILED | 36 passed | 1 failed (46s)
```

**Comment by zefhemel** [comment]
https://github.com/silverbulletmd/silverbullet/commit/b936a435abbc3a911aa412cb1c75e4a0eff40596 here it was fixed.

**Comment by showgood163** [comment]
> Is this based on the latest default branch? There was a brief moment where this test failed but I think it should be succeeding again now.

The package is based on the tag v0.3.11.

**Comment by showgood163** [comment]
Here is a log of using commit [b936a4](https://github.com/silverbulletmd/silverbullet/commit/b936a435abbc3a911aa412cb1c75e4a0eff40596).

[3.log](https://github.com/silverbulletmd/silverbullet/files/12533918/3.log)

**Comment by showgood163** [comment]
For reference, I cloned this repo and manually run these commands:
`deno task build`
`deno task bundle`
`deno task test`

Here is the log of tag v0.3.11: [git-1.log](https://github.com/silverbulletmd/silverbullet/files/12534336/git-1.log)

Here is the log of commit [b936a4](https://github.com/silverbulletmd/silverbullet/commit/b936a435abbc3a911aa412cb1c75e4a0eff40596): [git-2.log](https://github.com/silverbulletmd/silverbullet/files/12534353/git-2.log). 
This is strange because I see no failed test but the shell shows that `deno task test` returned `1` instead of `0`.

**Comment by showgood163** [comment]
I've cloned this repo on my arm64 device and manually built and tested this package.
No errors reported during the tests for both tag v0.3.11 and commit [b936a4](https://github.com/silverbulletmd/silverbullet/commit/b936a435abbc3a911aa412cb1c75e4a0eff40596).

In the end, I decided to ignore test errors and simply install this package manually.

**Comment by zefhemel** [comment]
I just released 0.4.0, could you check if is all ok with that?

**Comment by showgood163** [comment]
Here are two logs from my x64 VM.

[x64-aur.txt](https://github.com/silverbulletmd/silverbullet/files/12568196/x64-aur.txt), 43 tests passed and 2 failed

[x64-git.txt](https://github.com/silverbulletmd/silverbullet/files/12568197/x64-git.txt), `deno task test` simply returned 1.

**Comment by zefhemel** [comment]
I'm not familiar with AUR or how it works (or what it is exactly), is it possible that it's somehow locking down the build environment? Perhaps it blocks opening local ports (this endpoint test is the only test that asctually spawns a web server I think)

**Comment by showgood163** [comment]
Arch User Repositories (AURs) are user-uploded unofficial software packages for arch linux.

Building packages for arch linux [requires a clean chroot environment](https://wiki.archlinux.org/title/Creating_packages#Set_up_clean_chroot).

I do not know how to check whether this chroot env is bloking local ports.
Can you show me how to do it?

P.S. I'm using [pikaur](https://github.com/actionless/pikaur) to manage these AUR packages.
