### ISSUE TITLE
fs test fails when silverbullet is already under a hidden directory

### ISSUE THREAD

**Issue by rnbguy** [silverbulletmd/silverbullet#518]
I don't know if this is intended. If the Silverbullet is repo already under a hidden directory, e.g. `/home/user/.repos/silverbullet`, the following test will fail.

https://github.com/silverbulletmd/silverbullet/blob/7af98e7c7bc9464cdd747a30a13ad9e809c292ce/plugos/syscalls/fs.deno.test.ts#L12-L18

It is because `skip` pattern in the following doesn't allow `/.` anywhere in the absolute path. In my example, it matches with `.../user/.repos/...` and stops walking.

https://github.com/silverbulletmd/silverbullet/blob/7af98e7c7bc9464cdd747a30a13ad9e809c292ce/plugos/syscalls/fs.deno.ts#L76-L81

Maybe relax the regex with `^.*\/\.[^/]+$` to skip only the current directories whose names start with a dot.

**Comment by pcaro90** [comment]
This is also an issue when building for Arch Linux, form AUR, with `yay` (which uses `~/.cache/yay` as build directory).

**Comment by zefhemel** [comment]
I had already fixed this elsewhere, copied the fix
