### ISSUE TITLE
Order of notes

### ISSUE THREAD

**Issue by uGeek** [silverbulletmd/silverbullet#525]
In version 0.4.0, I had this code that ordered my notes by edit date, but now they come out ordered alphabetically. With the update to version 0.5.0, it no longer works. How should the code be changed so that it comes out ordered by edit date again?

```
<!-- #query page   where name != "{{page}}"   order by dateModified desc   limit 20   render [[templete/pagenodate]] -->
```

**Comment by uGeek** [comment]
Sorry, it was a problem in version 0.5.0, in version 0.5.1 it is solved

**Comment by zefhemel** [comment]
Yeah I noticed this bug myself and fixed it, will close this issue.
