### ISSUE TITLE
Different formatting in live query/template than in normal text

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet#530]
Hi, I wanted to migrate from an old query to the new live query and noticed some formatting issues.
New lines and leading spaces / indents are stripped of for example. Is this intended behavior?

![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/f283a0ef-23d2-40d3-b894-1c18975a3e2e)

`template/service`
```
### [[{{name}}]]
  Url: {{url}}
  Server: {{server}}
  📅 {{last_updated}} - [Release notes]({{release_notes_url}})
```

`services`
````
## Live query
```query
page where name =~ /services\/exam/ and server = "Bach" and active = true order by name asc render [[template/service]] 
```
## Normal query
<!-- #query page where name =~ /services\/ex/ and server = "Bach" and active = true order by name asc render [[template/service]] -->
### [[services/example]]
  Url: example.com
  Server: Bach
  📅 2023-10-12 - [Release notes](github.com)
<!-- /query -->
````

The list representation is also not consistent over normal lists and live template lists
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/a53d13b3-6459-4c05-8370-1331c03f78c5)

**Comment by zefhemel** [comment]
This is not intended. I’ll fix these, let me know if you have more things you see breaking this way.

**Comment by zefhemel** [comment]
Also to look at: newline behavior, here's a discord discussion: https://discord.com/channels/1028543811191836782/1160319256706158623/1160319596365107292

**Comment by v411e** [comment]
The buttons of the live template do not respect dark mode
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/29ed8ecd-51af-439f-9eb6-c200ef630000)

**Comment by msolo** [comment]
It looks like CSS specified in STYLES is not correctly applied inside Live Query iframes. 

For instance, specifying `--editor-font` doesn't work inside  the Live Query iframe, but works correctly on the parent frame.

There is no #sb-root element inside the iframe, but either of these two rules work for the rest of the page elements.
```
#sb-main {
   --editor-font: "Arial" !important;
}

html {
   --editor-font: "Arial" !important;
}
```

**Comment by zefhemel** [comment]
Ok, I addressed all these issues except @msolo's one, for which I created a separate issue #541 . Closing this now, please create a new issue when you find more.
