### ISSUE TITLE
FR: Editable Transclusions

### ISSUE THREAD

**Issue by ryanwwest** [silverbulletmd/silverbullet#533]
A transclusion displays a piece of a different Markdown file (whole file, heading+contents, specific paragraph, or bullet point/top paragraph with a list directly beneath, + sub bullet points) in a different file by appending a `!` to the link format like `![[another_note#note heading]]`. https://medium.com/workings/true-transclusion-in-obsidian-6d2e05235bd gives more examples.

I thought that this was part of SilverBullet but I must be misremembering as I can't get it to work now. Is this the case? If so, I'm curious if there's any interest for it. It's a core feature of Obsidian and other Markdown apps and very helpful.

However, this FR isn't just a request for viewing them, but actually editing the transclusions directly in the other files in which they're displayed. See https://forum.obsidian.md/t/edit-transcluded-embedded-notes-blocks-in-place-likely-requires-wyswyg-first/15339 for details of the idea - this isn't yet an option in Obsidian but is an option in other apps.

**Comment by zefhemel** [comment]
I’m going to hijack this issue and use it to actually implement Obsidian-style transclusions. Likely initially this won’t allow editing, although I’m thinking that clicking/tapping on the transcluded text will simply navigate you to the transcluded page, which in turns will allow you to edit it.

**Comment by zefhemel** [comment]
Here are the Obsidian docs on “embedding”: https://help.obsidian.md/Linking+notes+and+files/Embedding+files

Note this also supports and other things. One thing at a time 😄

**Comment by ryanwwest** [comment]
Thanks, transclusions first sounds great! I'd love if you designed it in a way that could make it easy to in the future make them directly editable too. At the same time, I have no idea how hard that would be.

Some notes to consider:
- Obsidian has some weaknesses in its transclusions. If you either link or transclude a heading and then change the heading title, the links are broken. You don't run into this with blocks since they have a unique identifier, which makes me wonder if unique identifiers are just better overall.
- If you transclude a bullet point, sub-bullets are also transcluded. I like this though I always wish you could like to a non-bulleted paragraph with a list immediately following and have the list be included. For example, if I made a link to [[Some notes to consider:]] above (with a unique identifier), no spacing indicates the list 'belongs' to that top paragraph/block and so both of these points are also included in the transclusion. But maybe there are drawbacks. And perhaps you want to have parity with Obsidian behavior. 

Maybe your comment "Note this also supports and other things" was intended to cover some of the above..

**Comment by ryanwwest** [comment]
Here's an idea I had about linking to / transcluding a specific region of text in Obsidian (for another FR, lol): https://github.com/erykwalder/quoth/issues/20.

**Comment by zefhemel** [comment]
@onespaceman i think you intended to implement this, since you already did so for attachments. Is this still the plan? Otherwise I may take it

**Comment by onespaceman** [comment]
I have some progress, but I'm moving houses and don't have time to finish it for a couple weeks. You're welcome to do it. I'll put up a pull request with what I have so far.

**Comment by zefhemel** [comment]
WIP PR here: https://github.com/silverbulletmd/silverbullet/issues/903

Up for grabs if somebody wants to work on it

**Comment by zefhemel** [comment]
This has now been implemented with https://github.com/silverbulletmd/silverbullet/commit/fb21377bef1fd5d5b99f629741e9d14dc3b482e0
