### ISSUE TITLE
Overriding page switcher/command palette keybindings

### ISSUE THREAD

**Issue by jamesgecko** [silverbulletmd/silverbullet#537]
Hello! The `SETTINGS` document indicates that keybindings defined by plugs may be redefined. Is it possible to redefine `Cmd-k` and `Cmd-/`? [They appear to be hard coded](https://github.com/silverbulletmd/silverbullet/blob/0034b4e8a7d2efd90ac1056a145865725f869b56/web/editor_state.ts#L173). While using VSCode I've gotten used to using `Cmd-p`/`Cmd-Shift-p` for accessing the equivalent of the Silverbullet page switcher and command palette.

**Comment by zefhemel** [comment]
Not possible right now, but wouldn't be very hard to do. I'll put it on my backlog.

**Comment by zefhemel** [comment]
Keybindings are not configurable in https://silverbullet.md/SETTINGS by overriding keys for the `Command Palette` and `Navigate: Page Picker` commands.
