### ISSUE TITLE
No warning on invalid YAML object

### ISSUE THREAD

**Issue by pithlessly** [silverbulletmd/silverbullet#539]
Creating a YAML fenced code block with a tag will cause it to be treated as an object:

    ```#myfields
    a: 1
    b: 2
    c: 3
    ```

However, there are many subtle issues which can cause something to be invalid YAML.
Among these are the presence of a duplicate key:

    ```#myfields
    a: 1
    b: 2
    a: 3
    ```

Or incorrect indentation:

    ```#myfields
    foo: 1
    bar: 2
     bz: 3
    ```

When these errors occur the fenced block will not be regarded as an object at all, causing it to not be accessible by queries etc. This is probably the right behavior (since we can't product the fields of the object), but it might be hard for the user to notice the problem when creating the YAML block — the only feedback is that it isn't visible in queries.

It might be useful to emit some visual warning at the code block, to indicate to the user that the object is being ignored due to a syntax error. Even better would be to highlight the location of the error.

P.S. thanks for creating this, it's a fantastic tool.

**Comment by zefhemel** [comment]
Completely agree. There needs to be inline feedback to show such errors. CodeMirror  (the editor component SB uses) has this capability, so this is very doable. Adding it to my list.
