### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#547]
To make it easier for people to host multiple SilverBullet spaces on a single server, built-in multi-tenancy support would be nice.

This would require:

* [ ] The ability to configure multiple space configurations. Each space configuration requiring:
   * A name (for internal use)
   * A path containing the space files
   * A hostname to bind to (this would be based on virtual hosts), e.g. a domain name or a sub-domain name, we’re not going to support sub-directories for now
   * Authentication information, e.g. a username:password combo
* [ ] The server needs to be adapted to spin up a new instance of itself (its own ServerSystem at least) based on the request’s hostname. Effectively it will keep a pool of these in memory (and maybe flush out inactive ones).
* For performance reasons, this would benefit from #545 and #546 
* To be considered as part of this package: https://github.com/silverbulletmd/silverbullet/discussions/468

Open questions:
* Where should this configuration be kept? A file? A database? Same for authentication info.

Note: this infrastructure can eventually be used to create a SaaS version of SB.

**Comment by yorrd** [comment]
Quick note: security is a concern for many users that opt for an offline-first PKM. Maybe end to end encryption should be part of the discussion? I do realize it's quite a lot of effort though.

**Comment by zefhemel** [comment]
Yep, linked in the discussion on that topic: https://github.com/silverbulletmd/silverbullet/discussions/468

**Comment by slashtechno** [comment]
> Note: this infrastructure can eventually be used to create a SaaS version of SB.

Would this remain fully open source and self-hostable? Or would it become an subscription model of some sort, even to self-host?

**Comment by zefhemel** [comment]
For now I've deprioritized this and am focusing on the self hosted single player aspects.
