### ISSUE TITLE
Alternative storage back-end support

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#548]
Currently SilverBullet primarily supports using a folder on disk to store space content. Technically there is also S3 support, but this is mostly undocumented. It would be great to properly support multiple storage backends, e.g.:

* Disk (current default)
* S3
* Deno KV (for easily deploying SilverBullet to [Deno Deploy](https://deno.com/deploy))

How to configure this? Right now it’s done via the folder path:

* An absolute/relative path enables disk mode
* `s3://` enables S3 mode, further configured with environment variables

A similar pattern can be used more generally.

**Comment by virtadpt** [comment]
Could I put in a request for [WebDAV](https://en.wikipedia.org/wiki/WebDAV)?

**Comment by kothavade** [comment]
Tried following the Deno Deploy + S3 instructions, and it seems to fail here: https://github.com/silverbulletmd/silverbullet/blob/main/server/server_system.ts#L63
This is the exact error I get:
```
error: The deployment failed: UNCAUGHT_EXCEPTION

TypeError: Non-default databases are not supported
    at Object.openKv (ext:deno_kv/01_db.ts:9:26)
    at ServerSystem.init (https://silverbullet.md/silverbullet.js:64004:30)
    at _Command.serveCommand [as fn] (https://silverbullet.md/silverbullet.js:64165:24)
    at _Command.execute (https://silverbullet.md/silverbullet.js:2937:18)
    at _Command.parseCommand (https://silverbullet.md/silverbullet.js:2821:19)
    at async https://silverbullet.md/silverbullet.js:76341:1
```
If I'm reading this correctly, Deno KV cannot write its database to S3? It's also possible I've set up S3 or Deno incorrectly, so if others are able to successfully deploy to Deno with S3, I'll take a second look at my own setup. If it is an issue with the project, I'd be happy to help work on this issue, if you have any pointers on what it would take!

**Comment by zefhemel** [comment]
Yeah that's likely broken now. Working on it.

**Comment by zefhemel** [comment]
There’s now S3 and KV support (next release).

**Comment by virtadpt** [comment]
@zefhemel Would that apply to S3-alike services as well (like B2 or Minio)?

**Comment by zefhemel** [comment]
They should yes.

**Comment by kothavade** [comment]
Working great, thanks! I see it has to run in `SYNC_ONLY` mode, because Deno Deploy doesn't support Workers--do you have any plans on eventually supporting Cloudflare Workers, with storage via Cloudflare Workers KV (or S3 via R2)?

**Comment by zefhemel** [comment]
I don't think Cloudflare workers support Deno, so that would be quite an effort. Netlify edge functions may be more feasible.
