### ISSUE TITLE
Feature Request: limit query by page depth

### ISSUE THREAD

**Issue by thinkbig1979** [silverbulletmd/silverbullet#553]
From what I can tell there is currently no easy way of limiting a query by the depth of the page in the tree. This would be a very useful feature in my  opinion, especially in queries used to create a kind of table of contents.

Contrived example, but let's say you're a historian and you have a log of events spanning centuries, with a tree structure that looks like this:

century/decade/year/month/day

Let's say you want to make a query to generate a table of contents that goes down to the  year level, but does not list months or days separately. You can accomplish this with regex, but it would be easier if you could issue a page query with a depth limited to 3 or something of that nature.

An indent by depth format would also be great in that scenario, but that's probably a lot more complex.

**Comment by zefhemel** [comment]
Ok, so queries have 0 concept of what pages are, or even folders. I kind of like it that way. However, what queries as of recently do support (although I have not documented yet this on purpose because it's not fully ironed out) is the ability to call functions. I'm still thinking how to make the set of functions available extensible, but let's say we add two built-ins here:

* `split(page, "/")` so a string split function, that would return the argument split on the separator
* `length(...)` (or `count(...)`) which would could the number of elements in a list

Then a filter could be: `where length(split(page, "/")) < 3` to achieve such a thing. 

What do you think?

Again, not implemented yet, but not hard to do.

**Comment by thinkbig1979** [comment]
Allowing for function in queries will make them even more powerful, so that's a really nice feature.
Your suggested implementation for the filter makes a lot of sense as well. 

In the future, if user defined/template functions are allowed for, you could have a user defined function where the variable `depth' is defined as `length(split(page, "/"))` and then the user could simply specify 'where depth <3` in their query. Is that roughly what you have in mind with extensible functions?

**Comment by zefhemel** [comment]
What I had in mind with making functions extensible is to allow plugs to define their own custom functions, however this may be problematic from a performance perspective. When you perform a query against a large data set, and that query contains function calls, this function call is evaluated against every single entry. This is ok-ish with quick, synchronous calls, but when crossing a plug's sandbox boundary this can potentially get quite slow. 

An alternative solution (but with limitations) could be to allow users to define JS snippets that define such functions, e.g.

    ```custom-function
    function depth(path) {
       return path.split("/").length;
    }
    ```

which you could then use in your queries. This has limitations and is potentially insecure (allowing to run random JS code in the browser can be problematic). It would be _flexible_ though ;) You'd then call this using the `where depth(path) < 3` syntax

**Comment by thinkbig1979** [comment]
Hmm, I can see how both options have their drawbacks. You don't want the app to be a security threat, but you do want it to be performant. 
[Rock < 😦 > Hard place]

**Comment by zefhemel** [comment]
No worries, just thinking out loud here. I'll figure something out.

**Comment by zefhemel** [comment]
So this now possible using defining a custom function using space script. https://silverbullet.md/Space%20Script

**Comment by thinkbig1979** [comment]
I will take a look, thanks!
