### ISSUE TITLE
Unknown option "-o" - no matter what flags I pass to the standalone binary

### ISSUE THREAD

**Issue by johnlunney** [silverbulletmd/silverbullet#556]
Just downloaded the 0.5.3 binary on macOS Intel, when I run ./silverbullet I get:
error: Unknown option "-o". Did you mean option "-h"?

No matter what flags I pass, I get this. I can't see any alias or similar that would be kicking in.

@zefhemel says:
Oh yeah, I see the same that's weird. Haven't tested the standalone binaries for a while

**Comment by zefhemel** [comment]
Will be fixed in next release
