### ISSUE TITLE
Make Silver Bullet run on Windows

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#56]
Right now, SB doesn’t really run on windows (at least the server doesn’t). When you run the `npx` command, it downloads and installs fine, but then it fails. After finding the folder where `npx` downloaded everything, in my case under `C:\Users\Zef\AppData\Local\npm-cache\_npx\3678a4af46f0276d\node_modules\@silverbulletmd\server` I can run `node dist\server\server.js` from there with a path to a folder, and that kinda runs. But it seems plugs don’t load properly etc. 

Honestly, I don’t know anything about node and Windows. Probably somebody who does could figure out what’s going wrong here. Help wanted!

**Comment by zefhemel** [comment]
Now works

**Comment by iamm3u** [comment]
how did you get it to work
