### ISSUE TITLE
Unsupported query source 'page' / =~ query bug

### ISSUE THREAD

**Issue by tristansokol** [silverbulletmd/silverbullet#564]
Hi! 

Recently did a fairly large leapfrog of versions and am updating my queries. It seems like the `=~` operator doesn't seem to work? 

for example 
````
```query
page where name =~ "test" 
```
````
gives `**Error:** Unsupported query source 'page'` 
 
 but 
````
```query
page where name = "test" 
```
````

works fine. 

I haven't seen anyone else report this error, so not sure what the deal is.  
using version 0.5.4.

**Comment by dedioste** [comment]
Same here, live queries broken since saturday updates

**Comment by zefhemel** [comment]
The syntax has always be to use `=~ /test/` not `=! "test"` I don't think that changed? Can you try using the regex `/` notation?

**Comment by tristansokol** [comment]
ah perfect! 

You are probably right, but I'm coming from the old `<!-- #query` syntax where I had something along the lines of `<!-- #query page where  name =~ “🗓️”` to see all my weekly notes. I'll see if I can find a spot in the docs to add this in. Thanks!

**Comment by zefhemel** [comment]
The syntax was like this from day 1, but the parser is kind of permissive, so maybe it just accepted it before and now is in a more strict mood.

**Comment by dedioste** [comment]
Same as above, some rewriting of the query tward a more modern model did the trick.
