### ISSUE TITLE
Overriding `--subtle-background-color` CSS value renders background color on top of selection background

### ISSUE THREAD

**Issue by BramBonne** [silverbulletmd/silverbullet#567]
Example screenshots below, to better illustrate what I mean.

Without overriding `--subtle-background-color`, selecting something inside a code block looks as expected:
![image](https://github.com/silverbulletmd/silverbullet/assets/614383/ca387422-3066-429a-8f9a-0df1782fface)

Overriding it (in my case, setting `--subtle-background-color: var(--ctp-mocha-surface0);`), renders text selection as follows:
![image](https://github.com/silverbulletmd/silverbullet/assets/614383/6704cb90-b2db-4af2-aedb-4713b795e27d)
Note that the text is properly selected, but the selection background color seems to render "behind" the overridden background color of the code block.

Overriding the `--root-background-color` works as expected, without any text selection rendering issues.

**Comment by zefhemel** [comment]
Yes, you need to use a color that is partially transparent like rgba or some other way of setting the alpha to set transparency. 

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb

**Comment by BramBonne** [comment]
Ah, yep, that did it!

Is this a limitation of CSS / generally related to the CSS model? I'd expect a z-index for the selection background to fix this, but I'm about the furthest away from being a web developer one can be :)

**Comment by BramBonne** [comment]
That seems to be [exactly the case](https://discuss.codemirror.net/t/line-background-color-and-selection-layering/5413) :)

I'll close this issue. The thread linked above has the suggestion of using [`layer`s](https://codemirror.net/docs/ref/#view.layer) to supposedly handle this, just in case.
