### ISSUE TITLE
[FR] Embedding local pages / Page content in template

### ISSUE THREAD

**Issue by buxel** [silverbulletmd/silverbullet#568]
Hi! I started exploring SB for my personal daily notes and stuff i need to remember (and maybe share  with my wife).
I usually take some daily notes and at the end of a week, i review them and update more "stable" pages, if necessary.
Right now, any quick/daily note i create, feels somehow "lost", because it is not easily discoverable.

It would be great to have a way to get one page with all my daily notes concatenated to scroll through. I tried using a Query + template + embed but this resulted in problems with width not being used ideally and the header of SB getting duplicated for each daily note.

I may have missed how this could already work. If so, any pointers would be appreciated.
If not, consider it a feature request: allow local pages to be embedded with dynamic height and without header, Alternatively, allow templates to get the raw page content.

It could look something like this:

-----
# Daily Notes
## 2023-11-15
- Missing browsing my daily notes easily, created a feature request

## 2023-11-14
- told friend about SB, he seems intrigued

## 2023-11-13
- Discovered silverbullet, played with the demo

<...more...>

(pagination may become an issue, but limiting it to x pages may work around this.)

I have noted a similar request #533 with a little different usecase. I did not want to hijack it but i think they could be solved together.

Thank you for building this interesting piece of software! 👍

**Comment by zefhemel** [comment]
Would using a [live template](https://silverbullet.md/Live%20Templates) not do the job? This embeds another page into the current one. You can use `raw: true` to avoid any processing of handlebars instructions.

    ```template
    page: "[[some other page]]"
    raw: true
    ```

**Comment by buxel** [comment]
This does not seem to work. I get an error

```
 end of the stream or a document separator is expected at line 1, column 24: page: [[📅 2023-11-15]]] ^
```

It can be replicated by appending this on silverbullet.md (i could not get the proper backticks properly escaped in this reply)

```
'''template
page: [[💡 Inspiration]]]
raw: true
'''
```

**Comment by zefhemel** [comment]
Hmm, seems to work for me?

![CleanShot 2023-11-17 at 09 37 24](https://github.com/silverbulletmd/silverbullet/assets/59073/827dad0f-c71c-48fa-8006-007f68532a3d)

**Comment by buxel** [comment]
After a good night of sleep i realized, i simply missed the quotes around `page: "[[some other page]]"`

To anybody looking for this, i got it working using this query:

````
```query
page 
where name =~ /^📅/
order by name desc
render [[template/daily]]
```
````

and the following `daily/template`

````
## [[{{name}}]]
```template
page: "[[{{name}}]]"
raw: true
```
````

I assume pagination clashes with your model of writing the query result to the file, right?
What would be an alternative approach to this? Could a plug do this?

**Comment by zefhemel** [comment]
Query results are not written directly to a file anymore, this used to be the case with directives but no longer.

Pagination... yeah not sure how to handle that. You can limit your result set with e.g. a `limit 10` clause in your query, but there's no `offset` or similar at this point.
