### ISSUE TITLE
some ideas - how to 'plug' it?

### ISSUE THREAD

**Issue by hololeo** [silverbulletmd/silverbullet#572]
ive been using silverbullet for a few days. 

here are some ideas to make it better for my particular use case (researching on the web)

- a site map / tree should come out of the box. this is probably already possible with query
- breadcrum navigation or some other method to know where i was, what is the context

its presently very ackward to navigate this thing as a knowledge base. but im sure all the blocks are there to build it

**Comment by zefhemel** [comment]
Yeah, a file tree would probably make sense. We have an issue for it: https://github.com/silverbulletmd/silverbullet/issues/102

Regarding breadcrum navigation? Usually that's related to the hierarchy of a website/space, but what you're suggesting here is to make it dynamic based on your browsing history? Something like "index > meetings > 2024-08-03 daily > meetings"?
