### ISSUE TITLE
Button gets triggered when clicking next to it (Android Chrome)

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet#585]
When clicking next to a button, it gets triggered which makes editing or even deleting it a bit difficult

I think this is a mobile only bug, as on Desktop there is no such problem and a click next to a button would not trigger it.

See this video:
https://github.com/silverbulletmd/silverbullet/assets/8049779/ff10b4c2-f40c-447c-9f2a-c6df306d17b5

**Comment by zefhemel** [comment]
Ok, I cannot replicate this on my iOS simulator, but I have fixed this bug for desktop specifically before. I think what I pushed now should fix it, let me know if it does.

**Comment by v411e** [comment]
Ah, perfect! Yes I can confirm the bug is fixed now. Thank you
