### ISSUE TITLE
After a docker image update silverbullet fails to start

### ISSUE THREAD

**Issue by prcrst** [silverbulletmd/silverbullet#590]
`docker-entrypoint.sh` calls `bash -e` and the groupadd fails here after a restart.

`docker logs silverbullet`:
```
Will run SilverBullet with UID 1000, inferred from the owner of /space (set PUID environment variable to override)
groupadd: group 'silverbullet' already exists
```

The image was auto-updated via watchtower and the initial restart worked.
It failed after a subsequent host reboot.

**Comment by zefhemel** [comment]
I think I just fixed this, can you try with `:edge`?

**Comment by prcrst** [comment]
Works again
