### ISSUE TITLE
Content jumping when selecting text close to a query

### ISSUE THREAD

**Issue by buxel** [silverbulletmd/silverbullet#592]
There is some jumping around happening when selecting text close to a query result. 

You have to be very careful to not accidently move the mouse too close to it or it can get very confusing. Especially with multiple queries on one page it is basically impossible to navigate, once it happens.

![SilverBullet - Brave 2023-12-02 15-20-20](https://github.com/silverbulletmd/silverbullet/assets/331779/a3fd625d-b301-4c9e-b542-14413417937a)

Posssible fixes:
1) keep height of query editor/result the same when a selection enters a query area. This may still make the selecting behavior odd.
2) do not switch to edit mode while as selection from "outside" enters a query result. Instead, continue selecting the results

I'd prefer 2) because it seems to be the more intuitive behavior

**Comment by zefhemel** [comment]
Yeah, this is not great, let me see what I can do. I like option 2 also, have to see if it's feasible (I think so)

**Comment by zefhemel** [comment]
I think I just made this at least less bad than before, although the behavior is hard to completely get rid of. Could you check on silverbullet.md to see if it's better for you now (this is also available on the `:edge` docker image, but not properly released yet).

**Comment by buxel** [comment]
I deleted cache and tried again... not sure what changed but it feels a little different than before. It still looks like this:

![sb_jumping](https://github.com/silverbulletmd/silverbullet/assets/331779/6dd6afec-d289-481e-a30d-74302bb7e5c4)

**Comment by zefhemel** [comment]
I think this should be resolved with recent changes (not yet released, only on edge)
