### ISSUE TITLE
Implement proper (temporary) token based authentication

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#594]
Currently the basic authentication mechanism is likely not very secure, needs to be enhanced by giving out (temporary) session token that can be revoked, as well as proper CSRF etc.

**Comment by v411e** [comment]
Maybe using OIDC?

**Comment by zefhemel** [comment]
OpenID maybe at some point, although honestly for a single-user system I'm not sure that's super helpful. I've now implemented authentication with JWTs, and added some CSRF as well, which should be a big improvement already.
