### ISSUE TITLE
page changed elsewhere, reloading in online mode

### ISSUE THREAD

**Issue by skyrunner15** [silverbulletmd/silverbullet#603]
On a Synology NAS, single host, no backend sync or other processes - I keep getting the page changed elsewhere, reloading in online mode. Sync seems to be OK and I've set the PUID/PGID variables to 1026/1000 since the PGID for the admin group still results in errors on SB startup. 1026 is the correct owner of the folder where all the files are saved into. Any thoughts?

**Comment by skyrunner15** [comment]
For what it's worth, the groupadd issue seems to be back in latest and edge docker images. Getting this error again:

groupadd: GID '101' already exists
groupadd: GID '101' already exists

Environment variables are:
      - PUID=1026
      - PGID=101

**Comment by zefhemel** [comment]
This is really strange. When you run in Sync mode, do you see (in the JavaScript developer console) that files are currently resyncing as well, or not? The only reason this may be happening that I can think of is that some your NAS doesn't reliably keep last modified timestamps for files. What filesystem do you use?

**Comment by skyrunner15** [comment]
Synology BTRFS is the file system; sync mode seems to work ok for the most part though. The files do change properly and I can see the update on the server end in the .md files. There's just something funky with the PUID/PGID bit - like I can get it to run when I force PGID=1000, but no 1000 exists on the Synology. The admin group is 101 which has control over that directory, but when I use 101, the groupadd error comes into play and SB never starts.

**Comment by zefhemel** [comment]
The problem is that the docker container already has a group with GID 101: `ssh`...

**Comment by skyrunner15** [comment]
That might do it - Synology uses 100 for users and 101 for admins by default with no way to change them

**Comment by zefhemel** [comment]
Yes I think I just fixed it. Could you try the `zefhemel/silverbullet:edge` image to verify?

**Comment by skyrunner15** [comment]
Edge seems to be working! No startup issues... using the notes for work now :)
