### ISSUE TITLE
Space on end of page name creates two pages, one shadowed

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet#615]
**What happened**
1. Create a new page using the "Page: From Template" command with a space at the end of the name
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/a8e46bfc-e51c-401d-8f28-0a5b06013d4a)

2. See that two pages are created, but links always point to the page without space at the end
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/4631cb3c-26e4-410d-8c32-e1a4ee5c2cb3)

3. View on filesystem
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/4e6c7bd8-0646-41b2-acf5-b82c43958d47)

**What I expected**
- Creating a new page using the "Page: From Template" command with a space at the end of the name should strip the space from the name before creating a page.
- Only the page without a space at the end should be created

**Comment by fflorent** [comment]
If that's OK, I can take this one.

**Comment by v411e** [comment]
Thank you very much @fflorent 😍
