### ISSUE TITLE
Add Keyboard Shortcut for "Delete Line"

### ISSUE THREAD

**Issue by Gugi264** [silverbulletmd/silverbullet#618]
Since the new update it is possible to add custom Keyboard Shortcuts.

One Shortcut I am missing is "Delete Line"

**Comment by zefhemel** [comment]
This has to be wrapped in a command: https://codemirror.net/docs/ref/#commands.deleteLine see see `web/syscalls/editor.ts` for examples.

**Comment by pihentagy** [comment]
About to commit the solution tomorrow.

Any suggestion for default shortcut?

**Comment by Gugi264** [comment]
My personal preference is Ctrl+d
But no idea if that would be a good default

**Comment by pihentagy** [comment]
Seems to be heavily tool-dependent, but I guess the future is choosable keymap for IntelliJ/Eclipse/VSCode/whatever editor users.
