### ISSUE TITLE
New live widget linked-mentions cut characters when rendering notes

### ISSUE THREAD

**Issue by paletochen** [silverbulletmd/silverbullet#621]
Screenshot to show what the subject says:

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/9dc7d67f-399e-4a72-ad47-4efb00f4f51b)

You can see that the `N` from `Next Day` is missing

**Comment by henrikx** [comment]
Use the following Linked Mentions template:
```
---
description: Adds Linked Mentions to pages
tags: template
hooks.bottom.where: 'true'
---
{{#let @linkedMentions = {link where toPage = @page.name and page != @page.name order by page}}}
{{#if @linkedMentions}}
# Linked Mentions
{{#each @linkedMentions}}
* [[{{ref}}]]:
`{{
replace(
  replace
  (
    replace
    (
      Substring(readPage(page), pos, 10),
      "[[",
      "`[["
    ), "]]", "]]`"
  ),/^`/, " `"
)
}}`
{{/each}}
{{/if}}
{{/let}}
```

Requires this space script:
```javascript
silverbullet.registerFunction("Substring", (inputString, position, numWords) => {
    // Split the input string into words
    const words = inputString.split(/\s+/);
    
    // Calculate the character index corresponding to the position
    let currentIndex = 0;
    let wordIndex = 0;
    while (currentIndex < position && wordIndex < words.length) {
        currentIndex += words[wordIndex].length + 1; // +1 for the space
        wordIndex++;
    }
    
    // Check if the position is within the bounds
    if (wordIndex >= words.length) {
        return "Position out of range";
    }
    
    // Extract words at the specified position
    const startIndex = Math.max(0, wordIndex - numWords);
    let endIndex = Math.min(words.length, wordIndex + numWords + 1);
    
    // Stop if we encounter the backtick character
    for (let i = wordIndex + 1; i < words.length; i++) {
        if (words[i].includes('`')) {
            endIndex = i;
            break;
        }
    }
    
    const extractedWords = words.slice(startIndex, endIndex);
    
    return extractedWords.join(" ");
})
```

**Comment by henrikx** [comment]
@paletochen That version of the script doesn't take into account multiline.

Try this version which takes only the line at the position.
```javascript
silverbullet.registerFunction("Substring", (inputString, position, numWords) => {
  function getLineAtPosition(inputString, position) {
      // Split the input string into lines
      const lines = inputString.split('\n');

      // Calculate the line index corresponding to the position
      let currentIndex = 0;
      let lineIndex = 0;
      while (currentIndex < position && lineIndex < lines.length) {
          currentIndex += lines[lineIndex].length + 1; // +1 for the newline character
          lineIndex++;
      }
  
      // Check if the position is within the bounds
      if (lineIndex >= lines.length) {
          return "Position out of range";
      }
  
      // Extract the line at the specified position
      return lines[lineIndex-1];
  }

    // Split the input string into words
    inputString = getLineAtPosition(inputString, position);
    const words = inputString.split(/\s+/);
    
    position = inputString.length/2;
    
    // Calculate the character index corresponding to the position
    let currentIndex = 0;
    let wordIndex = 0;
    while (currentIndex < position && wordIndex < words.length) {
        currentIndex += words[wordIndex].length + 1; // +1 for the space
        wordIndex++;
    }
    
    // Check if the position is within the bounds
    if (wordIndex >= words.length) {
        return "Position out of range";
    }
    
    // Extract words at the specified position
    const startIndex = Math.max(0, wordIndex - numWords);
    let endIndex = Math.min(words.length, wordIndex + numWords + 1);

    // Stop if we encounter the backtick character
    for (let i = wordIndex + 1; i < words.length; i++) {
        if (words[i].includes('`')) {
            endIndex = i;
            break;
        }
    }
    
    const extractedWords = words.slice(startIndex, endIndex);
    
    return extractedWords.join(" ");
})
```

**Comment by paletochen** [comment]
@henrikx Thanks for working on this.

It seems you fixed showing extra lines but I am not getting a ton of "Position out of range" while the original "Linked Mentions" work

**Comment by paletochen** [comment]
> @paletochen I am unable to reproduce your issue. Did you make sure to copy the whole script? I had to change parts of the original script to make it work.

I do seem to have everything as you outlined.

My `Space-Scripts` page
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/dfe9ccee-6270-4cca-b1e5-2cd80661a002)



My `Linked Mentions` page
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/f61af38c-c10e-48d1-b90e-95a89ebd5bfb)


And here what I mean:
![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/ad686db7-c14b-4f32-82fd-e5483aebf611)

**Comment by henrikx** [comment]
@paletochen Sorry for the issue. There was an edge-case. I have edited my comment with an improved version.

**Comment by paletochen** [comment]
> @paletochen Sorry for the issue. There was an edge-case. I have edited my comment with an improved version. I don't have a big space to test with right now, so would be helpful if you let me know if there is any more issues.

No worries,
I am happy to test this, you are making my experience better with your ideas :)

It seems that the last time you modified https://github.com/silverbulletmd/silverbullet/issues/621#issuecomment-1942299336 was nearly 1h ago.

Can you confirm which comment exactly did you update with the fix?

Thanks :)

**Comment by henrikx** [comment]
@paletochen That is definitely the one I edited. I have verified that I edited it. Refresh your page?

**Comment by paletochen** [comment]
> @paletochen That is definitely the one I edited. I have verified that I edited it. Refresh your page?

Then I am still seeing the same problem. Another example:

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/e9f5add4-b6a2-4204-927e-89e893ec428e)

This is what i have right now in my space-script

````
```space-script
silverbullet.registerFunction("Substring", (inputString, position, numWords) => {
  function getLineAtPosition(inputString, position) {
      // Split the input string into lines
      const lines = inputString.split('\n');

      // Calculate the line index corresponding to the position
      let currentIndex = 0;
      let lineIndex = 0;
      while (currentIndex < position && lineIndex < lines.length) {
          currentIndex += lines[lineIndex].length + 1; // +1 for the newline character
          lineIndex++;
      }
  
      // Check if the position is within the bounds
      if (lineIndex >= lines.length) {
          return "Position out of range";
      }
  
      // Extract the line at the specified position
      return lines[lineIndex-1];
  }

    // Split the input string into words
    inputString = getLineAtPosition(inputString, position);
    const words = inputString.split(/\s+/);
    
    position = Math.trunc(inputString.length/2)-1;
    // Calculate the character index corresponding to the position
    let currentIndex = 0;
    let wordIndex = 0;
    while (currentIndex < position && wordIndex < words.length) {
        currentIndex += words[wordIndex].length + 1; // +1 for the space
        wordIndex++;
    }
    
    // Check if the position is within the bounds
    if (wordIndex >= words.length) {
        return "Position out of range";
    }
    
    // Extract words at the specified position
    const startIndex = Math.max(0, wordIndex - numWords);
    let endIndex = Math.min(words.length, wordIndex + numWords + 1);

    // Stop if we encounter the backtick character
    for (let i = wordIndex + 1; i < words.length; i++) {
        if (words[i].includes('`')) {
            endIndex = i;
            break;
        }
    }
    
    const extractedWords = words.slice(startIndex, endIndex);
    
    return extractedWords.join(" ");
})
```
````

**Comment by henrikx** [comment]
@paletochen Did you reload system after replacing the script? `Ctrl + Alt + R`

If yes, please send me a screenshot of what of those notes with links look like.

**Comment by paletochen** [comment]
> @paletochen Did you reload system after replacing the script? `Ctrl + Alt + R`
> 

Yes, I have performed several times `System Reload`.
Even clear cookies, and multiple page refreshes.

> If yes, please send me a screenshot of what of those notes with links look like.


The previous screenshot with all those `Position out of range` are coming from my [[Linux]] page, which is referenced in many places.
There's nothing fancy on those other pages. 

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/88d14e51-0d1b-42c0-96ce-9cc575bdc6bf)

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/4b870152-12f6-47b5-96fa-67102d6f3e58)

**Comment by henrikx** [comment]
@paletochen Thanks for the additonal information.

I have updated my comment again. Could you check again?

**Comment by paletochen** [comment]
> @paletochen Thanks for the additonal information.
> 
> I have updated my comment again. Could you check again?

Progress :)

It doesn't throw the error now but the output is not quite there yet.
(nit: I made a mistake before, it is not referencing [[linux]] but [[docker]] page as you can see in this screenshot)

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/14210739-fdc2-4703-9007-81bfc05b0af8)

**Comment by henrikx** [comment]
@paletochen 
Use improved template:
```
---
description: Adds Linked Mentions to pages
tags: template
hooks.bottom.where: 'true'
---
{{#let @linkedMentions = {link where toPage = @page.name and page != @page.name order by page}}}
{{#if @linkedMentions}}
# Linked Mentions
{{#each @linkedMentions}}
* [[{{ref}}]]:
`{{
replace(
  replace(
    replace(
      replace(
        Substring(readPage(page), pos, 10),
        "[[",
        "`[["
      ), "]]", "]]`"
    ),/^`/, " `"
  ),/`$/,"` "
)
}}`
{{/each}}
{{/if}}
{{/let}}
```

**Comment by paletochen** [comment]
@henrikx 
And here you have the output :smile: 

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/0cefc5af-8db1-4fc4-a761-947a44a9f31e)

**Comment by henrikx** [comment]
Looks like what I had in mind for it to look like :smile:

Thanks for help squashing the bugs out! If you want the structure of the output to be different, you just need to update the template. The `Substring`-method simply returns the `numWords`-number of words around the link on the same line.

**Comment by paletochen** [comment]
Thank you for taking the time to provide this working (and great) solution :)

**Comment by henrikx** [comment]
@paletochen I have updated the script again. There was an issue where the position within the line was always the middle of the line, instead of the position of the link, so if the wordlength of the line exceeded the numWords-parameter and your link was at the edges you would not see the true context.

**Comment by paletochen** [comment]
> @paletochen Thought you would like to know I have updated the script again. There was an issue where the position within the line was always the middle of the line, instead of the position of the link, so if the wordlength of the line exceeded the numWords-parameter and your link was at the edges you would not see the true context.

Thanks for letting me know.
I updated my instance with the latest version :)

**Comment by zefhemel** [comment]
Another approach (content wise) rather than a hard cut-off which can then be fixed up, is used here: https://notes.andymatuschak.org/About_these_notes?stackedNotes=z5E5QawiXCMbtNtupvxeoEX&stackedNotes=zNUaiGAXp21eorsER1Jm9yU this includes the full sentence containing the linked reference which seems quite nice (but potentially long)

**Comment by zefhemel** [comment]
I think this should be better now (reindex your space for this to have effect)
