### ISSUE TITLE
REQ: Daily journal as index page

### ISSUE THREAD

**Issue by crawfordlong** [silverbulletmd/silverbullet#622]
Based on our exchange over in Discussions, there is no current way to set one (or more) of the following as an index page:

1. The current day's Daily Journal page (create if does not exist)
2. List of Daily Journal entries

**Functionality** - A potential interface would be a "meta-page" for the Daily Journal containing:
- a directly editable current day's entry (created if does not exist) followed by 
- an infinite scrolling list of previous entries (links or content). 

This is comparable but not identical to to both logseq's and Roam's behavior. 

I suspect this would align at least conceptually with other discussions here about a calendar view and other similar structured ways of accessing content.

(Happy to attempt a first draft if you accept PRs.)

**Comment by zefhemel** [comment]
Yes, see the Tips section here: https://silverbullet.md/Library/Journal

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/7990eeb6-ffd2-4215-bb66-65b65e5520b9)

Thanks, 

1. I tried `indexPage: "Journal/Day/{{today}}"`, but it looked quite different from past daily notes.
2. What does the `Library: Import` of `!silverbullet.md/Library/Journal/` do? It did not seem to make any difference

**Comment by bilogic** [comment]
I figured out it was just about renaming the past pages. However, doing a rename had the effect of duplicate the past day notes instead.... bug?

**Comment by zefhemel** [comment]
So the naming convention of daily notes has changed, but if you like you can change it back: https://community.silverbullet.md/t/live-now-templates-2-0/29/5

As to what `Library: Import` do: it copies a set of templates from (in this example) silverbullet.md into your own local space. You can then find them with your Template Picker and edit them as you see fit from there.

**Comment by bilogic** [comment]
Ok, thanks, will we eventually have a way to have show day notes in 1 page sorted chronologically?

**Comment by zefhemel** [comment]
This explains how you could build something like that: https://community.silverbullet.md/t/weekly-snippets-how-to-embed-a-list-of-pages-its-content-within-a-page/44/4?u=zef

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/481d4d94-01fe-446e-be56-52e27c5b1f52)

I tried following and managed to create the template, but where do I put the `query`?

**Comment by bilogic** [comment]
Nice, I got it to work! 

1. I have this setting `indexPage: "Journal/Day/{{today}}"`, is it possible to show this query at the bottom of each Day note? (Like Linked Mentions) 
2. Would it cause a infinite nesting?

The past notes helps as I need them for references sometimes. Thanks once again!

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/d764f98a-3714-4cf5-ad89-c92ca648acdc)
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/5157e20d-4342-4b0c-aa6e-060419596a09)

I just updated to the latest docker image and this no longer works

**Comment by zefhemel** [comment]
Can you reload the browsers once or twice? This seems like a client JS caching issue.

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/607ff497-e5a7-4852-a2da-8d817f70fd3c)
I disabled my Chrome's cache and it became another error

**Comment by bilogic** [comment]
Any ideas? Thanks

**Comment by zefhemel** [comment]
I've updated https://community.silverbullet.md/t/weekly-snippets-how-to-embed-a-list-of-pages-its-content-within-a-page/44/4?u=zef with the new code to use. Please give that a try.

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/c618cc8f-01d6-48ce-9a21-7e8288c3e21c)
 I just found this, going to try your updated new code.

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/311028b0-6b56-4c10-92a7-b532d3ddba4e)

Question: is it possible to make changes to the `query` so that I can jump and edit the each page?

**Comment by zefhemel** [comment]
Yes, if you imported the core library, you should have a `Library/Core/Query/Page` template so you can do:

~~~
```query
page
where name =~ /^Journal/Day//
render [[Library/Core/Query/Page]]
order by name desc
```
~~~

**Comment by bilogic** [comment]
Thanks, let me try it out. Can I suggest starting an examples folder filled with markdown files? So, in this case, we can file it in `examples/journalling.md`?

**Comment by bilogic** [comment]
I tried, it changed and now shows only a list of dates, which when clicked, links to editing the page.
However, what I want is to retain the earlier `Custom/Journal` where contents of the day are also shown + a clickable link to edit the page, possible?

I wanted to see how `Library/Core/Query/Page` does its magic, but this file does not seem to exists... why is that?

**Comment by zefhemel** [comment]
It's a template so you have to open it via the Template Navigator

**Comment by zefhemel** [comment]
Ok in that case you can use what's described here: https://github.com/silverbulletmd/silverbullet/issues/622#issuecomment-1964294329

Just change the title (you can remove the `replace` part, because the folder etc. will be hidden anyway as link):

```
## [[{{name}}]]
```
and keep the rest as is listed there

**Comment by bilogic** [comment]
Thanks, it worked! Still kind of related to this, when I load the `Journalling` page, it always shows the query instead of content. Possible to make it show content by default?

**Comment by zefhemel** [comment]
Because that's where the cursor ends up initially? Just add an empty line at the top.

**Comment by bilogic** [comment]
done thanks!
