### ISSUE TITLE
Daily Note template needs some love (update)

### ISSUE THREAD

**Issue by paletochen** [silverbulletmd/silverbullet#623]
I noticed in the latest version of SB that Daily note template is not working.

In my local instance, the page is created with the frontmatter of the template (used shortcut `Alt-Shift-d`)

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/f14373a6-dde6-4a67-8082-d6f0b707719b)

Template below:

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/6ed7dc15-cf46-4425-b33c-b35c3028dcea)

Also, in https://silverbullet.md, when pressing `Alt-Shift-d` to create a Daily note, the result is the following page:

![image](https://github.com/silverbulletmd/silverbullet/assets/109062850/b2d06c9a-a3f1-4b97-95cd-902061325765)

**Comment by zefhemel** [comment]
This is now moot with templates 2.0
