### ISSUE TITLE
Non-existent pages

### ISSUE THREAD

**Issue by slfhstr** [silverbulletmd/silverbullet#625]
Just come across SIlverBullet and really like it 👍 
Experimenting, I created a `/query` for pages with the tag `#link`
I get a list showing a number of 'blank' entries with no page tag.
How do I clean this up (or exclude them) ?

query :
```
query
link render all [[template/link]]
```

template/link :
```
| Name | LastModified |  Tags  |
|----------|----------|----------|
{{#each .}}
| [[{{name}}]] | {{lastModified}} | {{tags}}
{{/each}}
```

screenshot :
<img width="811" alt="Screenshot 2024-01-11 at 15 41 30" src="https://github.com/silverbulletmd/silverbullet/assets/28682881/1a32a32e-a4d2-4e92-ad2a-16a5a20a3ed3">

Deployment : selfhost VPS using docker-compose

**Comment by zefhemel** [comment]
What's going on here is that "link" is also a built in tag used for page links and as a result you get a mix of both. 

Not tested, but the following query should do what you want: `page where tags = "link"`

**Comment by slfhstr** [comment]
Thank you @zefhemel 
I took a sideways solution - changed the tag on a page from `link` to `links`.
Don't want to tread on internals
