### ISSUE TITLE
Make headers indexed as objects

### ISSUE THREAD

**Issue by thecandlestick** [silverbulletmd/silverbullet#629]
Idea to index the headers (lines beginning with '#') of a page in order to support a wider range range of queries and templates.

Example application:

Query returns pages A and B. The result can be rendered as follows:
```
* Page A 
Topics in this page:
Header1, Header2

*Page B
Topics in this page:
Header1, Header2, Header3
```

**Comment by zefhemel** [comment]
You can now query `header` as well (since the linked commit)
