### ISSUE TITLE
Export (Share as) PDF, ePub, other formats

### ISSUE THREAD

**Issue by simone-viozzi** [silverbulletmd/silverbullet#635]
Hi, thank you for the great tool.

If I need to share a note with a colleague, how can I print the silverbullet rendering of the note?

Doing print page to PDF from the browser (edge | firefox | chrome) prints only the first page.

Is there a command / plug I need to use to just save the rendered page as PDF?

Thank You!

**Comment by zefhemel** [comment]
There’s no great way to do this right now. The only thing that comes to mind is to open the markdown preview (Cmd-p/Ctrl-p) and copy and paste from there into a word document or some other word processor and export to PDF from there.

I do see the value of this, though, but would have to investigate how to implement this.

**Comment by gorootde** [comment]
In Safari on macOS all the pages are printed. In iOS / iPad OS as well. Seems to be browser related.

**Comment by zefhemel** [comment]
One thing I'd like to investigate is how much weight it would be to add pandoc and latex to the docker image to achieve this and offer export to docx, epub and other formats while at it.

**Comment by zefhemel** [comment]
Or this can be done as a separate pandoc plug which dynamically attempts to install all dependencies. That probably makes more sense. Will investigate at some point.
