### ISSUE TITLE
Button to add file, image/camera

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#639]
On mobiles, it would be wonderful if there was a button to directly attach file/image while typing markdown

**Comment by zefhemel** [comment]
I can see that, my only concern is screen real-estate and minimalism. Right now there are 3 buttons (and soon there will be a 4th), is adding a 5th worth it? Not entirely convinced yet.

**Comment by bilogic** [comment]
Thanks, how about this?

In mobile portrait, all buttons are hidden into a burger menu

In tablet/desktop, these are expanded for direct clicks

**Comment by bilogic** [comment]
Hi,

I did some analysis:

1. `Mode` button, is there a use case where this needs to be toggled constantly? My view is no, so perhaps this can be hidden into a command
2. `Home` button, this kind of assumes we constantly need to edit the same page or jump back to home, to navigate elsewhere, is that the case?
3. `Open` button, definitely needed
4. `Run` button, definitely needed

From this, I think 1 and 2 can potentially be removed if there is no strong use case to support them.

**Comment by zefhemel** [comment]
How about we make all top buttons configurable so you can pick icons and commands to run? I think that will be nice right?

**Comment by bilogic** [comment]
Yes that would be great!

**Comment by zefhemel** [comment]
#643

**Comment by bilogic** [comment]
Just curious, the camera will still be added right? I tried to upload an mp4 file, but could not find it on my server.

**Comment by zefhemel** [comment]
There's already an `Upload: File` command, which should give you the option to also select from the camera. That said, there is a 10MB file upload limit right now, which may not make this great for video...

**Comment by bilogic** [comment]
ok, just tested and it works. Think I also found a bug, if a file upload fails, user should be informed. :)

**Comment by jeroenev** [comment]
Is there an option to change the upload limit?
