### ISSUE TITLE
Suggestion: Path instead of tags in template picker

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet#642]
I noticed, that all templates in the template picker have the exact same tag (`#template`) listed under their name. Also, the name is not very good readable, because of the long path. 

![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/efacc855-e65d-4bed-81cf-f50d3b6a9d50)

What do you think of something like this instead?
![image](https://github.com/silverbulletmd/silverbullet/assets/8049779/710c5710-1eef-4169-b5af-d04cde0bd3cb)

**Comment by zefhemel** [comment]
I like it :)
