### ISSUE TITLE
Mistake in welcome index page (about templates button)

### ISSUE THREAD

**Issue by skorphil** [silverbulletmd/silverbullet#645]
Hi, just installed an app. Seems promising!

I noticed that there is no T-icon
![Screenshot 2024-01-22 at 14 45 24](https://github.com/silverbulletmd/silverbullet/assets/6762009/fa74e3d9-8e14-4b8f-ab83-b2cbefaa0314)

**Comment by zefhemel** [comment]
Just removed that. Thanks!
