### ISSUE TITLE
/include no longer work and there is no good alternative

### ISSUE THREAD

**Issue by Qining** [silverbulletmd/silverbullet#649]
`/include` once worked before to 'embed' a page. The slash command also bring up a picker to search for the note to be embedded.

We don't have this anymore since 0.6.0 (or it could be 0.5.11, not very sure).

**Live Template** can partially work as an alternative with:
```
> ```template
>   page: "[[<target page name>]]"
> ```
```

However, the picker triggered by `page: "[[<xxx>]]"` only searches in `#template` pages. So it is not a convenient drop-in replacement of `/include`.

**Comment by zefhemel** [comment]
True. FYI: while the page: attribute for template blocks doesn't complete non-templates you can in fact include any page this way. But it's not as convenient. 

The nicer solution is probably this: https://github.com/silverbulletmd/silverbullet/issues/533

**Comment by Qining** [comment]
Agree! It is just not as convenient. +1 to #533

**Comment by zefhemel** [comment]
As a stop gap, how about I repurpose the `raw` attribute to also support page links, enable page completion there and have the behavior be to do a verbatim (so not template processed) include that way?

**Comment by zefhemel** [comment]
Ok, implemented `raw` as described, which will complete regular pages instead of templates. This will be nicer once I get to #533
