### ISSUE TITLE
Treat Section Headers like anchors (and be objects)

### ISSUE THREAD

**Issue by devzero** [silverbulletmd/silverbullet#650]
Much like Obsidian allows you to link to sections in pages like `[[Page Name#Section Name]]` and is supported by autocomplete and useful for embedding just single sections from page, I think that allowing the # notation added to links (much like @ and $ are for anchors and character locations).  Additionally, I see in a lot of the default documentation a pattern where you have a section header named and then an anchor below it with exactly the same name.  This seems unnecessarily redundant and kind of visually distracting.  Adding header sections as a form of anchor would fix this.  

https://github.com/silverbulletmd/silverbullet/issues/629 is a related issue.  I brought this up on discord and was suggested here.

**Comment by zefhemel** [comment]
I agree, this makes sense. And indeed, I also don’t like the header and anchor pattern that I use right now.

**Comment by dpantel** [comment]
Sorry to poke the dead, but did that commit include suggesting available headers as you are typing, same as it does for pages?
