### ISSUE TITLE
Shortcut for settings?

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#652]
I'm trying to make silverbullet have very similar shortcuts to VSCode

One that I'm stuck with is, how can I configure `ctrl+,` to open the settings page?

I tried adding this in my settings, but it says 
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/e8f57238-5360-453b-8aef-ca88f3c729a8)
```
shortcuts:
- command: '{[Navigate: To Page]("SETTINGS")}'  
  key: "Ctrl-,"
```

**Comment by zefhemel** [comment]
What version are you on? I think I just renamed this command to "Navigate: To Page" today, so it's only on the Edge version so far: https://community.silverbullet.md/t/living-on-the-edge-builds/27

**Comment by zefhemel** [comment]
Ok so actually I didn't rename it, I implemented it new. So there's no command that does this yet in 0.6.0, so you have to switch to Edge or wait until 0.6.1 :)

**Comment by zefhemel** [comment]
This should be resolved since there release
