### ISSUE TITLE
Can `Linked Mentions` be sorted?

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#653]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/cfae974e-7ca1-4e69-8caa-6ce593dc2202)

My `Linked Mentions` look like this, is there a way to sort them?

**Comment by zefhemel** [comment]
Yes, go to the `Library/Core/Widget/Linked Mentions` template (via the Template Picker). In there you'll find a query:

```
query: |
  link where toPage = "{{@page.name}}" and page != "{{@page.name}}"
```

You can add a `order by` clause to that at the end, what would you like to sort by?

**Comment by bilogic** [comment]
Thanks! I would like to sort by title (date) of note

**Comment by zefhemel** [comment]
Ok, that can be done with `order by name` or `order by name desc`.

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/ed77fa48-746f-4fb3-bca2-2006255999e5)

It seems I now have 2 linked mentions, which should be retained for `0.6.0`? And how should I remove the outdated one?
I'm asking because I added `order by toPage` to both, but still not being sorted, i.e. I still get same output as per my OP.

**Comment by zefhemel** [comment]
Yeah, remove the `template/widget/linked-mentions` one simply by navigating to it and running `Page: Delete`

**Comment by bilogic** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/d008296d-b71e-4615-8b0a-6caddc51ef9a)

I have this, but `Linked Mentions` still not being sorted, did I miss something?

**Comment by zefhemel** [comment]
Sorry, it should be `order by page` not `toPage`, `toPage` is always the current page.

**Comment by bilogic** [comment]
Thanks, that worked!
