### ISSUE TITLE
`actionButtons` has no effect on `0.6.0`

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#654]
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/dc1cf3bc-1537-4980-97be-33cf463037fe)

I'm trying to customize my `actionButtons`, but the YAML settings have no effect despite having reloaded. Any idea?

**Comment by zefhemel** [comment]
Yes, not released yet. It's only in the edge builds.

**Comment by bilogic** [comment]
Noted. Not a bug then. Thank you.
