### ISSUE TITLE
Admonition support

### ISSUE THREAD

**Issue by Willyfrog** [silverbulletmd/silverbullet#67]
It would be cool to support [github's admonitions](https://github.com/community/community/discussions/16925)

**Comment by christian-schulze** [comment]
@zefhemel I'd love to work on this. I've started digging through the code-base and existing plugs. I can see the `syntax:` section of a manifest where you can match custom markdown via a regex, but not sure how to hook in custom rendering. Can you give me a push in the right direction here?

**Comment by zefhemel** [comment]
Great! If my understanding is correct this is not actually a syntax extension, it's mostly about presenting existing syntax (block quotes or fenced code blocks) differently.

This is stuff that needs to happen in a CodeMirror plug-in. Here's one for block quotes: https://github.com/silverbulletmd/silverbullet/blob/main/web/cm_plugins/block_quote.ts in that same folder there's also one for code blocks. You'll likely have to special case one of those.

**Comment by zefhemel** [comment]
Obsidian seems to have a popular plug-in that uses fenced code blocks. May also be good to support: https://github.com/valentine195/obsidian-admonition

**Comment by zefhemel** [comment]
Ah no, Obsidian itself has "call out boxes" with again slightly different syntax 😃 great. https://help.obsidian.md/How+to/Use+callouts

**Comment by christian-schulze** [comment]
Awesome, thanks for the links. Will get stuck into this and let you know how I go soon.

Also I think it would be good for this to eventually support different syntax'es as it seems there is not much agreement over which is best.

**Comment by christian-schulze** [comment]
Hi @zefhemel, I've made some progress with this, but have hit a problem. I need to create a `ParseTree` instance from a fragment of raw markdown text, and this can be done via the syscall api like so:
```js
import { parseMarkdown } from "../../plug-api/silverbullet-syscall/markdown.ts";

const t = await parseMarkdown(text);
```
But this is an `async` function, and the CodeMirror `syntaxTree(state).iterate({enter: ...})` api does not support async.

I've attempted to put the contents of the `enter` callback in an async IIFE, but this throws an exception within the `parseMarkdown` function, something to do with the `syscall`:
> Uncaught TypeError: B8 is not a function
>    at j8 (markdown.ts:6:10)

I can push up a WIP pull request if that helps.

**Comment by zefhemel** [comment]
A few things:

There are two "worlds" here: the regular world running JS directly as part of the server or browser with direct access to everything. This is the world of CM extensions like you're building. 

There's also the world of plugs, an isolated, sandboxed environment where you can only do limited things and you access most things through syscalls like the parseMarkdown one you're using here. 

The confusing thing is that both are written in TypeScript and live side by side (almost) in the code base. 

What you're doing wrong here is make a syscall from non-plug code, which will not work regardless of being sync or async. 

Second, what you're iterating through here is a lezer parse tree, which is similar to the psrseMarkdown style parse tree, but only contains positions of syntax nodes, not its actual text directly. You get the text value by slicing it from state.doc 

An example is here: https://github.com/silverbulletmd/silverbullet/blob/850077bad0619d5d321bbcd4ca7589e1d51c5a22/web/cm_plugins/command_link.ts#L28

While it's possible to use parseMarkdown to get that sort of tree, I wouldn't recommend it. I'd just get the syntax tree's node text like in link and pull out the information you need with perhaps a regex. 

That said, if you do really want to get that markdown tree from this environment you can. This is what lezerToParseTree does, an example is here: https://github.com/silverbulletmd/silverbullet/blob/850077bad0619d5d321bbcd4ca7589e1d51c5a22/web/cm_plugins/table.ts#L94

By the way, CM plug-ins always are synchronous so doing async stuff will never be an option.

**Comment by christian-schulze** [comment]
Cheers for the info. One of the reasons I went down this approach is for nested markdown within the admonition, but architecturally this approach won't work as per your explanation.

I'm now approaching things differently. Since the existing `QuoteMark` node already supports nested markdown I'm looking to augment the existing DOM with CSS classes and extra elements for icon and title. This approach looks promising so far, will update you soon.

**Comment by zefhemel** [comment]
Yes, that sounds right to me 👍

**Comment by christian-schulze** [comment]
@zefhemel have pushed a WIP PR, please take a look when you get a chance. #186
