### ISSUE TITLE
FR: add "group by" clause to query language

### ISSUE THREAD

**Issue by devzero** [silverbulletmd/silverbullet#673]
this would be less complex than SQL's group by, but the idea would be, if in your list of result objects you have properties that are commonly redundant and would be grouped together (e.g. a tasks query and grouping by deadline).  The "group by deadline" addition would change the output to be a list of key-value pair instead of a list, where the keys were the unique deadlines, and the value would be the list of results where deadline corresponds to that value.  This would work well with the existing templating engine system and shouldn't change any existing queries.

If multiple fields are specified, it would just add another nesting layer in the query set.  E.g. the query:
task select page, ref, name, deadline group by deadline, priority order by deadline desc, ref asc

might yield a result that looks like:
[{"2024-01-31": [{"TODO": [{"page":"TODO", "ref":TODO@23", "deadline":"2024-01-31", "name":"do thing 1"}]}]}]

This would be addressable with nested {{#each}} helpers and @ key and @ item references in handlebars.  It would be simpler if you didn't get to specify order by on the keyed fields, but then the template language would not be able to re-sort those so you would get random ordering in the output.  An alternative approach might be to allow templates or queries to  launch sub-queries, but that could become an escaping nightmare.

**Comment by devzero** [comment]
No longer necessary with new advanced templates in 0.7

**Comment by zefhemel** [comment]
Well... you can achieve this with nested loops, but I think it may still be interesting to get proper SQL-like "group by" functionality at some point.

**Comment by bjeanes** [comment]
> No longer necessary with new advanced templates in 0.7

Could you elaborate? I'm new to SB but trying to do a group by style query. I could see a nested loops if there were a `unique` verb in the query language, but I haven't discovered this yet, if it exists.
