### ISSUE TITLE
bug evaluating javascript expression in template with index

### ISSUE THREAD

**Issue by devzero** [silverbulletmd/silverbullet#682]
If I have the following template:
```template
{{["hello","world"]}}
```
It displays the string representation of a list of strings.

However, if I try to index into it, this appears to fail and it is not obvious why:
```template
{{["hello","world"][0]}}
```

**Comment by zefhemel** [comment]
What you're writing in between `{{` and `}}` is not JavaScript, it's a custom language detailed here: https://silverbullet.md/Expression%20Language

This language doesn't have the `[0]` indexer syntax right now, instead there's an `at` function: `{{at(["hello", "world"], 0)}}` does what you need.
