### ISSUE TITLE
how is this solution better than trillium notes  and other foss notes /personal knowledge base creation foss solutions?

### ISSUE THREAD

**Issue by HakaishinShwet** [silverbulletmd/silverbullet#699]
trillium has many features and plugins and you can see whole beautiful big memory map plus we can easily and beautiful create things plus filter things. so i want to know it what possible ways is this solutions better than that ? :-))

**Comment by Jurrer** [comment]
What is your problem?

**Comment by zefhemel** [comment]
If you’d like to have this discussion, please start it in https://community.silverbullet.md this is not a bug I can fix.
