### ISSUE TITLE
Backlinks in the RHS

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#7]
It may be helpful to have a mode where the RHS (right-hand side) always shows backlinks to the current page. These are [already indexed](https://github.com/silverbulletmd/silverbullet/blob/d57a9e79dec6d18338d0ab7a3e6726ff29c6db45/packages/plugs/core/page.ts#L47) into a database, so it’s primarily a matter of rendering them in the RHS (and having those links properly work).

**Implementation note:** this can be done very similarly to how [Markdown preview is implemented](https://github.com/silverbulletmd/silverbullet/tree/main/packages/plugs/markdown), likely including how internal links are made to work there (a bit of a hack with target=“_top”).

**Comment by zefhemel** [comment]
Yes, through the page index set of syscalls.

**Comment by Willyfrog** [comment]
https://github.com/Willyfrog/silverbullet-backlinks

**Comment by Willyfrog** [comment]
not yet fully solved, as I filled a couple of issues that need to be resolved to have this marked as complete

**Comment by zefhemel** [comment]
That's cool! I'll give it a try later.

**Comment by Willyfrog** [comment]
Navigation and udpating fixed (if you have a moment can you check if that's the right event to subscribe?), there is probably more that can be done with this, but for now it fixes the requirements in https://github.com/Willyfrog/silverbullet-backlinks/releases/tag/v0.1

**Comment by zefhemel** [comment]
I think we can close this then: https://github.com/Willyfrog/silverbullet-backlinks
