### ISSUE TITLE
Add Powershell Syntax Highlighting

### ISSUE THREAD

**Issue by CyberPenguin** [silverbulletmd/silverbullet#706]
Please could Powershell syntax highlighting be added to codeblocks?

**Reproduce Issue**
1. Insert code block and after the first ``` enter either ps or powershell
2. No syntax highlighting provided

**Comment by zefhemel** [comment]
Should be easy to do. There is a power shell highlighter in legacy modes: https://github.com/codemirror/legacy-modes/tree/main/mode

Which needs to imported here: https://github.com/silverbulletmd/silverbullet/blob/main/common/languages.ts

I can do this after my vacation, but happy to take a PR that adds this.

**Comment by zefhemel** [comment]
On discord somebody asked for diff, may well add that one too while at it. And potentially more languages in that list.

**Comment by zefhemel** [comment]
Great!

**Comment by giovannipollo** [comment]
I think this issue can be closed, since it has been solved!
