### ISSUE TITLE
"Page: Materialize" command (or similar)

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#708]
What this would do is replace any template or query block with its rendered content in place. This content then becomes static and will no longer update and just become part of the page itself. It would be a way to "freeze in time" but also to make it easier to export this content to non-SilverBullet markdown tools.

**Comment by gorootde** [comment]
I wrote a space script that exports a markdown page to PDF. The `Page: Materialize` would be an awesome addition, since dynamic content would become plain markdown and thus also be exportable to PDF.

**Comment by zefhemel** [comment]
Did you share this script anywhere? I'm sure others would like this too.

**Comment by SONDLecT** [comment]
> I wrote a space script that exports a markdown page to PDF. The `Page: Materialize` would be an awesome addition, since dynamic content would become plain markdown and thus also be exportable to PDF.

Yes pls! This is something I'd use all the time. Constantly trying to send notes from SB to normies.

**Comment by gorootde** [comment]
Sure, I just added the PDF export script to my collection: https://github.com/gorootde/silverbullet-collection . See the script's MD file for a description of its dependencies.
