### ISSUE TITLE
Updating nested keys in frontmatter via snippet is broken

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#723]
The (https://silverbullet.md/Snippets#Frontmatter)[Snippets Documentation] states that if a frontmatter is already present, it will be combined with the one already present in the document.

This doesn't work for sub-keys and already existing keys.

**Minimal Example**:
`snippet.md`
```markdown
---
    tags: template
    hooks.snippet.slashCommand: add-alias
    frontmatter: |
       aliases:
          - foobar
---
```

`page.md`
```markdown
---
aliases:
   - someAlias
---
```

`page.md` will only contain `someAlias` after applying the snippet to `page.md`, whereas it should contain `foobar` additionally.

**Comment by zefhemel** [comment]
Yeah, we can do some better object merging here.

**Comment by zefhemel** [comment]
Actually, if you use the `|` notation you'll include frontmatter verbatim as a string. If you pass it in as a YAML object you may get better results. You will have to make sure it's valid YAML though and therefore put quotes around directives, eg `"{{something}}"`

**Comment by gorootde** [comment]
I tried that as well. Deep merging does also not work when using a yank object
