### ISSUE TITLE
Templates in snippets not working when executed as command

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#724]
Snippets executed as command via command palette do not have access to the page meta information, thus the snippet will render e.g. `{{name}}` as `undefined` 

**Minimal Example**:
`snippet.md`
```markdown
---
    tags: template
    hooks.snippet:
        slashCommand: add-title
        command: Add Title
    frontmatter: |
       thePageName: {{name}}
---
```
When executing this via slash command everything works as expected. When executing via command palette, it will render `thePageName: undefined` in frontmatter.

**Comment by zefhemel** [comment]
Can't easily try this, but does it work when you use `{{@page.name}}` instead?
