### ISSUE TITLE
Make tables a queryable object

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#725]
Since tables are somehow already a data structure, why not make them also queryable as a data object?

Proposal for the spec & docs in [`Objects.md`](https://github.com/silverbulletmd/silverbullet/blob/main/website/Objects.md):

> ## table
> Markdown table rows are indexed using the `table` tag, any additional tags can be added using [[Tags]] in any of its cells.
> | Title | Description Text |
> | --- | ----- |
> | This is some key | The value contains a #table-tag |
> | Another key | This time without a tag |
>
> ```query
> table-tag
> ```
This would render the result as

| ref | tag | page | pos | title | description_text | tags
| --- | --- | ---- | --- | --- | --- | ---- |
| someref@23 | table |  ExamplePage |  23 |  This is some key |  The value contains a #table-tag | table-tag |

**Comment by zefhemel** [comment]
I love it. I was thinking of supporting this for CSV embedded in fenced code blocks already, but also doing this for markdown tables makes perfect sense.

**Comment by gorootde** [comment]
Glad you like it. I am going to prepare a PR. Feel free to assign this issue to me.

**Comment by zefhemel** [comment]
Implemented by... you!
