### ISSUE TITLE
Image 404 after moving note to a folder

### ISSUE THREAD

**Issue by filcuk** [silverbulletmd/silverbullet#733]
Embeded image link broken after note is moved to a folder.

Scenario:
- Create `Note`
- Embed `![](face.gif)`
- Move note to `Folder/Note`
- Image now 404's
- Move not to `Note`
- Image works again

Ideally, the link should update or image should move with the note.
It may be good to have the ability to choose what happens by default, or even a prompt when moving notes.

I'm on v0.7.1

**Comment by zefhemel** [comment]
I think this was fixed with #827
