### ISSUE TITLE
Allow multiple auto completion sources (or to register slash commands)

### ISSUE THREAD

**Issue by justyns** [silverbulletmd/silverbullet#742]
I'm not sure if this is a bug or feature request.  

I tried adding `slash:complete` in a plug.yaml like this:

```yaml
functions:
  aiPromptSlashCommplete:
    path: src/prompts.ts:aiPromptSlashComplete
    events:
    - slash:complete
```

And then when start typing a /, I get this error in the js console:

```
client.ts:876 Got completion results from multiple sources, cannot deal with that
completeWithEvent @ client.ts:876

await in completeWithEvent (async)
slashCommandCompleter @ slash_command.ts:97
startQuery @ autocomplete.mjs:2
startUpdate @ autocomplete.mjs:2
(anonymous) @ autocomplete.mjs:2
setTimeout (async)
update @ autocomplete.mjs:2
update @ view.mjs:2
updatePlugins @ view.mjs:4
update @ view.mjs:4
ES.dispatchTransactions @ view.mjs:4
dispatch @ view.mjs:4
h5 @ view.mjs:4
flush @ view.mjs:4
(anonymous) @ view.mjs:4
client.ts:879 Previously had []length: 0[[Prototype]]: Array(0) now also got 
```

Looking at client.ts, it specifically doesn't allow for more than one set of completion results.

Is there another way to accomplish this?  If not, could slashCommandCompleter be enhanced to allow for plugs to return new slash commands?   Or maybe a `registerSlashCommand` for spacescript and plugs to use?

Otherwise right now afaict slash commands are limited to templates with either `hooks.newpage.slashCommand` or `hooks.snippets.slashCommand` defined

**Comment by zefhemel** [comment]
I think you’re approaching this the right way, will look into a fix.

**Comment by zefhemel** [comment]
Could you check if the current `main` fixes this issue for you?

**Comment by justyns** [comment]
Hmm, I tried the latest `main` and get this error now after pressing `/` with the `slash:complete` event reenabled

```
view.mjs:2 TypeError: u.options is not iterable
    at Kb.completeWithEvent (client.ts:895:40)
    at async bg.slashCommandCompleter (slash_command.ts:96:56)
```

This is the aiPromptSlashComplete function I'm using, I think I'm returning the same format as https://github.com/silverbulletmd/silverbullet/blob/main/plugs/template/snippet.ts#L11 :

```
export async function aiPromptSlashComplete(
  completeEvent: CompleteEvent,
): Promise<SlashCompletion[]> {
  const allTemplates = await queryObjects<TemplateObject>("template", {
    filter: ["attr", ["attr", "aiprompt"], "slashCommand"],
  }, 5);
  return allTemplates.map((template) => {
    const aiPromptTemplate = template.aiprompt!;
    console.log("ai prompt template: ", aiPromptTemplate);

    return {
      label: aiPromptTemplate.slashCommand,
      detail: template.description,
      order: aiPromptTemplate.order || 0,
      templatePage: template.ref,
      pageName: completeEvent.pageName,
      invoke: "prompts.insertAiPromptFromTemplate",
    //   invoke: "prompts.insertAiPromptTemplate",
    };
  });
}
```

**Comment by zefhemel** [comment]
Right now I see what's going on. Ok, just pushed another fix which actually changes the return format to be compatible with regular code complete, this involves wrapping results with `options` like here: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/template/snippet.ts#L23

Could you give that a shot?

**Comment by justyns** [comment]
Awesome, I can confirm it works now :) 

thanks!

<img width="639" alt="image" src="https://github.com/silverbulletmd/silverbullet/assets/215985/28660f29-33a3-433f-b2d8-5a65bfacbc56">
