### ISSUE TITLE
Newlines in Markdown are badly rendered 

### ISSUE THREAD

**Issue by brouberol** [silverbulletmd/silverbullet#745]
I've noticed that markdown gets incorrectly rendered when a newline is located just after markdown markup symbols (`**`, `_`, etc).

Here is an simple example to reproduce the issue:

| Template | Rendering |
| -- | -- |
|<img width="724" alt="Screenshot 2024-02-24 at 09 14 54" src="https://github.com/silverbulletmd/silverbullet/assets/480131/db27e61c-acd6-4070-a72c-54a375e2c959"> |<img width="711" alt="Screenshot 2024-02-24 at 09 15 01" src="https://github.com/silverbulletmd/silverbullet/assets/480131/6259a7a9-bb98-4d2f-961b-1a37a8d70382"> |

**Comment by zefhemel** [comment]
Ok I think I fixed this, I hope it doesn't regress other renderings...
