### ISSUE TITLE
Slash commands broken in 0.7.3

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#755]
When typing `/` to execute any slash command, the browser console displays an error and not autocomplete for slash commands is displayed. In 0.7.1 everything was working as expected.

`TypeError: undefined is not a function (near '...a of s...') client.js:127:7158`

**Comment by zefhemel** [comment]
Did you try reloading the page to see if that fixes it? There was an api change and maybe your client files haven't been reloaded.

**Comment by gorootde** [comment]
Thanks for the hint: Deleting and re-installing the PWA did the job. Seems like refresh didn't reload the cached JS.
