### ISSUE TITLE
Poor readability due to negative margins and auto hiding markdown

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#756]
# Problem/Actual
![image](https://github.com/silverbulletmd/silverbullet/assets/946010/59114302-5dc5-4b47-9ddd-ec9ebc05422d)

Why does the `##` have to be to the left of the starting vertical line? It makes it difficult to find where the author intended the headers to be especially when the `##` also hides itself when the cursor is not at that header. The \-\-\- and \`\`\` wrappers also hide themselves when cursor is not on the line, leaving the reader to wonder if they were there

# Expected
The `##` and all user typed markdown should fall inside the left and right boundaries and none of it should ever be hidden. As someone used to reading plain text markdown, I find it very unnatural to read and very challenging to determine where the headers are.  Even though the font sizes are slightly bigger, the many colors distract away from noticing that at first glance.

For a start my suggestion is to align and unhide all user typed markdown

**Comment by zefhemel** [comment]
So the reason it's this way is to reduce text jumping as you move your cursor through it. In the general case this is unavoidable, but in some — like headers — it is. Without this left negative margin, as you move your cursor from above the header, to the header, and then underneath it the header text will jump to the right while the cursor is on it. I found this aesthetically unpleasing, hence this solution.

There is an issue now with very narrow screens that the `##` are actually outside the screen view, which I've been meaning to address.

**Comment by bilogic** [comment]
I don't quite follow the description of "text jumping", is there a video or something for my reference?

The scenarios in my mind are: 

1. Markdown text editing (in VSCode)
2. HTML preview of markdown to a panel on its right
3. I have seen some markdown editors change the font sizes based on the number of `###` at start of line

In all cases above, I don't recall any unpleasant "text jumping".

**Comment by henrikx** [comment]
> I also think point 3 above is a possible solution. Another solution I can think of is the use of animation, this will probably make any "text jumping" more acceptable. (Of course, animation might be a monster to implement)

While I agree that navigating to the `#..` syntax needs to be improved, I disagree that I would ever want to see them when viewing a page.

I think this is another thing that could be solved with a "reading mode" as I described here:
> a read-only mode for desktop which not only keeps the cursor (for navigating inside the document similar to VIM's normal mode), but also hides the underlying markdown while navigating as it is quite distracting to navigate over a link (or other dynamic content) and having the editor switch to the markdown code when the cursor enters formatted text.
https://github.com/silverbulletmd/silverbullet/issues/704#issuecomment-1952308801

**Comment by mxts** [comment]
I suppose you are viewing to read, and not viewing to edit?

It can be quite a challenge to edit something that I can't see.

**Comment by bilogic** [comment]
I suppose you are viewing to read, and not viewing to edit?

It can be quite a challenge to edit something that I can't see.

**Comment by henrikx** [comment]
> I suppose you are viewing to read, and not viewing to edit?
> 
> It can be quite a challenge to edit something that I can't see.

Sorry, indeed yes I should've clarifiied that I meant when I am "viewing to read" and not "viewing to edit".

**Comment by zefhemel** [comment]
This is what I mean with jumping, here I've disabled the negative left margin (which is what you're asking for):

![CleanShot 2024-02-27 at 15 40 13](https://github.com/silverbulletmd/silverbullet/assets/59073/48ae24cf-84a6-4ed3-9547-673ac29eefd7)

and this is the current behavior:

![CleanShot 2024-02-27 at 15 41 19](https://github.com/silverbulletmd/silverbullet/assets/59073/26636abd-71b7-4faa-b1bb-22891021c18f)

See what I mean?

**Comment by zefhemel** [comment]
And yes, this is all related to live preview. Hypothetically I could offer a setting to disable live preview, but that would also require a fair bit of CSS changes that would have to be maintained for both modes, which I don't really have the cycles to do.

**Comment by bilogic** [comment]
Yes, I understand and appreciate your time and efforts spent on this project. Would be possible to at least disable negative margin? Those like me would just have to live with text jumping until live preview can be disabled. :)

**Comment by zefhemel** [comment]
Ok you can use a custom style for this. In your `SETTINGS` file enable custom styles:

```yaml
customStyles: "[[STYLES]]"
```

Then, create a `STYLES` page and put a `css` code block in it:

```css
#sb-main .cm-editor .sb-header-inside {
  text-indent: 0 !important;
}
```

Then reload the page, the text indenting should now stop for headers.
