### ISSUE TITLE
Widget rendering in table of content

### ISSUE THREAD

**Issue by tmichela** [silverbulletmd/silverbullet#759]
# Problem

Any header containing a widget is rendered as raw text in the table of content:

<img width="904" alt="Screenshot 2024-02-27 at 10 01 47" src="https://github.com/silverbulletmd/silverbullet/assets/32831491/35f298a0-abf9-41bb-b7fe-3c3c3506c7b9">

# expected

Show a clickable link to the header section

**Comment by zefhemel** [comment]
Wow, putting a command link a header — yeah that's not something I anticipated people would do 😆

**Comment by tmichela** [comment]
haha, yea that's a bit unorthodox.
I originally had regular headers then I realized 99% of the time I needed to make a `quick note` was on mobile, so having a command on the home page was the most convenient for me.

**Comment by tmichela** [comment]
fixed with #887
