### ISSUE TITLE
Extracting attributes from headers

### ISSUE THREAD

**Issue by zamuz** [silverbulletmd/silverbullet#771]
Attributes can't be extracted from `header` objects when using the `registerAttributeExtractor` API. This is low priority issue in my opinion, but it makes sense for the API to work on `header` tags the same as all other builtin and custom tags. Thank you!

**Comment by zefhemel** [comment]
This should now be fixed (on `main`)

**Comment by zamuz** [comment]
Awesome! That was extremely quick, thank you @zefhemel!
