### ISSUE TITLE
silverbullet 0 cpm 

### ISSUE THREAD

**Issue by abdl1245** [silverbulletmd/silverbullet#776]
i faced a problem with silverbullet that nomatter what i put as a config it and world list it will always be 0 cpm and all data retries and all the proxies go for bad iwill be glad if u helped me solve this problem and after hours the same error

![image](https://github.com/silverbulletmd/silverbullet/assets/162042438/e9b96b3f-9a43-42cd-be91-de2c5a4dd88d)

**Comment by zefhemel** [comment]
Different silver bullet

**Comment by abdl1245** [comment]
how to install the right version?
itryied but i couldnt
