### ISSUE TITLE
native android app?

### ISSUE THREAD

**Issue by dckdck** [silverbulletmd/silverbullet#777]
Hi there,

I like Silver bullet but I cannot use the PWA functionality, since I am not connecting my home server to the internet, local lan/WiFi only.

Locally I can only connect via http and since you can only install a PWA on android when you connect via https, I am not able to use silver bullet offline.

Is there any interest to make this into a native android app at some point or would this go against the principles behind the app?

**Comment by zefhemel** [comment]
Once upon a time there was an Android app (and an iOS app, and an Electron app for Linux, Windows and Mac) but it was too much work for me to maintain and test, so I decided simplify and take the PWA route instead. So far no regrets. 

The question is: do you see no way to still use SSL even within your network? There are ways to do this, one of them is using tailscale as described here: https://community.silverbullet.md/t/install-silverbullet-on-a-64-bit-debian-ubuntu-raspianos-internet-accessible-via-tailscale/48
