### ISSUE TITLE
Parse error when escaping function call

### ISSUE THREAD

**Issue by schroederc** [silverbulletmd/silverbullet#778]
The following template correctly escapes its argument to render `{{today}}`:

```template
{{escape "today"}}
```

The following results in `Parse error in: escape "today()"`:

```template
{{escape "today()"}}
```

The example is silly because you don't need parentheses for function calls without arguments, but it becomes much more of a problem when you want to escape things like `replace(@page.name, "Journal/Date/", "")` in nested templates for widgets.

**Comment by schroederc** [comment]
For simple cases, I've been using the following Space Script as a workaround:

```space-script
silverbullet.registerFunction("escapeCall", (f, ...args) => {
  return "{{" + f + "(" + args.join(", ") + ")}}";
});
```

**Comment by zefhemel** [comment]
The reason the first one works at all is that I made some attempt to be backwards compatible with handlebar helpers. But beyond of the simple cases, this seems to be breaking. So I suggest you use the new function call syntax instead, this should work:
```
{{escape("today()")}}
```

**Comment by schroederc** [comment]
Makes sense.  Thanks 👍  I'll close this since it seems to be a bug only in a deprecated feature.
