### ISSUE TITLE
Headers don't have their extracted attributes stored

### ISSUE THREAD

**Issue by sirlancelot** [silverbulletmd/silverbullet#780]
With the following text in a note:

```
## Header [something: value]

` ` `query
header
where page = @page.name
` ` `
```

I would expect the attribute `something` to be saved to the object. It looks like the attribute is extracted from the `name` value, but the extract property doesn't get added to the indexed object.

**Comment by zefhemel** [comment]
This was just fixed on the main branch but I haven't released this yet. Are you using the edge or release build? https://community.silverbullet.md/t/living-on-the-edge-builds/27

**Comment by sirlancelot** [comment]
Oops sorry for the duplicate. I'm using the release build.

**Comment by sirlancelot** [comment]
Duplicate of #771
