### ISSUE TITLE
Specifying `ctrl-q` in settings has no effect

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#784]
1. `ctrl-q` could not be captured in my SB when using Chrome Version 122.0.6261.95 (Official Build) (64-bit) on Windows 10
2. In fact, adding it breaks all my other shortcuts in SB, i.e. they also no longer have any effect
3. I worked around this for now by changing `ctrl-q` to `ctrl-1`

I have checked that none of my Chrome extensions are in the way

**Comment by zefhemel** [comment]
If you imported the `Library/Core/Snippet/Task` template (and you probably did), this is bound to the `Ctrl-q t` keyboard shortcut. Whenever any command does this, it's reserving (in this case) `Ctrl-q` for use as a sequential keyboard shortcut and you can no longer use it for anything else. What you can do is either remove this template or, change (or remove) the shortcut in this template.
