### ISSUE TITLE
Silverbullet broken on firefox 102.14.0esr (64-bit)?

### ISSUE THREAD

**Issue by gardiol** [silverbulletmd/silverbullet#795]
Looks like latest SilverBullet does not work on Firefox.

Error: SyntaxError: export declarations may only appear at top level of a module..

This is the stack:
```
Booting SilverBullet client in Sync Mode [boot.ts:8:10](https://silverbullet.md/web/boot.ts)
Running in read-only mode [boot.ts:14:12](https://silverbullet.md/web/boot.ts)
Service worker registered... [boot.ts:32:14](https://silverbullet.md/web/boot.ts)
Rebuilding editor state [client.ts:830:12](https://silverbullet.md/web/client.ts)
Reading file content from fallback for SETTINGS.md 2 [fallback_space_primitives.ts:26:16](https://silverbullet.md/common/spaces/fallback_space_primitives.ts)
Loading plugs [client_system.ts:210:12](https://silverbullet.md/web/client_system.ts)
(Re)loading plugs [client_system.ts:213:12](https://silverbullet.md/web/client_system.ts)
Booting up worker for emoji [worker_sandbox.ts:33:12](https://silverbullet.md/lib/plugos/sandboxes/worker_sandbox.ts)
SyntaxError: export declarations may only appear at top level of a module
```

this on Firefox 102.14.0esr (64-bit) (linux), on Chrome it works.

**Comment by zefhemel** [comment]
Ok, this could be. But from what I can tell this is a release from June 2022 https://www.mozilla.org/en-US/firefox/102.0/releasenotes/ I’m not sure it’s worth investing a lot of time in attempting to support almost 2 year old browsers. Upgrading your firefox is not an option?

**Comment by gardiol** [comment]
You are right, upgraded to 106 and it works! Didn't notice the browser was so old.
