### ISSUE TITLE
SB_AUTH_TOKEN without SB_USER

### ISSUE THREAD

**Issue by aorith** [silverbulletmd/silverbullet#799]
At this moment, the authorization code does the following:

```typescript
      if (!spaceServer.auth) {
        // Auth disabled in this config, skip
        return next();
      }
```

This makes it impossible to only enable `SB_AUTH_TOKEN` without `SB_USER` (or the flag `--user`). So someone could think that the API is protected when it's not since it requires the basic auth enabled.

**Comment by zefhemel** [comment]
Good point. Will fix.
