### ISSUE TITLE
No folder specified. Please pass a folder as an argument or set SB_FOLDER environment variable. ERORS

### ISSUE THREAD

**Issue by sayit135** [silverbulletmd/silverbullet#810]
No folder specified. Please pass a folder as an argument or set SB_FOLDER environment variable.

**Comment by sayit135** [comment]
![image](https://github.com/silverbulletmd/silverbullet/assets/35692406/54298a01-7eaf-45a9-8782-6c1677410ac1)
CLOSED

**Comment by zefhemel** [comment]
How are you running this? You need to run it from the command prompt, and pass in a folder pointing to a folder where your markdown files will be kept as an argument. Simply double clicking the .exe won't work (which you may be doing).

**Comment by sayit135** [comment]
I don't understand. Can you help me?

**Comment by sayit135** [comment]
> How are you running this? You need to run it from the command prompt, and pass in a folder pointing to a folder w

https://github.com/silverbulletmd/silverbullet/issues/810#issuecomment-2002016426

**Comment by zefhemel** [comment]
Ok this is not helpful, looking at your GitHub profile I think you're looking at the wrong repository. Let me know if I'm wrong. Closing this.
