### ISSUE TITLE
Query Support for Absence of Attributes in Tasks and Notes

### ISSUE THREAD

**Issue by simone-viozzi** [silverbulletmd/silverbullet#814]
Implement the ability to query tasks and notes in SilverBullet based on the absence of certain attributes, such as `due` or `priority`. 

This functionality would allow users to identify items needing additional information or categorization more efficiently.

## Use Cases

- Task Management: Identifying tasks that haven't been assigned a due date to ensure no task is overlooked in planning.
- Content Categorization: Finding notes that are missing specific attributes for a thorough categorization process.

## Proposed Solution

Extend the SilverBullet query language to include syntax or operators that allow querying based on the absence of specified attributes. This could be through a straightforward syntax like `not attribute "due"` or through a more flexible query modifier that specifies missing attributes.

**Comment by simone-viozzi** [comment]
I found a way:

```query
task select due, priority, name where ((due = null) or (priority = null)) and done = false render [[Library/Core/Query/Task]]
```

**Comment by zefhemel** [comment]
Simply eg `not due` will also work.
