### ISSUE TITLE
{[Open Daily Note]} doesn't open a new note when running after midnight

### ISSUE THREAD

**Issue by hanzei** [silverbulletmd/silverbullet#83]
Running `{[Open Daily Note]}` after midnight does not open a new page but instead the page of the past day.

Maybe wait until 1 AM solves the issue. But I need sleep :sleeping:

**Comment by zefhemel** [comment]
Interesting, and your server's clock is in sync with your local time?

**Comment by hanzei** [comment]
Yes. In fact, the server runs on the same machine as the browser.

**Comment by hanzei** [comment]
`/today` is also effected by this issue.
