### ISSUE TITLE
Feature Request: Add options for PWA manifest customisation

### ISSUE THREAD

**Issue by s1gnate-sync** [silverbulletmd/silverbullet#838]
To be able to distinguish between multiple instances of silverbullet.

I think it would be great if certain non-critical fields of manifest.json will be customizable:
- short_name
- name
- icon
- description

Use-case:
- I have installed silverbullet PWA from official website (for documentation) and also hosted my own 
- It's impossible to distinguish between two instances as name and icon are the same.

**Comment by s1gnate-sync** [comment]
I can provide a pull-request if you think it's worth implementing :)

**Comment by zefhemel** [comment]
This would be nice, but how would you imagine configuring it?

**Comment by s1gnate-sync** [comment]
I see two options:
1. serve it dynamically
2. generate static version 

and yeah I'm talking only about self-hosted

**Comment by s1gnate-sync** [comment]
[

**Comment by zefhemel** [comment]
Yeah, I was also thinking of the SETTINGS option, but then it needs to be quite dynamic and that may be tricky. Another option would be to make it configurable via environment variables on the backend and use those when serving the manifest fil.
