### ISSUE TITLE
Space Script documentation does not list all syscalls

### ISSUE THREAD

**Issue by daniel-michel** [silverbulletmd/silverbullet#839]
The documentation for [Space Script](https://silverbullet.md/Space%20Script) does not list all syscalls. It uses a query to list the syscalls, however as mentioned in #824, this does not include all syscalls which makes the documentation confusing. Also the list of syscalls in the documentation changes when activating sync mode.

**Comment by daniel-michel** [comment]
I guess since, as discussed in the other issue #824, the behavior of the query should not change. It might actually be a solution to mention that sync mode has to be enabled to show client side syscalls. Although that does not seem like a very satisfying solution.

**Comment by zefhemel** [comment]
Yeah, not sure what to do here. I added this query source as a "hey, this is a fun way to self document" not really taking into consideration the client/server-side only calls. Perhaps it would just be better to document syscalls from the source code (JS-Doc style) rather than in this way.

**Comment by daniel-michel** [comment]
This is fixed by e293525. The [Space Script](https://silverbullet.md/Space%20Script) page now links to the documentation on [jsr.io](https://jsr.io/@silverbulletmd/silverbullet/doc/syscalls/~).
