### ISSUE TITLE
Migrate to Deno

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#84]
I'm quite unhappy about the build, bundling and package management mess in Silver Bullet right now. It somehow works, but as they say "you don't want to know how the sausage is made." 

Right now we use a mix of various build tools:

* ParcelJS for building the frontend, tests and server code (we need to do some compilation even on the server because node.js doesn't support typescript natively) with a bunch of hacks.
* ES Build for building plugs

We constantly need to run a slew of watchers and continuous builds during development, which... again, works but isn't great.

I've been using [Deno](https://deno.land/) in the past (in fact a super early version of SB used Deno for the server side) and it brings a few things to the table that I really like:

* "Native" typescript support, no compilation required
* No more npm (it uses URL based imports instead)
* Opinions on: code formatting (`deno fmt`), docs (`deno doc`), code rules (`deno lint`) and a whole slew of other tools built in
* Bias towards web based standards (not node.js specific legacy)
* Easy distribution (you can easily build you entire system into a single binary, Go-style)
* Great support for webassembly, allowing to use e.g. SQLite without requiring platform-specific code

For the front-end we'd still use ESBuild (but run through Deno).

I've currently already started this work on the `deno` branch. In many ways this will break stuff, specifically plugs, but probably in easy to fix ways. I'll issue PRs to all external plug repos after the "damage was done."

It's not guaranteed this will work out perfectly, but I want to do the work as an exercise anyway.

**Comment by jimt** [comment]
- [ ] update https://silverbullet.md/%F0%9F%94%A8_development/
