### ISSUE TITLE
RegisterAttributeExtractor doesn't seem to work

### ISSUE THREAD

**Issue by montarion** [silverbulletmd/silverbullet#844]
I copied the example from here: https://silverbullet.md/Space%20Script#Custom%20attribute%20extractors

I changed it to filter to be custom task for this MVP:

```js
\```space-script
silverbullet.registerAttributeExtractor({tags: ["testtask"]}, (text) => {
  // This is an MVP after all
    return {
      name: "I'm not here...",
      completed: "oops",
      noshadows: "nothing here either"
    };
  }
});
\```
```

I then create a task:
- [ ] #testtask this should have extra attributes

reindex using the `Space: Reindex` command, wait for it to complete, reload the page, and refresh the query for:

```query
testtask
```

Which returns:

|ref|tag|name|done|page|pos|state|tags|itags|
|--|--|--|--|--|--|--|--|--|
|misc/todolist@217|task|this should have extra attributes|false|misc/todolist|217| |testtask|task, testtask|

I expected 2 new attributes, 'completed' and 'noshadow'. I also expected the 'name' attribute to have changed into "I'm not here..."

What am I missing?

**Comment by deepkn** [comment]
@montarion Were you able to get this to work? I'm seeing the same issue.
@zefhemel Tried the steps you suggested - but the attribute extractor does not seem to be getting invoked. I can see it being picked up when spacescript.ts runs but post that, it does not seem to be getting invoked. Tried adding a console.log() inside the function body and tried both online mode and sync mode, but it does not show up in either side. I could very well be missing something obvious - but any more ideas I can try? I don't see any errors in server side logs as well as in JS console. PS: I'm running edge.
