### ISSUE TITLE
Docker image crashing on start

### ISSUE THREAD

**Issue by jibweb** [silverbulletmd/silverbullet#851]
I tried running silverbullet using the docker install, and got a crash on start:

```
deno run -A --unstable-kv --unstable-worker-options /silverbullet.js      


#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe93949e60Aborted (core dumped)
```

The image ID is f70caebd6d8b if that helps. I am a little lost as to why, or even how to give more useful informations for debug

**Comment by zefhemel** [comment]
Can you tell me a bit about your environment? Could lack of memory be an issue? 1GB of RAM would be good to have.
