### ISSUE TITLE
ERROR in block REQUEST

### ISSUE THREAD

**Issue by Diablo22112131** [silverbulletmd/silverbullet#855]
hey i am just new to this, few days ago everything was working fine in silverbullet i have config for xbox and i used it in the past week everything was perfect i was getting hits and even custom too but now i only getting (bad) hits while i am so sure there's a lot of hits and working accounts, here's the silverbullet log errors
(https://github.com/silverbulletmd/silverbullet/assets/168175859/865ec1f3-5749-427a-8137-27903c28de46)
i always updating the proxies (HTTP) i am using more than 50 i dont know if it's a proxy problem
sorry for bothering 
and thanks

**Comment by zefhemel** [comment]
I'm a bit confused. You're sure you're posting to the right repo, right? You're using silverbullet.md the notes app? I don't recognize anything from these logs, I see references to SOCK proxies and requests to google that make no sense.
