### ISSUE TITLE
`<url>` is clickable, but doesn't do anything when clicked

### ISSUE THREAD

**Issue by honnip** [silverbulletmd/silverbullet#856]
According to commonmark spec (https://spec.commonmark.org/0.31.2/#autolink), `<uri>` is be parsed as link.

On silverbullet, it is clickable, but doing nothing when clicked.

![image](https://github.com/silverbulletmd/silverbullet/assets/108175486/52e54994-b266-4a76-8666-05d6f692735a)

**Comment by zefhemel** [comment]
Didn't even realize this as a thing. Indeed this isn't currently implemented.
