### ISSUE TITLE
Can't Import Core Library

### ISSUE THREAD

**Issue by STSMHQ** [silverbulletmd/silverbullet#870]
Hi, so I found Silverbullet recently and I wanted to give it a try as I liked very much the [demo](https://youtu.be/8btx9HeuZ4s). I installed it using the [deno process](https://silverbullet.md/Install/Deno), but I'm unable to load/import the Core Library:

> When I click on **Import Core Library**, in the pop-up that appears, it shows **0 templates**:
> 
> ![image](https://github.com/silverbulletmd/silverbullet/assets/94048176/27a8f501-9a74-4d70-9cde-9f249f8cda77)

> Also, even from the [`Library: Import`](https://silverbullet.md/Library/Core) command, the same happens:
> 
> ![image](https://github.com/silverbulletmd/silverbullet/assets/94048176/518f456b-3fcf-478b-a417-4c9b0f3e341b)
> ![image](https://github.com/silverbulletmd/silverbullet/assets/94048176/ce1675d0-df63-432d-90ee-67265b43a0a4)

> Thus, I can't use the slash commands either:
> 
> ![image](https://github.com/silverbulletmd/silverbullet/assets/94048176/ed019216-28ad-4214-886f-7d385ab94659)

I would like to ask for your help solving this problem. Thank you in advance!

**Comment by zefhemel** [comment]
This is very odd. Can you open your browser's JavaScript console and see if there's any obvious hints there showing what may be going wrong? Errors, warnings? Or in the server logs perhaps?

**Comment by zefhemel** [comment]
Ok hang on, something broken on the server side. Looking into it.
