### ISSUE TITLE
Follow OS theme (dark/light)

### ISSUE THREAD

**Issue by pihentagy** [silverbulletmd/silverbullet#871]
I've seen on https://developer.mozilla.org/
![Recording 2024-05-29 at 09 15 47](https://github.com/silverbulletmd/silverbullet/assets/29916/782d22e9-cd31-4228-88f7-4f6d47b48257)

**Comment by zefhemel** [comment]
Same as #481 right?

**Comment by pihentagy** [comment]
Well, searched for `theme` among the issues, that's why I could not find.
