### ISSUE TITLE
Feature Request: Erlang/Elexir langauge mode for syntax highlighting

### ISSUE THREAD

**Issue by MrMugame** [silverbulletmd/silverbullet#875]
Basically title.
### Erlang
There is a language mode for elexir in the [legacy package](https://www.npmjs.com/package/@codemirror/legacy-modes), so that would just be
```ts
import { erlang as erlangLanguage } from "@codemirror/legacy-modes/mode/erlang?external=@codemirror/language&target=es2022";
...
"erlang": StreamLanguage.define(erlangLanguage),
```
in [common/language.ts](https://github.com/silverbulletmd/silverbullet/blob/main/common/languages.ts)
### Elixir
So this is a little harder, there is a [package](https://www.npmjs.com/package/codemirror-lang-elixir) for elixir, but it is a separate ... package. It just exports `elixirLanguage` so using it would be easy too.

**Comment by MrMugame** [comment]
Just did some testing and adding the elixir package increases the bundle size from `2056KiB` to `2364KiB` and the erlang package only then increases the bundle size to `2372KiB`. In my opinion a `+14%` in bundle size for one language mode is a little insane. Erlang is no problem, but IDK what your opinion is on elixir that.
An alternative would be to load the language modes using dynamic `import()`s or to switch to more lightweight libraries like highlight.js

**Comment by MrMugame** [comment]
Another Idea would be to completely separate the syntax highlighting into plugs. This way there could be one builtin plug with the most basic stuff and everything else is opt-in.

**Comment by zefhemel** [comment]
Yes, but this would also require extending the capability of plugs significantly. They cannot extend the parser now.
