### ISSUE TITLE
deno run fails

### ISSUE THREAD

**Issue by hanzei** [silverbulletmd/silverbullet#88]
```bash
deno run -A --unstable https://get.silverbullet.md .
Pages folder: /some/path/silverbullet-notes
Silver Bullet is now running: http://localhost:3000
--------------
Loading plugs [
  "_plug/markdown.plug.json",
  "_plug/query.plug.json",
  "_plug/tasks.plug.json",
  "_plug/emoji.plug.json",
  "_plug/core.plug.json",
  "_plug/plugmd.plug.json",
  "_plug/tasks.plug.json",
  "_plug/github.plug.json",
  "_plug/plugmd.plug.json",
  "_plug/query.plug.json",
  "_plug/backlinks.plug.json",
  "_plug/emoji.plug.json",
  "_plug/core.plug.json",
  "_plug/markdown.plug.json",
  "_plug/git.plug.json"
]
Loading markdown
error: Uncaught (in worker "") Module not found "file:///Users/zef/git/silverbullet/plugos/environments/sandbox_worker.ts".
error: Uncaught Error: Unhandled error in child worker.

```

I'm running 
```
deno --version
deno 1.26.1 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.3
typescript 4.8.3
```

**Comment by hanzei** [comment]
Or is the feature just not ready yet?

**Comment by zefhemel** [comment]
Oh this is interesting, it seems it's hard coding my local path into the bundle. I'll look into how to fix that. Running it using the development instructions should work though.

**Comment by zefhemel** [comment]
Note to self: https://github.com/denoland/deno/issues/12276

**Comment by zefhemel** [comment]
@hanzei this should now be fixed, could you try again?

**Comment by zefhemel** [comment]
Note after this other things may still break, also have a look at https://silverbullet.md/changelog/ Some plugs may not work out of the box, especially external ones.

**Comment by hanzei** [comment]
> @hanzei this should now be fixed, could you try again?

It's still broken. And the error message is the same.

**Comment by hanzei** [comment]
Another issue that I found is that ` Open Daily Note` is broken. The command just does nothing.

**Comment by zefhemel** [comment]
Ah you probably are using the locally cached version, can you run it with the `--reload` flag?

```shell
deno run --reload -A --unstable https://get.silverbullet.md .
```

**Comment by zefhemel** [comment]
Regarding the daily note, where are you checking this? Because if SB isn't properly starting nothing will work. The Open Daily Note command works fine for me.

**Comment by hanzei** [comment]
> Ah you probably are using the locally cached version, can you run it with the `--reload` flag?
> 
> ```shell
> deno run --reload -A --unstable https://get.silverbullet.md .
> ```

That did the trick, thanks :+1: Caching as indeed the issue.

**Comment by hanzei** [comment]
> Regarding the daily note, where are you checking this? Because if SB isn't properly starting nothing will work. The Open Daily Note command works fine for me.

SB runs now, the command still does not work. There is nothing in the logs.
