### ISSUE TITLE
Minor typo on website

### ISSUE THREAD

**Issue by Tagirijus** [silverbulletmd/silverbullet#881]
There is a typo on the website: _"shoud"_ instead of _"should"_ here:

https://github.com/silverbulletmd/silverbullet/blob/ff923b87187d6f61e20240a2326ff5980759e0c7/website/Live%20Queries.md?plain=1#L14

Cheers!

**Comment by zefhemel** [comment]
Yep, thanks!

**Comment by Tagirijus** [comment]
Glad I could help a little. More thanks to you for this great app, though! (;
