### ISSUE TITLE
[Question] Record failed authentication in logs for fail2ban or other access control.

### ISSUE THREAD

**Issue by showgood163** [silverbulletmd/silverbullet#883]
Hi there,

I want to put my silverbullet instance on Internet for convenient access.
Because I'm in an untrusted network environment, I want to record failed authentication in logs for fail2ban or other similar programs to identify and prevent abuses by banning IPs.
However, with username-passward authencation enabled, I see no login failure in logs after I typed wrong username and password.
Is there a way to record failed authentication in logs?

**Comment by zefhemel** [comment]
I just added a log message for this: "Authentication failed, redirecting to auth page"

**Comment by showgood163** [comment]
Could you make the log reflect the IP so that fail2ban can work?

**Comment by zefhemel** [comment]
I assumed it would be easy, but it seems surprisingly hard to determine the remote IP.

**Comment by showgood163** [comment]
Alright, just take your time.

**Comment by aorith** [comment]
At this moment, I'm using this filter with Caddy in front of Silverbullet:

```
[Definition]
failregex = ^.*"remote_ip":"<HOST>",.*?auth\?error=1".*$
```

Since a bad authentication triggers a redirect to `/.auth?error=1`.

I don't see why you would expose a password-protected Silverbullet instance without TLS termination.
Caddy/Nginx etc will also take care of logging the IP address.

**Comment by showgood163** [comment]
Thanks for the input. Will report back when I have time to test that.

**Comment by showgood163** [comment]
I'm running Caddy v2.7.6 and silverbullet v0.7.7.

Caddy is set to reverse proxy the silverbullet server with https/tls.
Caddy log level is set to INFO.

I enter wrong username and password, see the redriction to `.auth?error=1` in address column in browser, but I didn't see any caddy logs to indicate there is a redirection.

Can you show me how you did that?

**Comment by aorith** [comment]
I'm running the same Caddy version with the following configuration for Silverbullet which is running at port 3000:

```
mydomain.example.com {
        tls myemail@email.com
        bind 0.0.0.0

        log notes {
                level INFO
                format json
                output file /var/log/caddy/notes.log {
                        roll_size 50MiB
                        roll_keep 10
                        roll_keep_for 196h
                }
        }

        reverse_proxy 127.0.0.1:3000 {
                header_down Strict-Transport-Security max-age=31536000;
        }
}
```

So it saves the log as json at `/var/log/caddy/notes.log`.
When a wrong username/password is entered I see something like this:

```json
{"remote_ip":"XX.XX.XX.XX","remote_port":"38928","client_ip":"XX.XX.XX.XX","proto":"HTTP/2.0","method":"GET","host":"mydomain.example.com","uri":"/.auth?error=1","headers":  . . . . .
```

And that does match with the regex for fail2ban: `^.*"remote_ip":"<HOST>",.*?auth\?error=1".*$`

**Comment by showgood163** [comment]
Hi there,

With your caddy configuration, I'm able to get records for redirection. The only problem is that I keep one webpage open for silverbullet all the time and the log file gets large very quickly. I'll see what I can do to manage that.

Thanks.

**Comment by aorith** [comment]
You can put the following after the `log` block to only log requests that start with `/.auth`:

```
        # Skip logging requests that do not start with '/.auth', caddy (go) regexp does not support negative lookaheads
        @logMatcher {
                not {
                        path_regexp ^/\.auth.*$
                }
        }
        # Will be renamed to log_skip on >= 2.8.0
        skip_log @logMatcher
```

**Comment by showgood163** [comment]
Hi there,

Yes, your log filter works as intended. I consider silverbullet behind caddy on public internet usable for now.

Thanks.
