### ISSUE TITLE
Stay on last opened document instead of index

### ISSUE THREAD

**Issue by bilogic** [silverbulletmd/silverbullet#888]
I have an index page defined, so each time I open my SB, it goes to the index page.

But what I would prefer is to have my last page restored so that I can easily pick up where I left off. Possible?

**Comment by zefhemel** [comment]
I had this implemented in the PWA but it regressed, I just implemented it again. The PWA does by default is not go to your SilverBullet root URL, but to the root URL with `#boot` at the end, so e.g. `https://notes.bla.com/#boot` When you visit that URL (which you can also bookmark in your browser), it will automatically go to your last opened page.

**Comment by bilogic** [comment]
thanks it works!
