### ISSUE TITLE
Firefox loading issue

### ISSUE THREAD

**Issue by ushills** [silverbulletmd/silverbullet#892]
I have tried to open https://silverbullet.md in Firefox ESR on Debian Bookworm and the home page loads for about < 1 second and the home page text is visible, then when the menu bar appears so does all the text and it remains blank.

When using Chromium the text reappears after the table of contents appears and the site functions correctly.

**Comment by zefhemel** [comment]
What's the version of this Firefox? Debian tends to distribute quite old versions and SilverBullet adopts fairly cutting edge browser features.

**Comment by cwross** [comment]
Also check your plugins for things such as adblockers, etc. I noticed the DuckDuckGo Privacy Essentials plugin breaks the page, and I had to disable it.

**Comment by ushills** [comment]
> Also check your plugins for things such as adblockers, etc. I noticed the DuckDuckGo Privacy Essentials plugin breaks the page, and I had to disable it.

Thanks, both, the DuckDuckGo plugin was the issue, and I have confirmed that disabling this allows Silverbullet to work with both Firefox-ESR and Firefox latest from Mozilla on Debian

**Comment by ushills** [comment]
Issue closed
