### ISSUE TITLE
Typing a " or ' when text is selected, should surround the text with these quotes

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#896]
This is how it works with brackets, but not quotes yet.

**Comment by MrMugame** [comment]
Btw, what's the reason for actually replacing the characters with the special unicode characters rather than just rendering them differently?

**Comment by zefhemel** [comment]
How would you just render them differently? Ah, you mean in the editor? Good question actually, never considered that option.

**Comment by zefhemel** [comment]
That would be another way to approach this. What I would want, then, is that when copy & pasting (or sharing) content, they'd be copied in the "curly" form, if that makes sense. So not sure that would be worth reimplementing in the editor.

**Comment by MrMugame** [comment]
For me not copying those unicode characters would actually be the reason to implement it further down. I guess there are different needs/expectations here.
