### ISSUE TITLE
Fix full text search

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#90]
With the transition to Deno, things now run on a SQLite build without fts5 support. Two options:

1. Move to a different SQLite build (possibly even a web assembly one) with FTS compiled in
2. Implement full-text search in some other way

**Comment by zefhemel** [comment]
l https://github.com/nextapps-de/flexsearch

**Comment by yorrd** [comment]
@zefhemel this does work, but it's case sensitive and doesn't seem to be very flexible with partial words. Should I open a separate issue for this?

**Comment by zefhemel** [comment]
Yes please
