### ISSUE TITLE
Need a way to link to today's note

### ISSUE THREAD

**Issue by genotrance** [silverbulletmd/silverbullet#916]
I tried `[[Journal/Day/{{today}}]]` but it does not work. I also tried embedding:

```
```template
page: "[[Journal/Day/{{today}}]]"
```

That doesn't work either. Only way to get to the note is with Alt-shift-d.

**Comment by zefhemel** [comment]
~~~
```template
[[Journal/Day/{{today}}]]
```
~~~

Should work though?
