### ISSUE TITLE
"Page: Force Create Under Cursor" command

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#919]
Not an amazing name, but this command should create the page under the cursor. For instance, when the user puts their cursor in the context of `[[nonexisting page]]` and runs this  command, this page would be created with empty content (or using any page templates configured for the pattern) and turn "blue" immediately.

**Comment by montarion** [comment]
doesn't [[linking]] to a page already do this?

I think it'd make more sense to have that use autocomplete
![image](https://github.com/user-attachments/assets/e78573c0-945a-4664-a47e-177963d47e27)

**Comment by zefhemel** [comment]
It's only physically created on disk once you navigate there and type something in it.

**Comment by meain** [comment]
Just a comment on the name. The word `Force` might be confusing (it was for me). Just `Page: Create Under Cursor` would do IMO.

**Comment by zefhemel** [comment]
Honestly, I think we're going to go another way. This is the deeper issue that needs to be addressed: #154
