### ISSUE TITLE
Bug: Query on date attribute doesn't work as expected

### ISSUE THREAD

**Issue by gorootde** [silverbulletmd/silverbullet#922]
Given this page:

```markdown
- First [date: 2024-07-08]
- Second [date: 2024-07-07]
```
Query:
`item where date = '2024-07-08'`

I'd expect that the query returns `First`. However, it does return no result at all. If I use the same query for selecting pages that contain a date as frontmatter attribute, it works as expected. Seems like selecting date attributes behaves differently than dates stored in other locations.

**Comment by zefhemel** [comment]
I just fixed this for frontmatter here: https://github.com/silverbulletmd/silverbullet/commit/2eb7e25854000090bdb3a8729aed3c3c1f06e381

Let me also apply that to inline attributes.

**Comment by zefhemel** [comment]
The issue here is that YAML parses strings of a date-like format as a JavaScript date, not as a string. A workaround is to put quotes around it: `[date: "2025-08-01"]`
