### ISSUE TITLE
Improve PWA navigation

### ISSUE THREAD

**Issue by jkjustjoshing** [silverbulletmd/silverbullet#933]
I have Silverbullet installed as a PWA on MacOS, and the browser forward/back buttons are missing. We should make it easier to go forward/back when installed as a PWA.

This is a request for desktop PWA navigation support, not mobile PWA support as discussed in #686.

I'd love to see one or both of the following implemented:
* `⌘ + ←` and `⌘ + →` keyboard shortcuts to navigate forward and back in history (to match web browsers)
* A thin top bar with forward/back buttons above the current UI, only visible when installed on a PWA on desktop (either detect device, or only show above certain screen widths). I know screen real estate is limited on mobile, but for desktop PWA this seems like a valuable UI to have.

**Comment by zefhemel** [comment]
The default browser keyboard shortcuts for back and forth navigation work though, right? I use them all the time.

**Comment by jkjustjoshing** [comment]
Ah, those do work, yes. My muscle memory is cmd+arrow, but those only work when there's no text input selected (which Silverbullet always has).

I can live with the existing ones!
