### ISSUE TITLE
Large while space above table when there are spaces in table columns

### ISSUE THREAD

**Issue by oneryx** [silverbulletmd/silverbullet#936]
For markdown like this, I would expect the second table is rendered the same as the first one, as those white spaces in columns should be ignored.

```
# Title
|Header1|Header2|
|---|---|
|123|456|
|123|456|

# Title
|Header1                             |Header2                                              |
|---                                 |---                                                  |
|123                                 |456                                                  |
|123                                 |456                                                  |
```

While silverbullet renders the second table with a huge white space above, as below screenshot.

![image](https://github.com/user-attachments/assets/acfb0300-ffc1-498c-ac9d-976cee2f5a02)

Some markdown editors format the table code like above to align those pipes to be beauty, but the rendered result looks bad in silverbullet.

The more rows, the larger the while space BTW.

![image](https://github.com/user-attachments/assets/1b09b142-bf64-4bfd-a1d6-7255bf60b00b)

**Comment by zefhemel** [comment]
Is this the same issue as this? https://github.com/silverbulletmd/silverbullet/issues/793
