### ISSUE TITLE
[Firefox] CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet

### ISSUE THREAD

**Issue by damufo** [silverbulletmd/silverbullet#944]
Hello:
I run with Docker,  current Silverbullet version
Firefox esr and release channel nothing show, attach console messages.
Chromium work fine

![imaxe](https://github.com/user-attachments/assets/ae887dd9-314a-4b69-9ebb-4c8a52964914)

Very thanks.

**Comment by zefhemel** [comment]
Is this the same as https://github.com/silverbulletmd/silverbullet/issues/850 ?

**Comment by zefhemel** [comment]
This should now be resolved
