### ISSUE TITLE
Links inside `!silverbullet.md/Getting Started` transclusion are broken

### ISSUE THREAD

**Issue by bjeanes** [silverbulletmd/silverbullet#967]
See the status bar here for the URL that hovering over "Libraries" links to:

<img width="985" alt="image" src="https://github.com/user-attachments/assets/e064c3d0-5d45-49d9-8838-a4d32405c782">

By comparison, if the `!silverbullet.md/Getting Started` page is viewed directly, the links are intact, and properly namespaced:

<img width="985" alt="image" src="https://github.com/user-attachments/assets/8358d59d-8bed-4c05-adcd-25bd832f0646">

This is on latest Docker image, set up about an hour ago, with a fresh empty space.

**Comment by zefhemel** [comment]
Oh yeah. Before transclusions based onboarding this used to work. Let me have a look.

**Comment by bjeanes** [comment]
It looks like a lot of the query based examples are also broken (but not all?)
