### ISSUE TITLE
Page decorations not rendered in query results for Pages in directories

### ISSUE THREAD

**Issue by jamescooke** [silverbulletmd/silverbullet#970]
## Current behaviour

Running 0.8.2 docker image, page decorations don't render correctly in queries where resulting Pages are in directories.

For example, with a setting that sets a person in an office decoration for a Page about working practices:

```yaml
pageDecorations:
- where: 'tags = "guide_working"'
  prefix: "🧑‍💼🏢 "
```

Given there are two pages:

`Test testing.md` in the root:
```text
#guide_working

I just like tests
```

And `guides/Test Scrum.md` in the `guides` dir:
```text
#guide_working

Does Scrum even?
```

Then, when we write a query in a page:
```text
page
where tags = 'guide_working'
render [[Library/Core/Query/Page]]
```

The following is rendered as:

![Screenshot from 2024-07-22 15-53-08](https://github.com/user-attachments/assets/6382d397-eb4e-4a6a-b63e-59810a452781)

The core query page template is default as per: https://github.com/silverbulletmd/silverbullet/blob/1635c417c3d925ff0766756eb5b063d8233878f4/website/Library/Core/Query/Page.md

## Expected behaviour

The "🧑‍💼🏢 " prefix is shown for _both_ Pages, not just the one in the root.

**Comment by jamescooke** [comment]
Have just spotted that the a query of Tasks included on these decorated pages also doesn't show the decoration on the Pages that are inside directories. Can provide an example if that's helpful.

**Comment by zefhemel** [comment]
I cannot replicate this, I'm doing exactly as you suggested and see this:

![CleanShot 2024-07-23 at 16 23 25@2x](https://github.com/user-attachments/assets/cb94c91d-ef6b-4865-b0b9-3959a3f4e088)

Query:

![CleanShot 2024-07-23 at 16 23 25@2x](https://github.com/user-attachments/assets/846a0534-85fd-42f9-b3a4-cd48a362ed6c)

![CleanShot 2024-07-23 at 16 23 54@2x](https://github.com/user-attachments/assets/0245f4ed-b48a-41db-85f0-ae2188dfe551)

![CleanShot 2024-07-23 at 16 24 06@2x](https://github.com/user-attachments/assets/35d1695f-83e8-490f-9cc8-3ed01488fb4b)


I'm running on the edge version of SB, but I don't think anything changed.

**Comment by jamescooke** [comment]
Hi @zefhemel  - thanks so much for checking on this and trying to reproduce.

I also got to where you were with a clean build running 0.8.2 and couldn't reproduce.

BUT then I realised there's a missing piece in my example above. I also have a `guides.md` page in the root:

```text
# Guides

Stuff to guide you.
```

👆🏻 Once this is created, I can refresh the clean install and the page decoration on the "Test Scrum" page disappears.

Just to confirm, this is the page structure:

```
.
├── guides
│   └── Test Scrum.md
├── guides.md
├── index.md
├── Library
│   └── Core
│       ...
├── SETTINGS.md
└── Test testing.md
```

And I'm guessing this is some kind of conflict between the `guides` directory and the `guides.md` page.

**Comment by zefhemel** [comment]
Found it.

**Comment by jamescooke** [comment]
Thanks Zef - got it working with the latest edge docker image:

![Screenshot from 2024-07-24 10-52-38](https://github.com/user-attachments/assets/4c293386-6d1a-4da4-baa8-caf9912ed1b4)
