### ISSUE TITLE
h1 in transclusion is styled more prominently than h1 in containing page

### ISSUE THREAD

**Issue by bjeanes** [silverbulletmd/silverbullet#971]
See screenshot:

![Screenshot 2024-07-23 at 9 45 30 am](https://github.com/user-attachments/assets/c9bd85a3-92d8-4afc-a429-87a0f093c5cf)

Both `Week` and `Goals` are `h1`s

**Comment by zefhemel** [comment]
Yep, this needs CSS adjustment.

**Comment by roceb** [comment]
Do we prefer the bigger h1 or the smaller one? I like the bigger one
because h1 should jump out of the page. The normal version can get confused
with h2. I often can't tell that type of header I am using

**Comment by zefhemel** [comment]
Personally I like the current header sizing, h1 below size options are these: https://github.com/silverbulletmd/silverbullet/blob/main/web/styles/editor.scss#L35

If they'd get any bigger like in the Live Preview version they'd get bigger than the actual page name at the top, which doesn't seem right.
