### ISSUE TITLE
`tags` and `itags` are not populated for pages when using `space.listPages()`

### ISSUE THREAD

**Issue by joekrill** [silverbulletmd/silverbullet#973]
I'm trying to add the ability to filter pages by tag in the [treeview plug](https://github.com/joekrill/silverbullet-treeview), but I'm running into a problem getting the tags for a given page. When I [call `space.listPages()`](https://github.com/joekrill/silverbullet-treeview/blob/main/api.ts#L41) it returns the list of pages but only the `tag` property is populated. The `tags` and `itags` properties are always undefined. It doesn't seem to matter whether page tags are added via Frontmatter or by simply putting the tag on the page somewhere - those properties are always undefined.

Is this by design? Is there some other way that should be used to retrieve the tags? Or is this a bug?

I've figured out how to get them using the `datastore` but this doesn't really feel right:

```ts
const pagesWithTags = await datastore.query({
  prefix: ["idx", "page"],
});
```

**Comment by zefhemel** [comment]
This is by design, meta data is kept in "page" objects that you can query using this: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/index/plug_api.ts#L22 

Example use: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/editor/complete.ts#L67

**Comment by joekrill** [comment]
> This is by design, meta data is kept in "page" objects that you can query using this: https://github.com/silverbulletmd/silverbullet/blob/main/plugs/index/plug_api.ts#L22

Oh Ok, got it, thanks!

**Comment by roceb** [comment]
How do i access that query from within spacescript?

**Comment by joekrill** [comment]
> How do i access that query from within spacescript?

You can use Syscalls [as described here](https://silverbullet.md/Space%20Script#Syscalls). For example:

```js
silverbullet.registerFunction({ name: "getPageCount" }, async () => {
  const pages = await syscall("system.invokeFunction", "index.queryObjects", "page")
  return pages.length;
});
```

Then in your template:

````md
```template
{{getPageCount()}}
```
````

**Comment by roceb** [comment]
Thanks, I read the section and assumed it meant space functions, so I could
call custom functions from within other functions. Thank you for clarifying
