### ISSUE TITLE
Error when updating the default core library

### ISSUE THREAD

**Issue by thedeany** [silverbulletmd/silverbullet#977]
I just got the Docker version of SB running tonight. I'm having trouble updating libraries though to install the default `"[[!silverbullet.md/Library/Core/*]]"` set. I have no other libraries configured to import. When I click the button to update libraries, I receive the following error in the UI:
> Error parsing command link arguments: t.startsWith is not a function

Checking the container logs reveals a few similar errors:
> An exception was thrown as a result of invoking function indexSpaceStyle error: t.startsWith is not a function
Error dispatching event page:index to index.indexSpaceStyle: t.startsWith is not a function
An exception was thrown as a result of invoking function parseIndexTextRepublish error: t.startsWith is not a function
Error dispatching event page:index_text to index.parseIndexTextRepublish: t.startsWith is not a function
An exception was thrown as a result of invoking function updateLibraries error: t.startsWith is not a function

This was with the latest docker image. I also tried on the edge tag, but I had the same issue. I've restarted and recreated the container multiple times, I've removed the .db files and had SB create things fresh... I'm out of ideas. Is this actually a bug?

Let me know what other information I can provide to assist in troubleshooting!

**Comment by zefhemel** [comment]
Ok, I cannot replicate this. Does this happen with a fresh space? Here's what I'm doing:

```
$ docker pull zefhemel/silverbullet
$ mkdir -p ~/testspace
$ docker run -it -v ~/testspace:/space -p3002:3000 zefhemel/silverbullet
```

I open up port 3002 (in this case), I get the onboarding page, click the "Libraries: Update" button there. It downloads stuff (35 files). And... all seems fine?

**Comment by thedeany** [comment]
Hmm, yes that does work. The only differences between that test and my original install is that I had created a couple test pages prior to trying the library update and that I'm using Docker Compose instead of running it directly. Perhaps something just got corrupted.

Anyhow, I'm back up now. Thanks for the quick response! Looking forward to checking this application out :)

**Comment by zefhemel** [comment]
It would still be interesting to learn what page broke it, because that shouldn't really happen.

**Comment by thedeany** [comment]
I wish I knew haha. I was looking through the code and there are only a few uses of `string.startsWith()`, but in the live version the code is obviously minified when inspecting via devtools and I couldn't exactly make sense of what was going on.
