### ISSUE TITLE
Is there a way to delete empty tags?

### ISSUE THREAD

**Issue by roceb** [silverbulletmd/silverbullet#978]
I currently have a query that displays all of my tags. In this query, therr is a tag called #"2024-07-05". It has no references and I want to delete.

**Comment by zefhemel** [comment]
Those should be deleted automatically. Are you sure there's no reference to it? You can try to check using tag pages, e.g. by visiting http://localhost:3000/%F0%9F%93%8C%202024-07-05

If that doesn't uncover some lingering use, you can try to run `Space: Reindex` to reindex the entire space and see if that helps.

**Comment by roceb** [comment]
Done that before and redid it again and nothing.

**Comment by roceb** [comment]
![Screenshot 2024-07-25 at 10 11 30 AM](https://github.com/user-attachments/assets/41b85a23-9281-4820-92c1-c64ec392bb77)
![Screenshot 2024-07-25 at 10 11 43 AM](https://github.com/user-attachments/assets/3aa02ee8-e665-4fc2-94a1-c985144ba144)

**Comment by roceb** [comment]
Figured it out using syscalls.
