### ISSUE TITLE
Page Decorations not working when defined in settings

### ISSUE THREAD

**Issue by itsallyours** [silverbulletmd/silverbullet#980]
Setup:

- new empty space
- running version 0.8.2
- Updated SETTINGS per screenshot below
- Updated index page with page decoration in frontmatter (worked)
- Created page "Anthony" with #person tag (page decoration didn't work)

![image](https://github.com/user-attachments/assets/989eb295-6d79-41d1-80ce-3b793e9d1d03)

![image](https://github.com/user-attachments/assets/df5a4d2f-ad6f-4c1d-a1d0-7d534060fb3f)

![image](https://github.com/user-attachments/assets/15912e16-de51-42a4-bf8e-dbc68ae68590)

**Comment by zefhemel** [comment]
You're missing quotes around person: `where: "tags = 'person'"`

If you check your browser's JavaScript console, you'll likely see a parse error about this.

**Comment by itsallyours** [comment]
You are correct on that.  I was initially trying it on my main space and it was not working.  I started with a simple space and copied a broken permutation.

With the correct syntax, it works in the test space without any problems.  I can use frontmatters or inline #tag.

However, in my main space only frontmatter works.  When I use inline #tag, it will not apply the icon.  

Not sure I understand what is going on.  I do have a large space (>1,000 md files).
I have tried the following without any luck
- changing text on the note to re-index it
- re-indexing the entire space
- stopping the docker container and deleting the db and restarting

Only placing the tag in the frontmatter works in my main space.

**Comment by zefhemel** [comment]
When using an inline tag to tag a page, that tag has to be the only thing on that line. If it's mixed with text it will be applied to the paragraph not the page. Are you doing that? For instance:

Ok:
```
#mytag

Hello!
```

Not ok:

```
#mytag Hello!
```

**Comment by itsallyours** [comment]
that explains it.  I was doing the following

```
## About
- #tag1
```
