### ISSUE TITLE
{{today}} and {{time}} seem inconsistent with each other in time zone

### ISSUE THREAD

**Issue by bjeanes** [silverbulletmd/silverbullet#981]
These 4 notes were created using the "Create a quick note" command in the core library, in succession as numbered:

![image](https://github.com/user-attachments/assets/640cb31d-f553-45a3-8ea8-06c816460737)

My TZ is AEST (+10/11). It's like the date portion from `{{today}}` was local time, but the `{{time}}` portion was derived from UTC.

**Comment by daydaya** [comment]
The answer to uestion may be here #680

**Comment by roceb** [comment]
Yes, but is there any reason why it doesn't work out of the box? People do
not expect to have to create a function just for current time now.

**Comment by daydaya** [comment]
Yes, I also think this should be the default, I was confused at first too

**Comment by bjeanes** [comment]
> The answer to question may be here #680

I agree! This issue seems to me to be a duplicate of that one. I will close this in favour of that one and add a comment.
