### ISSUE TITLE
Libraries: Update command results in message "An exception was thrown as a result of invoking function updateLibrariesCommand error: signal timed out"

### ISSUE THREAD

**Issue by ianelletson** [silverbulletmd/silverbullet#982]
Running in docker, edge image as of today (2024-07-26), tried Firefox and Chrome.

Received this message when clicking `Libraries: Update` button on `<site>/SETTINGS` page
Settings file:
```yaml
-libraries:
- import: "[[!silverbullet.md/Library/Core/*]]"
```

```
An exception was thrown as a result of invoking function updateLibrariesCommand error: signal timed out
(anonymous) @ federation.plug.js:1
```

**Comment by zefhemel** [comment]
Do you have a working Internet connection from your server? Can it reach https://silverbullet.md?

**Comment by ianelletson** [comment]
Yes, it was ultimately able to download the files (I tested with the Journal library, too). The error message does not occur on the Latest tag.

**Comment by zefhemel** [comment]
Ok. It could be that silverbullet.md was down as you tried. After an update it needs 20s or so to recover.

**Comment by ianelletson** [comment]
It just happened again (I tried it after seeing your message)
![image](https://github.com/user-attachments/assets/41688846-30f0-472d-933d-e96d55b6da15)

**Comment by zefhemel** [comment]
Anything you could see in the server log when this happens?

**Comment by ianelletson** [comment]
Yeah, unfortunately not helpful (I can get a text format if you'd rather)
![image](https://github.com/user-attachments/assets/dacfd285-05fd-456a-84b5-31ec016e9e48)

I just verified that this didn't happen in 0.8.2 but it does in 0.8.4
It seems that the libraries still get updated.
