### ISSUE TITLE
Files under _public show in autocomplete

### ISSUE THREAD

**Issue by josephembrey** [silverbulletmd/silverbullet#983]
I'm using the pub plug and have noticed that all non .md files under the _public directory show up when using autocomplete. They are hidden when using the page selector.

I tried reindexing and rebuilding the database but got the same behavior.

<img width="249" alt="Screenshot 2024-07-26 at 6 06 13 PM" src="https://github.com/user-attachments/assets/3f31fa68-cd71-4f95-98bb-ae390992821f">

**Comment by zefhemel** [comment]
Right, this is a regression, I'll have a look
