### ISSUE TITLE
Silverbullet compiles with wrong built target

### ISSUE THREAD

**Issue by MrMugame** [silverbulletmd/silverbullet#991]
When building a plug with the silverbullet utility that's using a library from `esm.sh`, the target is determined to be `denonext` (through the Useragent I think), which sometimes results in code that doesn't work in the browser (e.g. `node:*` apis). Tbh I'm unsure on how to fix this as I don't know if there is a way to specify the target across all package providers.

**Comment by zefhemel** [comment]
Yes, this is annoying and needs to be configured with every esm.sh dependency. I don't know how to work around this beyond what I do in import maps already. The same you'll need to do in plugs: see the target argument here: https://github.com/silverbulletmd/silverbullet/blob/a0f3f7ef414d64a779b812e544d74365ce46d67e/import_map.json#L8
