### ISSUE TITLE
Space Config

### ISSUE THREAD

**Issue by zefhemel** [silverbulletmd/silverbullet#999]
More and more stuff can now be defined in SETTINGS, and it would be nice to be able to split this file out. For this I would propose introducing `space-config` blocks, analogous to `space-script` and `space-style`. This would allow you to put pieces of SETTINGS anywhere in your space, and a full settings object would be assembled by deep-merging them all together.

Example

~~~
```space-config
indexPage: index
- where: 'false'
  attributes:
     yo: '10'
```

Elsewhere:

```space-config
objectDecorators:
- where: 'something'
  attributes:
     bla: '10'
```
~~~
Resulting in a combined:

~~~
```space-config
indexPage: index
- where: 'false'
  attributes:
     yo: '10'
- where: 'something'
  attributes:
     bla: '10'
```
~~~

**Comment by zefhemel** [comment]
This would also make it easier to add some YAML schema validation finally.

**Comment by raphwriter** [comment]
This might be out of scope... But wouldn't that also open up the possibility of _settings overrides_?
I.e. a space-config block that is located in `/note.md` would be overruled by `/path/to/somewhere/note.md` (and also only be valid for `path/to/somewhere/*.*`)
I don't know if that's even a sensible use case, tbh... Maybe different keyboard shortcuts for a certain subsection of your space - or something like that...?

**Comment by zefhemel** [comment]
That would make a lot of things very complicated I think. Let's come up with a valid use case first. 

By the way. This is implemented now (on main, not yet released). So closing this.
